// courseKeyLevel1.js
// KeyMaster Course · Key Level 1 — First Musicianship.
//
// The first level of the proper KeyMaster Course, beginning AFTER the Foundation
// Course (Foundation Stages 1–4). Appended to LEARN_STEPS after STAGE3_TWOHANDS_STEPS,
// so no Foundation step, title, chapter index, or resume position shifts.
//
// This module ships the OPENING ON-RAMP only — the "Reading Shapes into Music"
// chapter — and uses the existing educational-diagram renderer (whole noteheads,
// no manuscript). Proper manuscript (barlines, measures, time signature, note
// values, rests) is a separate gated track delivered before the first true piece.
//
// Original KeyMaster material. The Grade 1 practical + theory level is an INTERNAL
// seriousness benchmark only — no exam-board wording, repertoire, descriptors, or
// published exercises are used or reproduced anywhere.
//
// Voice: each step carries NEW `say` lines (id.say), spoken by TTS until recorded —
// no existing/recorded Jack line is touched. Jack-Coach scaffold (hint → reteach →
// gentle support reveal) follows the same data shape proven in Foundation.

export const KEY_LEVEL1_STEPS = [
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The KeyMaster Course begins', id: 'kl1-welcome',
    say: [
      { text: 'You have completed the Foundation Course. The whole map is yours now \u2014 the keyboard, the staff, the note names, and a steady pulse.', pauseAfter: 640, tone: 'warm' },
      { text: 'From here, the KeyMaster Course begins. This is Key Level 1 \u2014 First Musicianship.', pauseAfter: 520, tone: 'instruct' },
      { text: 'Everything you have learned now starts to become music: reading, rhythm, your hands, harmony, and your first real pieces \u2014 with me beside you the whole way.', pauseAfter: 380, tone: 'warm' },
    ],
    explain: ['You have completed the Foundation Course. Now the KeyMaster Course begins \u2014 Key Level 1, First Musicianship.', 'From here, reading, rhythm, technique, harmony, and pieces grow together. This is where you begin to play and think as a musician.'],
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Shapes are the building blocks', id: 'kl1-shapes-recap',
    say: [
      { text: 'In the Foundation you learned how notes move \u2014 by step, by skip, or by repeat. Those small moves are the building blocks of every melody.', pauseAfter: 600, tone: 'warm' },
      { text: 'Now we use them to make music. Read the shape, hear it, and play it \u2014 a little more each time.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Notes move by step, by skip, or by repeat \u2014 the building blocks of melody you met in the Foundation.', 'In Key Level 1 we turn those shapes into phrases, then into pieces \u2014 read, heard, and played.'],
    show: { kind: 'staff', clef: 'treble', notes: [ { midi: 67, value: 'whole' }, { midi: 69, value: 'whole' }, { midi: 71, value: 'whole' } ], caption: 'Step, skip, repeat \u2014 the building blocks of melody.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Your first phrase', id: 'kl1-first-phrase',
    say: [
      { text: 'Here is a short phrase. Read it as one shape \u2014 it rises by step, then returns home.', pauseAfter: 600, tone: 'warm' },
      { text: 'Listen to it first, then play it back.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['A five-note phrase that rises by step and returns \u2014 read it as one shape, not five separate notes.', 'Hear it, then play it in order.'],
    show: { kind: 'staff', clef: 'treble', notes: [ { midi: 67, value: 'whole' }, { midi: 69, value: 'whole' }, { midi: 71, value: 'whole' }, { midi: 69, value: 'whole' }, { midi: 67, value: 'whole' } ], caption: 'A little phrase \u2014 it rises by step, then returns home.' },
    demo: [67, 69, 71, 69, 67], demoGap: 0.46,
    tryPrompt: 'Play the phrase you see \u2014 up by step, then back home.',
    targets: [67, 69, 71, 69, 67], mode: 'sequence',
    okMsg: 'That sounded like music \u2014 a phrase with a shape, rising and returning. Beautifully read.',
    hint: 'Read it as a shape: step up, step up, then step back down the same way.',
    reteach: 'Take it gently \u2014 the phrase climbs three notes by step, then comes back down to where it started.',
    support: { highlight: [67, 69, 71], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Echo the phrase', id: 'kl1-phrase-echo',
    say: [
      { text: 'Now an echo. I will play a short phrase \u2014 listen to its shape, then play it back to me.', pauseAfter: 600, tone: 'warm' },
      { text: 'This one steps gently down, coming home.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['Listen to the phrase, then echo it back \u2014 the same shape, in your own time.', 'It steps downward and settles, like a line coming home.'],
    show: { kind: 'staff', clef: 'treble', notes: [ { midi: 72, value: 'whole' }, { midi: 71, value: 'whole' }, { midi: 69, value: 'whole' }, { midi: 67, value: 'whole' } ], caption: 'Listen, then echo \u2014 it steps down, coming home.' },
    demo: [72, 71, 69, 67], demoGap: 0.46,
    tryPrompt: 'Echo the phrase \u2014 stepping down, coming home.',
    targets: [72, 71, 69, 67], mode: 'sequence',
    okMsg: 'Yes \u2014 you heard the shape and echoed it. That is real musical listening.',
    hint: 'Listen again to the shape \u2014 it steps down, one note at a time, and settles at the bottom.',
    reteach: 'Hear it as a falling line: each note is one step lower than the last, until it comes to rest.',
    support: { highlight: [72, 71, 69, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Repeated notes', id: 'kl1-read-repeats',
    say: [
      { text: 'The simplest move of all is no move \u2014 a note that repeats. The same dot stays on the same line or space, and you play the same key again.', pauseAfter: 620, tone: 'warm' },
      { text: 'Here are two notes that each repeat. Play what you see \u2014 the same key, then the same key again.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A repeated note stays in the same place on the staff \u2014 you simply play the same key again.', 'Recognising a repeat before you play means your eye is reading shape, not spelling out every note.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 67, value: 'quarter', finger: 5 }, { midi: 67, value: 'quarter', finger: 5 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 64, value: 'quarter', finger: 3 } ], caption: 'Two notes, each repeated \u2014 the same key played again.' },
    demo: [67, 67, 64, 64], demoGap: 0.46,
    tryPrompt: 'Play what you see \u2014 a note repeated, then a lower note repeated.',
    targets: [67, 67, 64, 64], mode: 'sequence',
    okMsg: 'Good \u2014 you saw the repeats and played the same key again. That is reading shape at its simplest.',
    hint: 'The first two notes sit in the same place \u2014 same key twice. Then the pair drops lower and repeats again.',
    reteach: 'Gently \u2014 play the higher note twice, then the lower note twice. The lit keys show which two.',
    support: { highlight: [67, 64], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Steps upward', id: 'kl1-read-stepsup',
    say: [
      { text: 'When notes climb to the very next line or space each time, they are stepping upward \u2014 a row of 2nds, moving up one key at a time.', pauseAfter: 620, tone: 'warm' },
      { text: 'See how the notes rise, each just above the last. Play them climbing upward.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Notes that move to the next line or space each time are stepping \u2014 each one a 2nd above the last, one key at a time.', 'Reading "this steps up" is faster than naming four separate notes. Trust the shape.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 } ], caption: 'Stepping upward \u2014 each note one step higher than the last.' },
    demo: [60, 62, 64, 65], demoGap: 0.46,
    tryPrompt: 'Play the line climbing upward \u2014 each note one step higher.',
    targets: [60, 62, 64, 65], mode: 'sequence',
    okMsg: 'Yes \u2014 a smooth climb, one step at a time. You read the rising shape and followed it.',
    hint: 'Each note is just above the one before \u2014 keep moving up by single steps, finger after finger.',
    reteach: 'Slowly \u2014 thumb on C, then the next finger one step up, and the next, and the next. The lit keys show the climb.',
    support: { highlight: [60, 62, 64, 65], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Steps downward', id: 'kl1-read-stepsdown',
    say: [
      { text: 'Now the other direction. When notes fall to the very next line or space each time, they are stepping downward \u2014 still 2nds, but descending.', pauseAfter: 620, tone: 'warm' },
      { text: 'Watch the line fall, each note just below the last. Play it stepping down.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Stepping downward is the mirror of stepping up \u2014 each note a 2nd below the last, one key lower at a time.', 'Up or down, reading by step keeps your eye ahead of your hands.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 67, value: 'quarter', finger: 5 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 } ], caption: 'Stepping downward \u2014 each note one step lower than the last.' },
    demo: [67, 65, 64, 62], demoGap: 0.46,
    tryPrompt: 'Play the line stepping downward \u2014 each note one step lower.',
    targets: [67, 65, 64, 62], mode: 'sequence',
    okMsg: 'Lovely and even on the way down. Steps in both directions now read at a glance.',
    hint: 'Each note is just below the one before \u2014 keep moving down by single steps.',
    reteach: 'Gently \u2014 start on G with the little finger, then step down one finger at a time. The lit keys show the descent.',
    support: { highlight: [67, 65, 64, 62], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Skips', id: 'kl1-read-skips',
    say: [
      { text: 'A skip jumps further than a step \u2014 it leaps over a note. On the staff, it moves from a line to the next line, or a space to the next space. That is a 3rd.', pauseAfter: 640, tone: 'warm' },
      { text: 'Here the notes skip upward, then skip back down. Feel how much wider a skip is than a step. Play it.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A skip leaps over a note \u2014 line to next line, or space to next space \u2014 a 3rd, wider than a step.', 'Skips and steps look different on the page and feel different under the hand. Reading which is which is real fluency.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 60, value: 'quarter', finger: 1 } ], caption: 'Skipping up by 3rds \u2014 C to E to G \u2014 then skipping back down.' },
    demo: [60, 64, 67, 64, 60], demoGap: 0.46,
    tryPrompt: 'Play the skips \u2014 leap up by 3rds, then leap back down.',
    targets: [60, 64, 67, 64, 60], mode: 'sequence',
    okMsg: 'You felt those leaps \u2014 wider than steps, jumping over a note each time. That is a 3rd, up and down.',
    hint: 'Each jump skips over a key \u2014 do not land next-door, reach past it. Then reverse the leaps coming down.',
    reteach: 'Gently \u2014 thumb on C, skip to E, skip to G, then back down the same way. The lit keys show where to land.',
    support: { highlight: [60, 64, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Read it cold \u2014 step, skip, repeat', id: 'kl1-read-cold',
    say: [
      { text: 'Now put it together, and read it yourself \u2014 I will not play this one first. It has a repeat, a skip, and a step, all in four notes.', pauseAfter: 660, tone: 'warm' },
      { text: 'Look before you touch a key. Find each move: where it stays, where it skips, where it steps. Then play.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['A mixed pattern, read cold: a repeated note, then a skip up, then a step down. No demonstration \u2014 your reading does the work.', 'Name the moves in your head first \u2014 repeat, skip, step \u2014 then let your hand follow what your eye has read.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 } ], caption: 'Read it yourself \u2014 a repeat, a skip up, a step down. No listening first.' },
    tryPrompt: 'Read the four notes and play \u2014 repeat, skip up, step down.',
    targets: [60, 60, 64, 62], mode: 'sequence',
    okMsg: 'Read cold and played true \u2014 a repeat, a skip and a step, all seen and understood. That is the whole skill of reading.',
    hint: 'First note repeats \u2014 same key twice. Then a leap upward, skipping a key. Then a single step back down.',
    reteach: 'Slowly \u2014 play C twice, then skip up to E, then step down to D. Now the keys are lit to guide your reading.',
    support: { highlight: [60, 64, 62], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The pulse beneath the music', id: 'kl1-pulse-feel',
    say: [
      { text: 'Every piece of music has a pulse \u2014 a steady beat underneath, like a calm, unhurried heartbeat. You can feel it before you play a single note.', pauseAfter: 640, tone: 'warm' },
      { text: 'A musician feels that pulse first, then places the notes onto it. We will not rush \u2014 we feel the beat, and let the music rest on top of it.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['Music sits on a steady pulse \u2014 an even beat underneath, like a calm, unhurried heartbeat.', 'Feel the pulse first; the notes rest on top of it. This is the difference between playing in time and merely playing the right notes.'],
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Play on the beat', id: 'kl1-pulse-play',
    say: [
      { text: 'Let us feel four steady beats together. Count with me \u2014 one, two, three, four \u2014 evenly, never hurried.', pauseAfter: 620, tone: 'warm' },
      { text: 'Then play any note once on each beat, landing exactly with the pulse. Listen first, then join in.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['Count four even beats \u2014 one, two, three, four \u2014 and play a note exactly on each one.', 'Listen to the pulse first, then place each note onto a beat. Steady matters far more than fast.'],
    show: { kind: 'pulse' },
    tryPrompt: 'Play a note on each beat \u2014 one, two, three, four \u2014 landing with the pulse.',
    mode: 'count', count: 4,
    okMsg: 'Beautifully steady \u2014 you placed each note onto the pulse. That is what playing in time feels like.',
    hint: 'Let the count lead you \u2014 wait for each beat, then play exactly on it, not before.',
    reteach: 'Listen to the steady beat once more, then play one note on each pulse \u2014 even, unhurried, one to a beat.',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Keep the pulse going \u2014 eight beats', id: 'kl1-pulse-eight',
    say: [
      { text: 'You held four steady beats. Now hold eight \u2014 twice as far, the very same calm pulse. The challenge is to stay even all the way through.', pauseAfter: 620, tone: 'warm' },
      { text: 'Count with me and play a note on every beat \u2014 one to eight \u2014 never speeding up. Listen first, then join in.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Eight steady beats \u2014 a note on each. The same gentle pulse, simply carried further.', 'The test of pulse is staying even over time. Do not let the later beats hurry; keep the heartbeat calm right to the end.'],
    show: { kind: 'pulse' },
    tryPrompt: 'Play a note on every beat \u2014 one through eight \u2014 staying perfectly even.',
    mode: 'count', count: 8,
    okMsg: 'Steady all the way to eight \u2014 no rushing, no drifting. That is real control of the pulse.',
    hint: 'Let the beat lead \u2014 wait for each one and land on it. Even is the goal, not fast.',
    reteach: 'Listen to the steady pulse again, then place one calm note on each beat, all eight, like footsteps that never hurry.',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Steady, not rushing', id: 'kl1-pulse-rushing',
    say: [
      { text: 'Here is the secret that takes musicians years to master: keeping the pulse steady. The most common mistake is rushing \u2014 speeding up without meaning to, especially on the easy notes.', pauseAfter: 660, tone: 'warm' },
      { text: 'A steady pulse feels calm and even, like a slow clock. Rushing feels breathless, the beats crowding together. Always aim for calm and even.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['A steady pulse stays even \u2014 every beat the same distance apart, calm and unhurried, like a slow clock.', 'Rushing means speeding up without noticing, usually on the easy passages. The cure is to feel the beat and trust it, never racing ahead of it. Steady always sounds more musical than fast.'],
    show: { kind: 'pulse' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'How long each note lasts', id: 'kl1-notes-values',
    say: [
      { text: 'Notes do not only tell you which key to play \u2014 they tell you how long to hold it. The shape of the note is its length.', pauseAfter: 640, tone: 'warm' },
      { text: 'A semibreve, the whole note, is held for four beats. A minim, the half note, lasts two. A crotchet, the quarter note, is one beat. The longer notes are hollow; the crotchet is filled in.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['A note\u2019s shape tells you its length. A semibreve (whole note) is held for four beats; a minim (half note) for two; a crotchet (quarter note) for one.', 'The longer notes are hollow; the crotchet is filled in, with a stem. Same pitch, different lengths \u2014 this is rhythm beginning.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 67, value: 'whole' }, { midi: 67, value: 'half' }, { midi: 67, value: 'quarter' } ], caption: 'Semibreve (4 beats) \u00B7 minim (2 beats) \u00B7 crotchet (1 beat) \u2014 same note, different lengths.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Read the lengths and play', id: 'kl1-notes-read',
    say: [
      { text: 'Here is a short line in four-four time \u2014 four beats in the bar. Read the lengths as you play: two crotchets, then a minim held across two beats.', pauseAfter: 640, tone: 'warm' },
      { text: 'Listen to it first, then play the same notes, giving the long note its full length.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['A short line in four-four time. Read each note\u2019s length: two crotchets, one beat each, then a minim held for two \u2014 four beats in the bar.', 'Hear it, then play it, letting the minim breathe for its full two beats.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'half', finger: 3 } ], bars: [3], caption: 'Four-four time \u2014 crotchet, crotchet, minim. Four beats in the bar.' },
    demo: [60, 62, 64], demoGap: 0.5,
    tryPrompt: 'Play the line \u2014 two short notes, then the longer note held for two beats.',
    targets: [60, 62, 64], mode: 'sequence',
    okMsg: 'Yes \u2014 and you let the minim breathe for its full length. That is reading rhythm, not only notes.',
    hint: 'Read the lengths left to right: two short notes, then a longer one held twice as long.',
    reteach: 'Slowly now \u2014 play the two short notes, one beat each, then hold the last note for two full beats. The lit keys will guide your hand.',
    support: { highlight: [60, 62, 64], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Held, or played again?', id: 'kl1-notes-held',
    say: [
      { text: 'Two notes can share the same pitch yet sound quite different. One long note \u2014 a minim \u2014 is held, sounding once across two beats. Two crotchets are struck twice, a fresh sound on each beat.', pauseAfter: 660, tone: 'warm' },
      { text: 'Same key, different rhythm. Holding is not the same as repeating \u2014 the page tells you which the composer wants.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['A minim and two crotchets can sit on the same pitch but mean different things. The minim is one sound held across two beats; the two crotchets are struck separately, once each beat.', 'Reading rhythm means seeing not just which key, but whether to hold or to strike again. Held is smooth; repeated is articulated.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 67, value: 'half', finger: 5 }, { midi: 67, value: 'quarter', finger: 5 }, { midi: 67, value: 'quarter', finger: 5 } ], bars: [3], caption: 'A minim held across two beats, then two crotchets struck separately \u2014 same key, different rhythm.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A two-bar rhythm to read', id: 'kl1-notes-twobar',
    say: [
      { text: 'Now read a longer line \u2014 two full bars of four-four time. Watch the lengths: some notes are one beat, some are held for two.', pauseAfter: 640, tone: 'warm' },
      { text: 'Read across the barline without stopping, and give every long note its full count. Listen first, then play it through.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Two bars in four-four time. Each bar holds four beats: read the crotchets as single beats and the minims as held pairs.', 'Carry the pulse straight across the barline \u2014 the bar lines organise the counting, they do not stop the music.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'half', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'half', finger: 1 } ], bars: [3], caption: 'Two bars \u2014 crotchets and minims. Hold the long notes their full length.' },
    demo: [60, 62, 64, 62, 62, 60], demoGap: 0.5,
    tryPrompt: 'Play the two-bar line \u2014 short notes for one beat, long notes held for two.',
    targets: [60, 62, 64, 62, 62, 60], mode: 'sequence',
    okMsg: 'You read across both bars and let the long notes breathe. That is rhythm reading with real continuity.',
    hint: 'Follow the shape: it rises to a held note, then a repeated note, then settles low on another held note. Mind the two long notes.',
    reteach: 'Slowly \u2014 C, D, then E held for two beats; then D twice, then C held for two. The lit keys will guide your hand.',
    support: { highlight: [60, 62, 64, 62, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Morning Steps \u2014 listen first', id: 'kl1-piece-listen',
    say: [
      { text: 'Now your first real piece from manuscript \u2014 a little tune called Morning Steps. Look at it as a whole before you play.', pauseAfter: 640, tone: 'warm' },
      { text: 'The right hand rests over five notes, the thumb on C. It steps gently upward, then returns home and settles. Listen to how it sounds.', pauseAfter: 400, tone: 'instruct' },
    ],
    explain: ['Your first piece from manuscript: Morning Steps. The right hand sits over five notes \u2014 thumb on C \u2014 stepping gently upward, then home.', 'Read it as music: a rising line that turns and settles. Listen first, and let the shape sink in before you play.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'half', finger: 3 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Morning Steps \u2014 four-four time. It steps up, then returns home.' },
    demo: [60, 62, 64, 65, 64, 60], demoGap: 0.48,
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Morning Steps \u2014 now you play', id: 'kl1-piece-play',
    say: [
      { text: 'Now you play Morning Steps. Read the shape \u2014 four steps up, then home. Take your time; the notes matter more than the speed.', pauseAfter: 640, tone: 'warm' },
      { text: 'If you wander, I will help you find your way \u2014 a small hint first, and a closer look only if you need it.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Play Morning Steps from the manuscript. Read the rising shape \u2014 four steps up, then a turn and home \u2014 and let your fingers follow it.', 'Unhurried and even. Reading the shape well comes before playing fast.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'half', finger: 3 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Morning Steps \u2014 read the shape, and play it through.' },
    demo: [60, 62, 64, 65, 64, 60], demoGap: 0.48,
    tryPrompt: 'Play Morning Steps \u2014 up by step to the top, then turn and come home.',
    targets: [60, 62, 64, 65, 64, 60], mode: 'sequence',
    okMsg: 'That was real music \u2014 your first piece, read from the page and played with shape. Beautifully done.',
    hint: 'Follow the shape: it climbs four notes by step, then turns and comes home. Check where your hand sits against the next note.',
    reteach: 'Gently \u2014 the line rises one step at a time to the top, then steps down and rests on the note it began with. The lit keys will guide your hand.',
    support: { highlight: [60, 62, 64, 65, 64, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Rests \u2014 the silence in music', id: 'kl1-rests-intro',
    say: [
      { text: 'Music is not only sound. The silences matter just as much \u2014 and they are written down too. A written silence is called a rest.', pauseAfter: 640, tone: 'warm' },
      { text: 'Each note length has a matching rest. A crotchet rest is one beat of silence; a minim rest, two. You count a rest exactly as carefully as a note \u2014 the beat keeps going underneath.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['A rest is a written silence. Every note length has a matching rest \u2014 a crotchet rest is one beat of silence, a minim rest two beats.', 'The pulse never stops during a rest. You keep counting; you simply do not play. Silence is part of the music, not a gap in it.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 67, value: 'quarter' }, { rest: 'quarter' }, { midi: 67, value: 'quarter' }, { rest: 'quarter' } ], bars: [4], caption: 'Crotchet, crotchet rest, crotchet, crotchet rest \u2014 sound, silence, sound, silence.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Play through a rest', id: 'kl1-rests-play',
    say: [
      { text: 'Now read a short bar with a rest in it. Play the first note, then keep the second beat silent \u2014 that is the rest \u2014 then play the last two.', pauseAfter: 640, tone: 'warm' },
      { text: 'Count steadily through the silence: one, two, three, four. Do not let the rest hurry you on.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Read the bar: play on beat one, stay silent on beat two (the rest), then play on beats three and four.', 'Count right through the rest \u2014 one, two, three, four \u2014 so the silence keeps its full length.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 64, value: 'quarter', finger: 3 }, { rest: 'quarter' }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'quarter', finger: 1 } ], bars: [4], caption: 'Play \u00B7 rest \u00B7 play \u00B7 play \u2014 keep counting through the silence.' },
    tryPrompt: 'Play the bar \u2014 first note, a silent beat, then the last two notes.',
    targets: [64, 62, 60], mode: 'sequence',
    okMsg: 'Good \u2014 you let the rest breathe and kept your count. Silence handled like a musician.',
    hint: 'Three notes are played, with a silent beat after the first. Read the shape \u2014 it steps gently down to home.',
    reteach: 'Slowly \u2014 play the first note, count the silent beat, then step down two notes to the bottom. The lit keys will guide you.',
    support: { highlight: [64, 62, 60], replay: false },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A rest at the start', id: 'kl1-rests-read2',
    say: [
      { text: 'Sometimes a bar begins with silence. This one opens with a rest \u2014 so you wait, counting beat one, then come in on beat two.', pauseAfter: 640, tone: 'warm' },
      { text: 'Read it yourself and feel where you enter. Count one in silence, then step upward. Your turn.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['This bar opens with a crotchet rest \u2014 beat one is silent. You wait, counting it, then enter on beat two and step upward.', 'Coming in after a rest is a real musical skill: the silence is counted, not skipped, so you arrive in time.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { rest: 'quarter' }, { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 } ], bars: [4], caption: 'Silence on beat one \u2014 wait, count it, then step up from beat two.' },
    tryPrompt: 'Wait through the first silent beat, then play three steps upward.',
    targets: [60, 62, 64], mode: 'sequence',
    okMsg: 'You waited through the silence and came in right on time, then stepped up cleanly. Entering after a rest \u2014 nicely judged.',
    hint: 'Beat one is the rest \u2014 stay silent. Then three notes step upward from home, one at a time.',
    reteach: 'Count one silently, then play C, D, E stepping up. The lit keys show the climb after the rest.',
    support: { highlight: [60, 62, 64], replay: false },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Blue Window \u2014 listen first', id: 'kl1-blue-listen',
    say: [
      { text: 'Here is a second piece \u2014 Blue Window. This one falls gently, like a line drawn downward, then turns and comes home.', pauseAfter: 640, tone: 'warm' },
      { text: 'The right hand stays in its five-note home, thumb on C. Look at the shape, then listen to how it sounds.', pauseAfter: 400, tone: 'instruct' },
    ],
    explain: ['Your second piece: Blue Window. A gentle falling line \u2014 it steps downward from G, then turns and settles home on C.', 'Read the shape as a whole \u2014 a calm descent and a return. Listen first, and let it settle before you play.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 67, value: 'quarter', finger: 5 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'half', finger: 3 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Blue Window \u2014 four-four time. It falls by step, then turns home.' },
    demo: [67, 65, 64, 62, 64, 60], demoGap: 0.48,
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Blue Window \u2014 now you play', id: 'kl1-blue-play',
    say: [
      { text: 'Now you play Blue Window. Read the falling shape \u2014 G stepping down, then a turn and home to C. Unhurried.', pauseAfter: 640, tone: 'warm' },
      { text: 'Let the long notes at the end breathe. If you lose your way, I will guide you gently.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Play Blue Window from the manuscript. Read the falling shape \u2014 a gentle step-wise descent from G, then a turn and home to C.', 'Give the two minims at the end their full length. Read the shape; let the fingers follow.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 67, value: 'quarter', finger: 5 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'half', finger: 3 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Blue Window \u2014 read the falling shape, and play it through.' },
    demo: [67, 65, 64, 62, 64, 60], demoGap: 0.48,
    tryPrompt: 'Play Blue Window \u2014 falling by step from G, then a turn and home to C.',
    targets: [67, 65, 64, 62, 64, 60], mode: 'sequence',
    okMsg: 'Lovely \u2014 a calm, shaped line, read from the page and brought home. Two pieces now in your hands.',
    hint: 'Follow the shape downward \u2014 each note one step lower \u2014 then it lifts back up and settles home. Check the next note against where your hand is.',
    reteach: 'Gently \u2014 the line steps down four notes from the top, then rises one step and rests on home. The lit keys will guide your hand.',
    support: { highlight: [67, 65, 64, 62, 64, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'First Light \u2014 listen first', id: 'kl1-light-listen',
    say: [
      { text: 'A third piece \u2014 First Light. This one teaches a new thing: repeated notes, played gently, then a single skip that opens the melody up.', pauseAfter: 640, tone: 'warm' },
      { text: 'The right hand stays home over five notes. Listen for the two soft repeats, then the lift up to G.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['Your third piece: First Light. It opens with a repeated note \u2014 the same key, gently struck twice \u2014 then skips up to G before settling home.', 'Listen for the shape: repeat, repeat, a skip up, then a calm descent to rest on C.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 64, value: 'quarter', finger: 3 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'half', finger: 2 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'First Light \u2014 a repeated note, a skip up to G, then home.' },
    demo: [64, 64, 67, 64, 62, 60], demoGap: 0.48,
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'First Light \u2014 now you play', id: 'kl1-light-play',
    say: [
      { text: 'Now you play First Light. Strike the two repeated notes evenly, then reach up for the skip to G \u2014 do not let the repeats rush.', pauseAfter: 640, tone: 'warm' },
      { text: 'Then step gently down and rest on home. Listen once more in your mind, then play.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Play First Light: two even repeats on E, a skip up to G, then a calm step-wise descent home to C.', 'Keep the repeated notes steady \u2014 equal weight, no hurrying \u2014 and let the long notes at the end settle.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 64, value: 'quarter', finger: 3 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'half', finger: 2 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'First Light \u2014 even repeats, a skip to G, then home.' },
    demo: [64, 64, 67, 64, 62, 60], demoGap: 0.48,
    tryPrompt: 'Play First Light \u2014 two even repeats, skip up to G, then step home to C.',
    targets: [64, 64, 67, 64, 62, 60], mode: 'sequence',
    okMsg: 'Beautiful \u2014 even repeats, a clean skip, and a settled ending. Three pieces in your hands now.',
    hint: 'The first two notes repeat \u2014 same key, even. Then a leap up, back down, and a gentle step-wise fall to home.',
    reteach: 'Gently \u2014 E twice with finger three, skip up to G, back to E, then step down D to C. The lit keys will guide your hand.',
    support: { highlight: [64, 67, 62, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Walking Home \u2014 listen first', id: 'kl1-home-listen',
    say: [
      { text: 'A fourth piece \u2014 Walking Home. This one wanders a little before it finds its way back, the way a phrase often does. Notice how it ends on home, sounding finished.', pauseAfter: 660, tone: 'warm' },
      { text: 'Follow the line as it turns down, lifts again, and settles on C. That feeling of arriving is a phrase ending.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['Your fourth piece: Walking Home. The melody turns downward, lifts back up, and comes to rest on C \u2014 a clear sense of arriving home.', 'That settled feeling at the close is a phrase ending: the music sounds complete because it has returned to its home note.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'half', finger: 3 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Walking Home \u2014 it turns down, lifts, and ends home on C.' },
    demo: [64, 62, 60, 62, 64, 60], demoGap: 0.48,
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Walking Home \u2014 now you play', id: 'kl1-home-play',
    say: [
      { text: 'Now play Walking Home. Let it wander down, lift back up, and then \u2014 this is the important part \u2014 land softly on home, so it truly sounds finished.', pauseAfter: 640, tone: 'warm' },
      { text: 'Shape the ending: the last two notes are the phrase coming to rest. Play it through.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Play Walking Home: step down from E to C, lift back up to E, then settle home on C.', 'Give the ending its due \u2014 ease into the final home note so the phrase sounds complete, not just stopped.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'half', finger: 3 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Walking Home \u2014 wander down, lift, and rest on home.' },
    demo: [64, 62, 60, 62, 64, 60], demoGap: 0.48,
    tryPrompt: 'Play Walking Home \u2014 down to C, back up to E, then settle home on C.',
    targets: [64, 62, 60, 62, 64, 60], mode: 'sequence',
    okMsg: 'That ending really arrived \u2014 the phrase came home and sounded complete. Four pieces now, each teaching its own thing.',
    hint: 'It steps down to the bottom, turns and lifts back up, then comes to rest on home. Shape the last two notes as an ending.',
    reteach: 'Gently \u2014 E, D, C stepping down, back up to D and E, then home to C held. The lit keys will guide your hand.',
    support: { highlight: [64, 62, 60, 62, 64, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The left hand and the bass clef', id: 'kl1-lh-intro',
    say: [
      { text: 'So far your right hand has done the playing. Now the left hand joins, and it usually reads from the bass clef \u2014 the lower of the two clefs.', pauseAfter: 640, tone: 'warm' },
      { text: 'The bass clef carries the deeper notes, below Middle C. Here is a short left-hand line \u2014 notice the fingering counts the other way: the thumb is finger one, on the higher note.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['The left hand usually reads the bass clef \u2014 the lower clef, carrying the deeper notes below Middle C.', 'Left-hand fingering mirrors the right: the thumb is still finger one, but it now sits on the higher note, so the little finger takes the lowest note.'],
    show: { kind: 'staff', clef: 'bass', notes: [ { midi: 48, value: 'whole', finger: 5 } ], caption: 'The bass clef \u2014 the left hand\u2019s home. This low C is played by the little finger.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A first left-hand line', id: 'kl1-lh-play',
    say: [
      { text: 'Let your left hand rest over five notes, the little finger on the low C. Now play a gentle line \u2014 up by step, then back home.', pauseAfter: 640, tone: 'warm' },
      { text: 'Read it from the bass clef, and keep the hand calm. Listen first, then play.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Rest the left hand over five notes \u2014 little finger on low C. Play up by step to F, then turn and come home.', 'Read from the bass clef. Keep the hand still and let the fingers do the moving.'],
    show: { kind: 'staff', clef: 'bass', timeSig: [4, 4], notes: [ { midi: 48, value: 'quarter', finger: 5 }, { midi: 50, value: 'quarter', finger: 4 }, { midi: 52, value: 'quarter', finger: 3 }, { midi: 53, value: 'quarter', finger: 2 }, { midi: 52, value: 'half', finger: 3 }, { midi: 48, value: 'half', finger: 5 } ], bars: [4], caption: 'A left-hand line in the bass clef \u2014 up by step, then home.' },
    demo: [48, 50, 52, 53, 52, 48], demoGap: 0.5,
    tryPrompt: 'Play the left-hand line \u2014 up by step from low C, then turn and home.',
    targets: [48, 50, 52, 53, 52, 48], mode: 'sequence',
    okMsg: 'Well done \u2014 your left hand reading and playing from the bass clef. Both hands can read music now.',
    hint: 'Read the bass clef shape \u2014 it climbs by step, then turns and steps back down to where it began.',
    reteach: 'Slowly \u2014 little finger starts on low C, climb four notes by step, then come back down to home. The lit keys will guide your hand.',
    support: { highlight: [48, 50, 52, 53, 52, 48], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The left-hand five-finger pattern', id: 'kl1-lh-pattern',
    say: [
      { text: 'The right hand has its five-finger pattern; the left hand has one too, low in the bass clef. The hand stays still, the little finger anchored on low C.', pauseAfter: 640, tone: 'warm' },
      { text: 'Climb from C up to G and back, one finger to each note. Remember the left-hand fingering runs the other way \u2014 little finger low, thumb high. Listen, then play.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['The left-hand five-finger pattern lives in the bass clef: little finger on low C, thumb reaching up to G. Climb up and back, the hand staying home.', 'It builds the same evenness as the right-hand pattern, and teaches your left hand the shape that underpins so much bass-clef music.'],
    show: { kind: 'staff', clef: 'bass', timeSig: false, notes: [ { midi: 48, value: 'quarter', finger: 5 }, { midi: 50, value: 'quarter', finger: 4 }, { midi: 52, value: 'quarter', finger: 3 }, { midi: 53, value: 'quarter', finger: 2 }, { midi: 55, value: 'quarter', finger: 1 }, { midi: 53, value: 'quarter', finger: 2 }, { midi: 52, value: 'quarter', finger: 3 }, { midi: 50, value: 'quarter', finger: 4 }, { midi: 48, value: 'quarter', finger: 5 } ], caption: 'Left-hand pattern \u2014 low C up to G and back, little finger to thumb.' },
    demo: [48, 50, 52, 53, 55, 53, 52, 50, 48], demoGap: 0.42,
    tryPrompt: 'Play the left-hand pattern \u2014 up by step from low C to G, then back down.',
    targets: [48, 50, 52, 53, 55, 53, 52, 50, 48], mode: 'sequence',
    okMsg: 'Even and steady in the left hand too \u2014 and reading the bass clef as you go. Both hands have their pattern now.',
    hint: 'Climb by step to the top, then come back down the same path. Keep the hand anchored \u2014 only the fingers move.',
    reteach: 'Gently \u2014 little finger on low C, step up one finger at a time to the thumb on G, then step back down. The lit keys show the path.',
    support: { highlight: [48, 50, 52, 53, 55], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A short left-hand study', id: 'kl1-lh-study',
    say: [
      { text: 'Now a little study for the left hand alone \u2014 not just a pattern, but a small piece. It uses skips this time: low C up to E, up to G, and back.', pauseAfter: 640, tone: 'warm' },
      { text: 'Read it from the bass clef and keep the hand calm through the skips. Listen first, then play.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A short left-hand study built on skips: C up to E up to G, then a gentle step down to rest on home.', 'Skips in the left hand need a settled wrist \u2014 reach to each note without throwing the hand. Read the bass clef and stay calm.'],
    show: { kind: 'staff', clef: 'bass', timeSig: [4, 4], notes: [ { midi: 48, value: 'quarter', finger: 5 }, { midi: 52, value: 'quarter', finger: 3 }, { midi: 55, value: 'quarter', finger: 1 }, { midi: 52, value: 'quarter', finger: 3 }, { midi: 50, value: 'half', finger: 4 }, { midi: 48, value: 'half', finger: 5 } ], bars: [4], caption: 'A left-hand study \u2014 skipping up to G, then stepping home.' },
    demo: [48, 52, 55, 52, 50, 48], demoGap: 0.5,
    tryPrompt: 'Play the left-hand study \u2014 skip up to G, then step gently home.',
    targets: [48, 52, 55, 52, 50, 48], mode: 'sequence',
    okMsg: 'Well shaped \u2014 your left hand skipping and reading on its own. It is becoming a real musical partner.',
    hint: 'It skips upward through the chord, back down a skip, then steps gently to home. Reach the skips without jolting the hand.',
    reteach: 'Gently \u2014 low C, skip to E, skip to G, back to E, then step down to D and home C. The lit keys show the path.',
    support: { highlight: [48, 52, 55, 50, 48], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Both hands on the grand staff', id: 'kl1-hands-intro',
    say: [
      { text: 'Piano music joins the two clefs into one system \u2014 the grand staff. The treble clef on top for the right hand, the bass clef below for the left.', pauseAfter: 640, tone: 'warm' },
      { text: 'Reading both at once takes care, so we begin very gently: the left hand will hold one steady note while the right hand plays above it.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['The grand staff joins both clefs into one system \u2014 treble on top for the right hand, bass below for the left.', 'Two hands at once is the heart of piano playing. We begin gently: one held note in the left hand, a small melody in the right.'],
    show: { kind: 'staff', clef: 'grand', middleC: true, caption: 'The grand staff \u2014 right hand above, left hand below, joined by a brace.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A first move with both hands', id: 'kl1-hands-play',
    say: [
      { text: 'Here is your first move with both hands. Play the low C with your left hand and keep it gently held down.', pauseAfter: 620, tone: 'warm' },
      { text: 'Then, above it, play three notes with your right hand \u2014 C, E, G \u2014 the home chord, one note after another. Left first, then right.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['Your first two-hand move: the left hand plays and holds a low C, an anchor underneath.', 'Then the right hand plays C, E, G above it \u2014 one after another. The hands take turns: left settles first, then the right hand plays over the top.'],
    show: { kind: 'staff', clef: 'grand', timeSig: false, notes: [ { midi: 48, value: 'whole', finger: 5 }, { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 } ], caption: 'Left hand holds low C; right hand plays C, E, G above.' },
    demo: [48, 60, 64, 67], demoGap: 0.55,
    tryPrompt: 'Left hand plays and holds low C; then the right hand plays C, E, G above it.',
    targets: [48, 60, 64, 67], mode: 'sequence',
    okMsg: 'That is your first sound from two hands together \u2014 a held bass note and a melody above. A real pianist\u2019s texture.',
    hint: 'Start with the left hand on the low note, then move to the right hand and rise through the three notes above.',
    reteach: 'Gently \u2014 the low note first with the left hand, held; then the right hand climbs C, E, G. The lit keys show the path.',
    support: { highlight: [48, 60, 64, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Right hand holds, left hand moves', id: 'kl1-hands-rhhold',
    say: [
      { text: 'Last time the left hand held while the right moved. Now we swap: the right hand holds a high note, and the left hand walks underneath it.', pauseAfter: 640, tone: 'warm' },
      { text: 'Play and hold the high G with your right hand, then step up C, D, E with your left. The hands are learning to do different jobs at once.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['The roles reverse: the right hand plays and holds a high G while the left hand steps upward beneath it \u2014 C, D, E.', 'Each hand doing something different is the real beginning of two-hand playing. We take it one held note at a time.'],
    show: { kind: 'staff', clef: 'grand', timeSig: false, notes: [ { midi: 67, value: 'whole', finger: 5 }, { midi: 48, value: 'quarter', finger: 5 }, { midi: 50, value: 'quarter', finger: 4 }, { midi: 52, value: 'quarter', finger: 3 } ], caption: 'Right hand holds high G; left hand steps up C, D, E below.' },
    demo: [67, 48, 50, 52], demoGap: 0.55,
    tryPrompt: 'Hold the high G with the right hand, then step up C, D, E with the left.',
    targets: [67, 48, 50, 52], mode: 'sequence',
    okMsg: 'Two hands, two different jobs \u2014 one holding, one moving. This is exactly how hands learn to work together.',
    hint: 'Start with the right hand high and keep it down; then the left hand climbs three steps below.',
    reteach: 'Gently \u2014 right hand on high G, held; then left hand steps up C, D, E. The lit keys show both parts.',
    support: { highlight: [67, 48, 50, 52], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Hands taking turns', id: 'kl1-hands-turns',
    say: [
      { text: 'Here is another way hands work together \u2014 by taking turns, passing the music back and forth. Left, then right, then left, then right.', pauseAfter: 640, tone: 'warm' },
      { text: 'Play low C with the left, then C above with the right; then E with the left, and E above with the right. A gentle conversation between your hands.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['Hands can alternate, trading the line back and forth: left hand, right hand, left hand, right hand.', 'Taking turns builds coordination without needing both hands at the very same instant \u2014 a natural step toward true together-playing, which grows gradually from here.'],
    show: { kind: 'staff', clef: 'grand', timeSig: false, notes: [ { midi: 48, value: 'quarter', finger: 5 }, { midi: 60, value: 'quarter', finger: 1 }, { midi: 52, value: 'quarter', finger: 3 }, { midi: 64, value: 'quarter', finger: 3 } ], caption: 'Left, right, left, right \u2014 the hands passing the line between them.' },
    demo: [48, 60, 52, 64], demoGap: 0.5,
    tryPrompt: 'Take turns \u2014 left low C, right C, left E, right E.',
    targets: [48, 60, 52, 64], mode: 'sequence',
    okMsg: 'A lovely back-and-forth between the hands. Taking turns like this is how true two-hand playing is built, step by step.',
    hint: 'Alternate the hands \u2014 a low note in the left, then a higher one in the right, twice over, climbing a little each turn.',
    reteach: 'Gently \u2014 left hand low C, right hand C, left hand E, right hand E. The lit keys show whose turn is whose.',
    support: { highlight: [48, 60, 52, 64], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Why fingering matters', id: 'kl1-finger-why',
    say: [
      { text: 'You may have noticed small numbers beside the notes. Those are fingering \u2014 they tell you which finger to use, and they are chosen with care.', pauseAfter: 640, tone: 'warm' },
      { text: 'Good fingering lets your hand stay calm and reach every note without jumping about. The right finger in the right place is what makes playing feel easy.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['The small numbers beside notes are fingering: one is the thumb, up to five at the little finger. They are not random \u2014 they are chosen so the hand can move smoothly.', 'Good fingering keeps the hand settled and lets it reach every note without leaping. Trust the numbers, and playing becomes far easier.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 67, value: 'quarter', finger: 5 } ], caption: 'One finger to each note \u2014 thumb on C, up to the little finger on G.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A smooth, connected touch', id: 'kl1-finger-play',
    say: [
      { text: 'Now play with a smooth, connected touch \u2014 we call it legato. Each note joins to the next with no gap, as if drawing one unbroken line.', pauseAfter: 640, tone: 'warm' },
      { text: 'Hold each key just until the next one sounds, then release. The fingering keeps your hand steady so the line can stay smooth.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Legato means smooth and connected \u2014 each note joined to the next with no gap between them.', 'Hold each key until the next sounds, then let go. With the hand settled on its fingering, the line flows as one.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 60, value: 'quarter', finger: 1 } ], bars: [4], caption: 'A smooth line \u2014 connect each note to the next, no gaps.' },
    demo: [60, 62, 64, 60], demoGap: 0.5,
    tryPrompt: 'Play the four notes smoothly \u2014 each joined to the next, no gaps.',
    targets: [60, 62, 64, 60], mode: 'sequence',
    okMsg: 'That had a smooth, singing line \u2014 connected and calm. That is legato touch.',
    hint: 'Read the small shape \u2014 it steps up, then returns to where it started. Aim to join each note to the next.',
    reteach: 'Gently \u2014 thumb on C, step up to E, then back to the thumb. Connect the sound, no gaps. The lit keys will guide you.',
    support: { highlight: [60, 62, 64, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A crisp, detached touch', id: 'kl1-finger-detached',
    say: [
      { text: 'You have a smooth legato touch. Now meet its opposite \u2014 a detached touch, where each note is short and separate, with a little space after it.', pauseAfter: 640, tone: 'warm' },
      { text: 'Play these five notes crisply \u2014 press, then lift the finger cleanly so each note stands on its own. Light and bouncy, never heavy.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['A detached touch is the opposite of legato: each note short and separate, lifted cleanly so a little silence follows it.', 'Legato sings; detached dances. A musician chooses between them to shape the character of a piece. Keep detached notes light, never banged.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 67, value: 'quarter', finger: 5 } ], caption: 'Five notes, played crisp and detached \u2014 each one short and separate.' },
    demo: [60, 62, 64, 65, 67], demoGap: 0.5,
    tryPrompt: 'Play the five notes detached \u2014 each one short, crisp and separate.',
    targets: [60, 62, 64, 65, 67], mode: 'sequence',
    okMsg: 'Crisp and light \u2014 each note stood on its own. Now you have two touches to choose from: smooth and detached.',
    hint: 'Climb the five notes by step, but keep each one short \u2014 press and lift cleanly, a little gap between.',
    reteach: 'Gently \u2014 thumb to little finger, C up to G, lifting each finger crisply. The lit keys show the climb.',
    support: { highlight: [60, 62, 64, 65, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A phrase, guided by fingering', id: 'kl1-finger-phrase',
    say: [
      { text: 'Now a small musical phrase \u2014 and this time, let the fingering lead you. Follow the numbers exactly, and notice how the hand never has to jump.', pauseAfter: 640, tone: 'warm' },
      { text: 'Play it smoothly, trusting the fingers shown. Good fingering is what makes a phrase feel effortless. Listen, then play.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A short phrase with fingering to follow: thumb, then a skip up under finger three, a step down to two, and home to the thumb.', 'When you trust the printed fingering, the hand stays settled and the phrase plays itself. Reading the numbers is part of reading the music.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Follow the fingering \u2014 the hand stays calm and the phrase flows.' },
    demo: [60, 64, 62, 60], demoGap: 0.5,
    tryPrompt: 'Play the phrase, following the fingering shown \u2014 smooth and settled.',
    targets: [60, 64, 62, 60], mode: 'sequence',
    okMsg: 'Smooth and unhurried \u2014 the fingering kept your hand calm and the phrase sang. That is what the numbers are for.',
    hint: 'Thumb first, then a skip up, a step back down, and home to the thumb. Let the fingering guide the moves.',
    reteach: 'Gently \u2014 thumb on C, skip up to E with finger three, step down to D, home to C. The lit keys show the path.',
    support: { highlight: [60, 64, 62, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Steps and skips \u2014 2nds and 3rds', id: 'kl1-intervals-intro',
    say: [
      { text: 'The distance between two notes is called an interval, and we name intervals by number. Two notes next-door to each other make a 2nd \u2014 that is a step.', pauseAfter: 640, tone: 'warm' },
      { text: 'Skip a note, and the distance grows to a 3rd \u2014 that is a skip. From C, the next-door D is a 2nd; jump over D to E, and that is a 3rd.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['An interval is the distance between two notes, named by number. Notes next to each other are a 2nd \u2014 a step.', 'Skip one note and you reach a 3rd \u2014 a skip. C up to D is a 2nd; C up to E, skipping D, is a 3rd. Reading these distances is faster than naming every note.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 } ], caption: 'C to D is a 2nd (a step) \u00B7 C to E, skipping D, is a 3rd (a skip).' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Hear a step, hear a skip', id: 'kl1-intervals-play',
    say: [
      { text: 'Now play a line that uses both. First three steps \u2014 C, D, E, each a 2nd \u2014 then a skip up to G, a 3rd.', pauseAfter: 640, tone: 'warm' },
      { text: 'Listen to how the skip opens up wider than the steps. Hear it first, then play it.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Play C, D, E \u2014 three notes a step apart, each a 2nd \u2014 then skip up to G, a 3rd.', 'Notice the skip sounds wider than the steps. Reading by distance \u2014 step or skip \u2014 is how fluent readers move.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 } ], bars: [4], caption: 'Steps up by 2nds \u2014 C, D, E \u2014 then a skip of a 3rd to G.' },
    demo: [60, 62, 64, 67], demoGap: 0.5,
    tryPrompt: 'Play three steps up \u2014 C, D, E \u2014 then skip a 3rd to G.',
    targets: [60, 62, 64, 67], mode: 'sequence',
    okMsg: 'Yes \u2014 you felt the difference: three steps, then a wider skip. That is reading by interval.',
    hint: 'Three notes move by step, close together; then the last one leaps wider. Read the distances, not the names.',
    reteach: 'Slowly \u2014 step up C, D, E one at a time, then skip past F to land on G. The lit keys will guide your hand.',
    support: { highlight: [60, 62, 64, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A melody made of 2nds', id: 'kl1-intervals-2nd',
    say: [
      { text: 'Let us live inside the 2nd for a moment. Here is a little melody where every move is a 2nd \u2014 a step \u2014 rising and then falling back.', pauseAfter: 620, tone: 'warm' },
      { text: 'Because every move is a step, your fingers move to the very next note each time. Hear how smooth a line of 2nds sounds. Play it.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A melody built entirely from 2nds: every note steps to its neighbour, up then back down.', 'Lines made of 2nds feel smooth and connected \u2014 the ear hears a gentle, walking motion. Recognising a run of 2nds lets you read a whole phrase at a glance.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'quarter', finger: 1 } ], caption: 'Every move a 2nd \u2014 a smooth, stepping line up and back.' },
    demo: [60, 62, 64, 62, 60], demoGap: 0.46,
    tryPrompt: 'Play the melody of 2nds \u2014 step up, step back down.',
    targets: [60, 62, 64, 62, 60], mode: 'sequence',
    okMsg: 'Smooth and connected \u2014 a line of pure 2nds. You can feel how steps make a melody flow.',
    hint: 'Every move is to the next-door note \u2014 up three, then back down three, never skipping.',
    reteach: 'Gently \u2014 C, D, E stepping up, then E, D, C stepping back. The lit keys show the small steps.',
    support: { highlight: [60, 62, 64], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Reaching for 3rds', id: 'kl1-intervals-3rd',
    say: [
      { text: 'Now the 3rd \u2014 the skip. From a note, a 3rd reaches past its neighbour to the note beyond. From C, a 3rd is E; from D, a 3rd is F.', pauseAfter: 640, tone: 'warm' },
      { text: 'Play two 3rds \u2014 C up to E, then D up to F. Feel your hand reach a little wider than a step. Listen, then play.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A 3rd skips past one note: from C reach to E, from D reach to F. Wider than a step, and the ear hears the gap open up.', 'Spotting 3rds \u2014 line to next line, or space to next space \u2014 lets you read leaps as easily as steps.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 65, value: 'quarter', finger: 4 } ], caption: 'Two 3rds \u2014 C up to E, then D up to F. Each one a skip.' },
    demo: [60, 64, 62, 65], demoGap: 0.5,
    tryPrompt: 'Play two 3rds \u2014 C up to E, then D up to F.',
    targets: [60, 64, 62, 65], mode: 'sequence',
    okMsg: 'You reached those 3rds cleanly \u2014 each one skipping past a note. Steps and skips both under your hands now.',
    hint: 'Each pair leaps past one key \u2014 C reaching up to E, then D reaching up to F. Reach, do not step.',
    reteach: 'Gently \u2014 thumb on C, skip up to E; then finger two on D, skip up to F. The lit keys show where to land.',
    support: { highlight: [60, 64, 62, 65], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Step or skip? Feel the difference', id: 'kl1-intervals-compare',
    say: [
      { text: 'Here is the comparison that matters most. First a 2nd \u2014 C to D, a step, next-door. Then a 3rd \u2014 C to E, a skip, reaching past.', pauseAfter: 640, tone: 'warm' },
      { text: 'On the keys, the skip is wider. On the page, the step goes line-to-space while the skip goes line-to-line. Play both, and feel the difference.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['Side by side: C up to D is a 2nd, a step; C up to E is a 3rd, a skip. The skip is wider on the keyboard, and wider on the staff too.', 'Reading by step or skip \u2014 by the distance, not the name \u2014 is what lets fluent players move so quickly. Feel both and the difference becomes instinct.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 } ], caption: 'A 2nd then a 3rd \u2014 C up to D, the step; C up to E, the skip.' },
    demo: [60, 62, 60, 64], demoGap: 0.52,
    tryPrompt: 'Play a step, then a skip \u2014 C up to D, then C up to E.',
    targets: [60, 62, 60, 64], mode: 'sequence',
    okMsg: 'You felt it \u2014 the step lands next-door, the skip reaches past. That instinct is the heart of reading by interval.',
    hint: 'First reach only to the next key \u2014 a step. Return home, then reach wider, past one key \u2014 a skip.',
    reteach: 'Gently \u2014 C up to D, the step; back to C; then C up to E, the skip. The lit keys show both distances.',
    support: { highlight: [60, 62, 64], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The five-finger pattern', id: 'kl1-fivefinger-play',
    say: [
      { text: 'Here is a pattern every pianist learns \u2014 the five-finger pattern. Your hand stays perfectly still, one finger to each note, up to the top and back.', pauseAfter: 640, tone: 'warm' },
      { text: 'From C, climb by step to G \u2014 thumb to little finger \u2014 then come back down. No jumping; the hand stays home. Listen, then play.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['The five-finger pattern: five notes, five fingers, the hand completely still. From C, step up to G \u2014 thumb, two, three, four, five \u2014 then step back down to C.', 'It trains evenness and a calm hand. Many pieces live inside this shape, so it is worth playing until it feels effortless.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 67, value: 'quarter', finger: 5 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'quarter', finger: 1 } ], caption: 'Up to G and back \u2014 one finger to each note, the hand staying home.' },
    demo: [60, 62, 64, 65, 67, 65, 64, 62, 60], demoGap: 0.42,
    tryPrompt: 'Play the five-finger pattern \u2014 up by step from C to G, then back down to C.',
    targets: [60, 62, 64, 65, 67, 65, 64, 62, 60], mode: 'sequence',
    okMsg: 'Beautifully even, and your hand stayed home the whole way. That pattern is the foundation of so much playing.',
    hint: 'Climb by step to the top, then reverse exactly \u2014 the way down mirrors the way up. Keep the hand still.',
    reteach: 'Gently and evenly \u2014 thumb on C, step up one finger at a time to the little finger on G, then step back down the same path. The lit keys will guide you.',
    support: { highlight: [60, 62, 64, 65, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Why patterns and scales matter', id: 'kl1-fivefinger-why',
    say: [
      { text: 'You might wonder why we practise patterns at all. Here is why: a pattern trains your fingers to move evenly and independently, so that when a real piece arrives, your hand already knows the shape.', pauseAfter: 660, tone: 'warm' },
      { text: 'The five-finger pattern hides inside countless melodies. Master it, and you are not just doing an exercise \u2014 you are learning the alphabet that pieces are written in.', pauseAfter: 400, tone: 'instruct' },
    ],
    explain: ['Patterns and scales build even, independent fingers and a calm, settled hand \u2014 the physical foundation every piece relies on.', 'The five-finger pattern lives inside a huge amount of music. Practising it is not busy-work; it is rehearsing the shapes you will meet again and again in real pieces.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 67, value: 'quarter', finger: 5 } ], caption: 'The shape that hides inside so many melodies \u2014 worth knowing by heart.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Evenness \u2014 every note equal', id: 'kl1-fivefinger-even',
    say: [
      { text: 'Now play the pattern again, but with one goal only: evenness. Every note the same weight, the same length, like a row of identical pearls.', pauseAfter: 640, tone: 'warm' },
      { text: 'The little finger is naturally weaker, so give it a touch more attention. Slow and even beats fast and uneven, every time. Listen, then play.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['The same five-finger pattern, up and back \u2014 but now listening for evenness: equal weight and equal length on every note.', 'Watch the weaker fingers, the fourth and fifth, and let them match the others. Evenness is what turns an exercise into real control.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 67, value: 'quarter', finger: 5 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'quarter', finger: 1 } ], caption: 'Up and back \u2014 every note equal in weight and length.' },
    demo: [60, 62, 64, 65, 67, 65, 64, 62, 60], demoGap: 0.44,
    tryPrompt: 'Play the pattern up and back \u2014 every note even, equal, unhurried.',
    targets: [60, 62, 64, 65, 67, 65, 64, 62, 60], mode: 'sequence',
    okMsg: 'Even and controlled, all the way up and back \u2014 weaker fingers matching the rest. That evenness is hard-won and worth it.',
    hint: 'Climb to the top and mirror the path back down \u2014 and listen: are all the notes truly equal? Keep them even.',
    reteach: 'Slowly and evenly \u2014 thumb to little finger and back, every note the same. The lit keys show the path; let your ear judge the evenness.',
    support: { highlight: [60, 62, 64, 65, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Home note \u2014 the tonic', id: 'kl1-harmony-tonic',
    say: [
      { text: 'Every key has a home note \u2014 the note the music rests on, where a tune feels finished. Musicians call it the tonic.', pauseAfter: 640, tone: 'warm' },
      { text: 'In the key of C major, the home note is C. You have felt it already \u2014 both your pieces came to rest on C. That feeling of arriving home is the tonic.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['Every key has a home note \u2014 the tonic \u2014 where music feels settled and complete. In C major, that home note is C.', 'You have heard it without naming it: Morning Steps and Blue Window both came to rest on C. That sense of arriving home is the pull of the tonic.'],
    show: { kind: 'staff', clef: 'treble', notes: [ { midi: 60, value: 'whole', finger: 1, letter: 'C' } ], middleC: false, caption: 'C \u2014 the home note, the tonic of C major. Where the music comes to rest.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The home chord, one note at a time', id: 'kl1-harmony-triad',
    say: [
      { text: 'Three notes belong specially to the home note: C, E and G. Together they make the home chord \u2014 the tonic triad. Built from C, skipping to E, skipping again to G.', pauseAfter: 640, tone: 'warm' },
      { text: 'Played all at once they make a chord; played one after another they make a broken chord. Let us play it broken \u2014 C, E, G, and back. Listen, then play.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['The home chord \u2014 the tonic triad \u2014 is built on C: C, then a skip to E, then a skip to G. Three notes that belong together.', 'Sounded together they are a chord; sounded one at a time they are a broken chord. Playing it broken \u2014 C, E, G and back \u2014 lets you hear each note of the harmony.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 60, value: 'quarter', finger: 1 } ], caption: 'The tonic triad as a broken chord \u2014 C, E, G, then back home.' },
    demo: [60, 64, 67, 64, 60], demoGap: 0.46,
    tryPrompt: 'Play the home chord broken \u2014 C, E, G, then back down to C.',
    targets: [60, 64, 67, 64, 60], mode: 'sequence',
    okMsg: 'That is the sound of home harmony \u2014 the tonic triad, the chord at the heart of the key. Your first harmony.',
    hint: 'Skip upward through the chord \u2014 each note a 3rd above the last \u2014 then come back down the same way.',
    reteach: 'Gently \u2014 thumb on C, skip to E with finger three, skip to G with finger five, then back down. The lit keys will guide your hand.',
    support: { highlight: [60, 64, 67, 64, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Harmony holding up a melody', id: 'kl1-harmony-melody',
    say: [
      { text: 'Harmony is not just a stack of notes \u2014 it is support. Listen: the left hand holds the home note, C, while the right hand sings a small melody above it.', pauseAfter: 660, tone: 'warm' },
      { text: 'Play and hold low C with your left hand, then let the right hand step down to it \u2014 E, D, C. Feel how the held note holds the melody up.', pauseAfter: 400, tone: 'instruct' },
    ],
    explain: ['Harmony supports melody. Here the left hand holds the home note while the right hand plays a short tune above \u2014 E, D, C, settling home.', 'The steady home note underneath gives the melody a place to rest. That is what harmony does: it holds the tune up and gives it a home.'],
    show: { kind: 'staff', clef: 'grand', timeSig: false, notes: [ { midi: 48, value: 'whole', finger: 5 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'quarter', finger: 1 } ], caption: 'Left hand holds home C; right hand sings E, D, C above it.' },
    demo: [48, 64, 62, 60], demoGap: 0.55,
    tryPrompt: 'Hold low C with the left hand, then play E, D, C with the right above it.',
    targets: [48, 64, 62, 60], mode: 'sequence',
    okMsg: 'Hear how the held home note supported the melody \u2014 harmony and tune together. That is real music-making.',
    hint: 'Left hand on the low home note first, held; then the right hand steps down from E to home.',
    reteach: 'Gently \u2014 left hand holds low C; then right hand plays E, D, C stepping down. The lit keys show both parts.',
    support: { highlight: [48, 64, 62, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The home chord, falling', id: 'kl1-harmony-broken2',
    say: [
      { text: 'You played the home chord rising. Now hear it fall \u2014 the same three notes, G, E, C, broken from the top downward. The same harmony, a different shape.', pauseAfter: 640, tone: 'warm' },
      { text: 'Skip down through the chord \u2014 G to E to C \u2014 each step a 3rd. Listen, then play it falling home.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['The tonic triad again, this time broken downward: G, E, C \u2014 each a 3rd below the last, arriving home on C.', 'Knowing the home chord in both directions, rising and falling, means you truly own it \u2014 ready to use it as melody or as support.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 67, value: 'quarter', finger: 5 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 60, value: 'quarter', finger: 1 } ], caption: 'The home chord falling \u2014 G, E, C, each a 3rd down to home.' },
    demo: [67, 64, 60], demoGap: 0.5,
    tryPrompt: 'Play the home chord falling \u2014 G down to E down to C.',
    targets: [67, 64, 60], mode: 'sequence',
    okMsg: 'The home chord, rising and falling \u2014 you own it now, in both directions. Your first harmony, fully in hand.',
    hint: 'Skip downward through the chord \u2014 each note a 3rd below the last, reaching past one key, home to C.',
    reteach: 'Gently \u2014 little finger on G, skip down to E, skip down to C. The lit keys show where to land.',
    support: { highlight: [67, 64, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Listen, then echo \u2014 by ear', id: 'kl1-echo-task',
    say: [
      { text: 'This time there is no music to read. I will play a short phrase, and you play it straight back to me \u2014 by ear alone.', pauseAfter: 640, tone: 'warm' },
      { text: 'Listen to the shape: where it rises, where it falls. Hold it in your ear, then find it on the keys. Listen carefully now.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['No notation this time \u2014 pure listening. I play a short phrase; you echo it straight back from memory.', 'Hold the shape in your ear \u2014 its rise and fall \u2014 then find it on the keys. Playing by ear is a musician\u2019s deepest skill.'],
    demo: [62, 64, 65, 64], demoGap: 0.46,
    tryPrompt: 'Play back the phrase you just heard \u2014 by ear.',
    targets: [62, 64, 65, 64], mode: 'sequence',
    okMsg: 'You held the shape in your ear and found it on the keys \u2014 with no notation at all. That is real musicianship.',
    hint: 'Sing the shape back in your head first \u2014 it rises a little, lifts once more, then settles back. Then find those notes.',
    reteach: 'Listen again to the shape: it steps up, lifts to the highest note, then comes back. The lit keys will show you where it lives.',
    support: { highlight: [62, 64, 65, 64], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Sight-reading \u2014 read it cold', id: 'kl1-sight-micro',
    say: [
      { text: 'Now a sight-reading moment. This is a phrase you have not heard \u2014 and I will not play it for you. Reading something new, on your own, is sight-reading.', pauseAfter: 660, tone: 'warm' },
      { text: 'Look before you play. Find the shape \u2014 does it step up or down? Then play it, calmly, in your own time.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['Sight-reading means reading and playing something new without hearing it first. No demonstration this time \u2014 the reading is yours.', 'Look first: find the starting note and the shape of the line. Then play it slowly and steadily. Reading before playing is the whole habit.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'half', finger: 1 } ], bars: [3], caption: 'Read it yourself \u2014 find the shape, then play. No listening first.' },
    tryPrompt: 'Read the line and play it \u2014 on your own, without hearing it first.',
    targets: [64, 62, 60], mode: 'sequence',
    okMsg: 'You read that one cold and played it true \u2014 sight-reading, the skill that opens every piece of music to you.',
    hint: 'Find the first note, then follow the shape \u2014 it steps downward, one note at a time, to a held note at the bottom.',
    reteach: 'Take it slowly \u2014 the line begins up high and steps down to a long note at home. Now the keys are lit to show you; read the shape with them.',
    support: { highlight: [64, 62, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Key Level 1 \u2014 how far you have come', id: 'kl1-review',
    say: [
      { text: 'Take a moment. Look at how much you can do now. You read shapes instead of spelling out every note. You feel a pulse and count through rests.', pauseAfter: 640, tone: 'warm' },
      { text: 'You read both clefs, play with each hand, and have begun bringing them together. You know steps and skips, the home note, and the home chord \u2014 and you have two real pieces in your hands.', pauseAfter: 480, tone: 'warm' },
      { text: 'This is genuine musicianship beginning. When you are ready, Key Level 2 \u2014 Confident Reading \u2014 will take it further. Beautifully done.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Look back at Key Level 1. You read music by shape, feel a steady pulse, count note values and rests, and read both treble and bass clefs.', 'You play with each hand and have begun two-hand coordination; you understand steps, skips, the tonic, and the tonic triad; and you have played real pieces \u2014 Morning Steps and Blue Window \u2014 from manuscript.', 'These are the true first foundations of musicianship. Key Level 2 \u2014 Confident Reading \u2014 builds directly on them when you are ready. This is a real beginning, beautifully made.'],
    show: { kind: 'staff', clef: 'grand', middleC: true, caption: 'Both clefs, both hands, the home note at the centre \u2014 the ground you now stand on.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A two-note echo', id: 'kl1-echo-two',
    say: [
      { text: 'Let us train the ear with something small. I will play just two notes; you play them straight back.', pauseAfter: 600, tone: 'warm' },
      { text: 'Listen for the gap between them \u2014 do they sit close, or open up wide? Listen now.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['Just two notes, by ear. Hear whether they are close together or far apart, then find them on the keys.', 'No notation \u2014 this is pure listening. Small echoes train the ear that every musician relies on.'],
    demo: [60, 64], demoGap: 0.5,
    tryPrompt: 'Play back the two notes you just heard.',
    targets: [60, 64], mode: 'sequence',
    okMsg: 'Two notes, caught by ear and played back. The ear is waking up.',
    hint: 'The second note was higher, a little reach above the first. Find the lower one, then jump up.',
    reteach: 'Listen again \u2014 a low note, then a higher one a short skip above. The lit keys show where they live.',
    support: { highlight: [60, 64], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A three-note echo', id: 'kl1-echo-three',
    say: [
      { text: 'Now three notes. A little more to hold in your ear \u2014 listen to the whole shape before you play.', pauseAfter: 600, tone: 'warm' },
      { text: 'Does it rise, fall, or turn? Hold the shape, then play it back. Listening now.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['Three notes by ear. Hear the shape as a whole \u2014 rising, falling, or turning \u2014 before you reach for the keys.', 'Holding a short shape in the ear and reproducing it is real musical memory at work.'],
    demo: [62, 64, 65], demoGap: 0.46,
    tryPrompt: 'Play back the three notes you heard.',
    targets: [62, 64, 65], mode: 'sequence',
    okMsg: 'A rising shape, held in your ear and played back true. Lovely listening.',
    hint: 'The three notes climbed gently, each a step higher than the last. Find the first, then step up twice.',
    reteach: 'Listen again \u2014 three notes stepping upward, one after another. The lit keys will guide your hand.',
    support: { highlight: [62, 64, 65], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'An echo with a turn', id: 'kl1-echo-shape',
    say: [
      { text: 'One more echo, with a little turn in it. The shape goes up, then comes back down to where it began.', pauseAfter: 600, tone: 'warm' },
      { text: 'Listen for that arch \u2014 out and back. Then play it from memory. Listening now.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['A four-note echo that arches up and returns. Hear the rise and the fall as one shape.', 'Reproducing a contour by ear \u2014 not single notes, but the whole gesture \u2014 is the heart of playing musically.'],
    demo: [60, 64, 62, 60], demoGap: 0.46,
    tryPrompt: 'Play back the four-note shape \u2014 up, and back home.',
    targets: [60, 64, 62, 60], mode: 'sequence',
    okMsg: 'You heard the whole arch and brought it home \u2014 that is musical listening, not just note-catching.',
    hint: 'It lifts up at the start, then settles back down to the note it began on. Hear the arch, then trace it.',
    reteach: 'Listen again \u2014 it rises to its highest note, then steps back down to home. The lit keys show the path.',
    support: { highlight: [60, 64, 62, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Sight-reading \u2014 a skip in the treble', id: 'kl1-sight-treble2',
    say: [
      { text: 'Another cold read \u2014 I will not play it. Look first: where does it start, and does it step or skip?', pauseAfter: 640, tone: 'warm' },
      { text: 'This one skips upward through the notes. Trace the shape with your eyes, then play it calmly.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A new phrase to read on your own, with no demonstration. Find the first note, then read the distance to each next note.', 'These notes skip rather than step \u2014 each one jumps over its neighbour. Read by distance, then play.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 } ], caption: 'Read it yourself \u2014 it skips upward. No listening first.' },
    tryPrompt: 'Read the phrase and play it \u2014 on your own, skipping upward.',
    targets: [60, 64, 67], mode: 'sequence',
    okMsg: 'Read cold and played true \u2014 and you felt the skips open wider than steps. Strong sight-reading.',
    hint: 'It begins low and leaps upward, skipping a note each time \u2014 wider jumps than a stepwise line.',
    reteach: 'Slowly \u2014 start on the bottom note, skip up to the middle, then skip up again to the top. Now the keys are lit to guide you.',
    support: { highlight: [60, 64, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Sight-reading \u2014 in the bass clef', id: 'kl1-sight-bass',
    say: [
      { text: 'Now read one in the bass clef, for the left hand \u2014 and again, I will not play it first.', pauseAfter: 640, tone: 'warm' },
      { text: 'Find the starting note low down, then follow the shape. Little finger ready on the low note.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A bass-clef phrase to sight-read with the left hand \u2014 no demonstration. Find the low starting note, then read the shape upward.', 'Reading both clefs cold is the habit that lets you open any piece of piano music on your own.'],
    show: { kind: 'staff', clef: 'bass', timeSig: false, notes: [ { midi: 48, value: 'quarter', finger: 5 }, { midi: 50, value: 'quarter', finger: 4 }, { midi: 52, value: 'quarter', finger: 3 } ], caption: 'Read it yourself, left hand \u2014 it steps upward from low C.' },
    tryPrompt: 'Read the bass-clef phrase and play it \u2014 on your own, left hand.',
    targets: [48, 50, 52], mode: 'sequence',
    okMsg: 'A bass-clef line, read cold with the left hand \u2014 both hands can now read music on their own.',
    hint: 'It starts on the low note and steps upward, one step at a time. Little finger begins.',
    reteach: 'Slowly \u2014 little finger on low C, then step up two notes. Now the keys are lit to show the way.',
    support: { highlight: [48, 50, 52], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Review \u2014 read the rhythm', id: 'kl1-review-rhythm',
    say: [
      { text: 'Let us gather everything together. First, rhythm \u2014 remember the note lengths? Read this short bar and give each note its full value.', pauseAfter: 620, tone: 'warm' },
      { text: 'Two crotchets, then a minim held for two beats. Listen, then play it in time.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['A quick rhythm recall: two crotchets, one beat each, then a minim held for two \u2014 four beats in the bar.', 'Reading note lengths is one of the foundations you built. Let the minim breathe its full length.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'half', finger: 1 } ], bars: [3], caption: 'Recall the lengths \u2014 crotchet, crotchet, minim.' },
    demo: [64, 62, 60], demoGap: 0.5,
    tryPrompt: 'Play the bar \u2014 two short notes, then a minim held for two beats.',
    targets: [64, 62, 60], mode: 'sequence',
    okMsg: 'Rhythm remembered \u2014 lengths read and held. One foundation firmly in place.',
    hint: 'Read the shape down to home, and hold the last note twice as long as the first two.',
    reteach: 'Gently \u2014 two single beats stepping down, then a long held note at the bottom. The lit keys will guide you.',
    support: { highlight: [64, 62, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Review \u2014 read the shape', id: 'kl1-review-shape',
    say: [
      { text: 'Now reading by shape. Here is a line that steps, then skips. Read the distances, not the names.', pauseAfter: 600, tone: 'warm' },
      { text: 'Three steps up, then a skip to the top. Hear it, then play it.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['A shape recall: three notes by step \u2014 each a 2nd \u2014 then a skip of a 3rd to the top.', 'Reading by shape, faster than spelling out names, is the reading habit at the heart of Key Level 1.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 } ], caption: 'Recall the shapes \u2014 steps up, then a skip to the top.' },
    demo: [60, 62, 64, 67], demoGap: 0.46,
    tryPrompt: 'Play the line \u2014 three steps up, then a skip to the top.',
    targets: [60, 62, 64, 67], mode: 'sequence',
    okMsg: 'Shape read true \u2014 steps and a skip, felt as distances. Reading is becoming second nature.',
    hint: 'Three notes move close together by step, then the last one leaps wider. Read the distances.',
    reteach: 'Slowly \u2014 step up three notes, then skip past one to reach the top. The lit keys will guide you.',
    support: { highlight: [60, 62, 64, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Review \u2014 the left hand', id: 'kl1-review-lh',
    say: [
      { text: 'Now the left hand. Read this short bass-clef line and play it down low, little finger leading.', pauseAfter: 600, tone: 'warm' },
      { text: 'Up by step, then home. Listen, then play with the left hand.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['A left-hand recall: a short bass-clef line, up by step and home. Little finger on the low note.', 'You taught your left hand to read the bass clef \u2014 this is that skill, gathered back up.'],
    show: { kind: 'staff', clef: 'bass', timeSig: false, notes: [ { midi: 48, value: 'quarter', finger: 5 }, { midi: 50, value: 'quarter', finger: 4 }, { midi: 52, value: 'quarter', finger: 3 }, { midi: 48, value: 'quarter', finger: 5 } ], caption: 'Recall the left hand \u2014 up by step, then home to low C.' },
    demo: [48, 50, 52, 48], demoGap: 0.5,
    tryPrompt: 'Play the bass-clef line with your left hand \u2014 up by step, then home.',
    targets: [48, 50, 52, 48], mode: 'sequence',
    okMsg: 'Left hand reading the bass clef and finding its way home \u2014 firmly remembered.',
    hint: 'Read the low shape \u2014 it climbs a little, then drops back to where it started.',
    reteach: 'Gently \u2014 little finger on low C, step up, then back to the low C. The lit keys will guide you.',
    support: { highlight: [48, 50, 52, 48], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Review \u2014 the home chord', id: 'kl1-review-interval',
    say: [
      { text: 'Now harmony. Play the home chord broken \u2014 C, E, G \u2014 each note a skip of a 3rd above the last.', pauseAfter: 600, tone: 'warm' },
      { text: 'These are the notes that belong to home in C major. Listen, then play them up.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['A harmony recall: the tonic triad, broken \u2014 C, then a 3rd up to E, then a 3rd up to G.', 'The home chord and the skip of a 3rd \u2014 two ideas from Key Level 1, brought together in one shape.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 } ], caption: 'Recall the home chord \u2014 C, E, G, skipping up by 3rds.' },
    demo: [60, 64, 67], demoGap: 0.48,
    tryPrompt: 'Play the home chord broken \u2014 C, E, G, skipping up.',
    targets: [60, 64, 67], mode: 'sequence',
    okMsg: 'The home chord, remembered \u2014 three notes skipping up by 3rds. Harmony is taking root.',
    hint: 'Each note skips a 3rd above the one before \u2014 jump, jump, upward through the chord.',
    reteach: 'Gently \u2014 thumb on C, skip to E, skip to G, climbing the home chord. The lit keys will guide your hand.',
    support: { highlight: [60, 64, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Review \u2014 by ear', id: 'kl1-review-echo',
    say: [
      { text: 'Now your ear. No notation \u2014 I play a short phrase, you echo it straight back.', pauseAfter: 600, tone: 'warm' },
      { text: 'Hold the shape, then find it. Listening now.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['An ear recall: hear a short phrase and play it back from memory, with nothing written to read.', 'Playing by ear was one of the deepest skills you met \u2014 here it is, gathered back up.'],
    demo: [67, 65, 64], demoGap: 0.46,
    tryPrompt: 'Play back the phrase you heard \u2014 by ear.',
    targets: [67, 65, 64], mode: 'sequence',
    okMsg: 'Caught by ear and played back \u2014 your listening has grown real and quick.',
    hint: 'The phrase fell gently \u2014 each note a step lower than the last. Find the top, then step down.',
    reteach: 'Listen again \u2014 three notes stepping downward from the top. The lit keys will show you where.',
    support: { highlight: [67, 65, 64], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Review \u2014 read it cold', id: 'kl1-review-sight',
    say: [
      { text: 'And last, sight-reading. A phrase you have not heard \u2014 I will not play it. Read it, and play it on your own.', pauseAfter: 640, tone: 'warm' },
      { text: 'Find the first note, read the shape, and play calmly. This is the habit that opens every piece.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A final cold read: no demonstration. Find the starting note, read the shape, and play it yourself.', 'Reading before playing \u2014 looking first, then sounding \u2014 is the habit you carry on into Key Level 2.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'half', finger: 1 } ], bars: [3], caption: 'Read it yourself \u2014 find the shape, then play. No listening first.' },
    tryPrompt: 'Read the phrase and play it \u2014 on your own, without hearing it first.',
    targets: [64, 62, 60], mode: 'sequence',
    okMsg: 'Read cold and played true \u2014 the reading habit is yours. A fine way to close Key Level 1.',
    hint: 'Find the first note up high, then follow the shape downward to a held note at the bottom.',
    reteach: 'Slowly \u2014 the line steps down from the top to a long note at home. Now the keys are lit to guide you.',
    support: { highlight: [64, 62, 60], replay: true },
  },
];
