// courseChapters.js
// Course chapter map — groups the linear steps into named chapters for the Course Map. Presentation only.
// Extracted verbatim from foundations.js (the rc2-127 monolith) by the rc2-136
// thin-engine split. Identity-preserving: the SAME step objects, in the SAME
// order, with the SAME ids and fields — only their physical file location moved,
// so the Course renders identically. Original KeyMaster material; no third-party, method-book, or competitor content.

export const COURSE_CHAPTERS = [
  { stage: 1, name: 'Orientation', ids: ['welcome', 'course-opening', 'meet-keyboard', 'low-high'] },
  { stage: 1, name: 'Your hands', ids: ['sit-approach', 'hand-shape', 'fingers-rh', 'fingers-lh', 'hands-mirror', 'thumb-play', 'finger3-play', 'press-control'],
    intro: 'Before patterns, set up the hands: posture, a relaxed curved shape, the finger numbers, and control.' },
  { stage: 1, name: 'Black keys', ids: ['black-keys-two', 'black-keys-three'],
    intro: 'The black keys come in groups of two and three \u2014 your signposts.' },
  { stage: 1, name: 'White keys', ids: ['find-c', 'find-d', 'find-e', 'find-f', 'find-g', 'find-a', 'middle-c', 'b-below'],
    intro: 'Now we name the white keys, using the black-key groups to find them.' },
  { stage: 1, name: 'Movement', ids: ['direction', 'step-skip'],
    intro: 'Music moves \u2014 up and down, by steps and by skips.' },
  { stage: 1, name: 'Tones & semitones', ids: ['semitone', 'tone'],
    intro: 'The two sizes of step \u2014 the semitone and the tone \u2014 that scales are built from.' },
  { stage: 1, name: 'Scales', ids: ['scale-why', 'first-scale', 'c-scale-five', 'c-scale-down'],
    intro: 'What a scale is and why it matters \u2014 ordered steps you can climb and descend.' },
  { stage: 1, name: 'B major', ids: ['first-b-scale', 'b-major-why', 'bridge-scales'],
    intro: 'A first taste of the B-major pathway, and why it fits the hand.' },
  { stage: 1, name: 'Harmony', ids: ['first-chord', 'chord-g', 'bridge-chords'],
    intro: 'Notes sounded together make chords \u2014 the colour of music.' },
  { stage: 1, name: 'Reading the staff', ids: ['staff-what', 'staff-spaces', 'treble-clef', 'bass-clef', 'grand-staff', 'grand-staff-map', 'ledger-line', 'staff-to-key'],
    intro: 'The staff is the map musicians read \u2014 lines, spaces, clefs, the grand staff, and how it connects to the keys.' },
  { stage: 1, name: 'Naming the notes', ids: ['note-alphabet', 'treble-g-landmark', 'treble-spaces-face', 'treble-lines-egbdf', 'treble-recall-spaces', 'treble-recall-lines'],
    intro: 'Every line and space has a letter name \u2014 the treble G, the spaces that spell FACE, and the lines E G B D F.' },
  { stage: 1, name: 'Reading', ids: ['read-play-e', 'read-play-g', 'first-reading', 'bridge-sightreading'],
    intro: 'Reading music means knowing a note, then playing it \u2014 now linked to the staff.' },
  { stage: 1, name: 'Reading by shape', ids: ['shape-reading-intro', 'shape-step', 'shape-skip', 'shape-repeat', 'first-shape-pattern'],
    intro: 'Fluent readers see how notes move \u2014 steps, skips, and repeats \u2014 and read small groups as shapes, not one note at a time.' },
  { stage: 1, name: 'Rhythm', ids: ['first-pulse', 'pulse-eight'],
    intro: 'Music sits on a steady pulse \u2014 an even beat underneath the notes.' },
  { stage: 1, name: 'Checkpoint', ids: ['review-c', 'review-scale', 'review-chord'],
    intro: 'A calm checkpoint \u2014 just the things you already know.' },
  { stage: 1, name: 'Stage 1 complete', ids: ['stage1-complete'] },
  { stage: 2, name: 'Making music', ids: ['stage2-welcome'],
    intro: 'Stage 2 \u2014 the foundations become music.' },
  { stage: 2, name: 'The B-major pathway', ids: ['bmaj-shape', 'bmaj-rh', 'bmaj-lh'],
    intro: 'The KeyMaster hand-shape pathway \u2014 fingering, hand by hand, on the keys that fit.' },
  { stage: 2, name: 'Phrases', ids: ['phrase-up', 'phrase-down', 'read-pattern'],
    intro: 'Short phrases you can play \u2014 up, down, and a pattern to name and play in order.' },
  { stage: 2, name: 'Rhythm in music', ids: ['play-on-pulse', 'pattern-pulse'],
    intro: 'Notes over a steady pulse \u2014 the feel of music in time.' },
  { stage: 2, name: 'Scale & pattern shapes', ids: ['scale-shape-up', 'pattern-fingered'],
    intro: 'A scale and a pattern as shapes \u2014 with a finger ready for each note.' },
  { stage: 2, name: 'Harmony in music', ids: ['arpeggio-c'],
    intro: 'A chord spread out in time becomes an arpeggio.' },
  { stage: 2, name: 'Patterns & phrases', ids: ['motif-echo', 'first-phrase'],
    intro: 'Recognise a small pattern, then play your first melody.' },
  { stage: 2, name: 'Making music \u2014 studies', ids: ['play-echo', 'study-steps', 'study-qa'],
    intro: 'Echo a short idea, then play two original studies \u2014 the first real feel of making music.' },
  { stage: 2, name: 'Making music \u2014 answers & a tune', ids: ['call-response', 'chord-warm', 'study-tune'],
    intro: 'Answer a musical call, play a warm chord, and shape a little tune of your own.' },
  { stage: 2, name: 'Becoming a musician', ids: ['practise-slow', 'listen-tone'],
    intro: 'The habits behind the notes \u2014 practising slowly, and listening.' },
  { stage: 2, name: 'Bring it back \u2014 a gentle review', ids: ['recall-register', 'recall-middlec', 'recall-echo'],
    intro: 'A calm recall \u2014 find low and high, find Middle C, and echo a short pattern, all from memory.' },
  { stage: 2, name: 'Stage 2 review', ids: ['review-phrase', 'stage2-onward'],
    intro: 'A calm review, and the road into Stage 3.' },

  { stage: 3, name: 'Reading & playing', ids: ['s3-welcome'],
    intro: 'Stage 3 \u2014 reading from the staff and playing as one motion.' },
  { stage: 3, name: 'Reading the staff', ids: ['s3-landmark-g', 's3-read-up', 's3-direction', 's3-read-fingered'],
    intro: 'Landmarks, note movement, and a finger ready for each note.' },
  { stage: 3, name: 'Right-hand patterns', ids: ['s3-rh-pattern', 's3-rh-down'],
    intro: 'Short five-finger lines, played from the staff, the hand staying home.' },
  { stage: 3, name: 'Reading with pulse', ids: ['s3-read-pulse'],
    intro: 'Reading and playing carried on a steady count.' },
  { stage: 3, name: 'B major, reading', ids: ['s3-bmaj-staff'],
    intro: 'The B-major hand shape, now read from the staff.' },
  { stage: 3, name: 'Phrase & review', ids: ['s3-phrase', 's3-review', 's3-onward'],
    intro: 'Shaping a line, a checkpoint, and the road into Stage 4.' },

  { stage: 4, name: 'Two hands', ids: ['s4-welcome'],
    intro: 'Stage 4 \u2014 the left hand and the bass clef join in.' },
  { stage: 4, name: 'The bass clef', ids: ['s4-bass-clef', 's4-lh-fingers', 's4-lh-note', 's4-lh-pattern'],
    intro: 'Lower notes, left-hand fingers, and reading the bass.' },
  { stage: 4, name: 'The grand staff', ids: ['s4-grand', 's4-anchor'],
    intro: 'Both clefs together \u2014 a left-hand anchor under a right-hand melody.' },
  { stage: 4, name: 'Harmony & scales', ids: ['s4-chord-arp', 's4-scale-rh', 's4-scale-lh'],
    intro: 'Chord and arpeggio, and the five-finger scale shape in both hands.' },
  { stage: 4, name: 'Practising well', ids: ['s4-practise'],
    intro: 'Hands separately first, then together \u2014 the heart of good practice.' },
  { stage: 4, name: 'A piece & review', ids: ['s4-piece', 's4-review', 's4-onward'],
    intro: 'A first short piece, a checkpoint, and where you are now.' },

  // ===== KeyMaster Course (the proper graded-style journey, after Foundation) =====
  // course:'keymaster' switches the in-Course banner to "Key Level N" and gives the
  // Course Map its own "KeyMaster Course" section. Foundation chapters above carry no
  // `course` field and default to 'foundation', so they are entirely unchanged.
  { course: 'keymaster', stage: 1, name: 'Reading Shapes into Music', ids: ['kl1-welcome', 'kl1-shapes-recap', 'kl1-read-repeats', 'kl1-read-stepsup', 'kl1-read-stepsdown', 'kl1-read-skips', 'kl1-first-phrase', 'kl1-phrase-echo', 'kl1-read-cold'],
    intro: 'The KeyMaster Course begins. In Key Level 1 \u2014 First Musicianship \u2014 the shapes you learned in the Foundation become music: read, heard, and played, as reading, rhythm, and your hands grow together.' },
  { course: 'keymaster', stage: 1, name: 'Pulse and Counting', ids: ['kl1-pulse-feel', 'kl1-pulse-play', 'kl1-pulse-eight', 'kl1-pulse-rushing'],
    intro: 'Music rests on a steady pulse. Feel the beat first \u2014 a calm, unhurried heartbeat \u2014 then place the notes onto it. Counting before rushing is how playing in time begins.' },
  { course: 'keymaster', stage: 1, name: 'Notes in Time', ids: ['kl1-notes-values', 'kl1-notes-read', 'kl1-notes-held', 'kl1-notes-twobar'],
    intro: 'A note\u2019s shape tells you how long to hold it \u2014 the semibreve, the minim, the crotchet. Read the lengths as well as the pitches, and rhythm begins to live on the page.' },
  { course: 'keymaster', stage: 1, name: 'First Right-Hand Piece', ids: ['kl1-piece-listen', 'kl1-piece-play'],
    intro: 'Your first real piece from manuscript \u2014 Morning Steps. Proper notation now: a time signature, barlines, and notes of different lengths. Listen first, read the shape, then play it through.' },
  { course: 'keymaster', stage: 1, name: 'Rests \u2014 the Spaces in Music', ids: ['kl1-rests-intro', 'kl1-rests-play', 'kl1-rests-read2'],
    intro: 'Silence is written too. Every note length has a matching rest \u2014 and you count a rest as carefully as a note, the pulse running on underneath.' },
  { course: 'keymaster', stage: 1, name: 'Blue Window \u2014 a Second Piece', ids: ['kl1-blue-listen', 'kl1-blue-play'],
    intro: 'A second original piece, Blue Window \u2014 a calm falling line that turns and comes home. More manuscript, more music in your hands.' },
  { course: 'keymaster', stage: 1, name: 'More Right-Hand Pieces', ids: ['kl1-light-listen', 'kl1-light-play', 'kl1-home-listen', 'kl1-home-play'],
    intro: 'Two more original pieces \u2014 First Light, built on repeated notes, and Walking Home, a phrase that wanders and comes home. More reading, more music in your hands.' },
  { course: 'keymaster', stage: 1, name: 'The Left Hand', ids: ['kl1-lh-intro', 'kl1-lh-play', 'kl1-lh-pattern', 'kl1-lh-study'],
    intro: 'The left hand joins, reading the bass clef \u2014 the lower notes below Middle C. Both hands can read music now.' },
  { course: 'keymaster', stage: 1, name: 'Two Hands, Carefully', ids: ['kl1-hands-intro', 'kl1-hands-play', 'kl1-hands-rhhold', 'kl1-hands-turns'],
    intro: 'The grand staff joins both clefs into one. We begin two hands gently \u2014 a held bass note under a small right-hand melody.' },
  { course: 'keymaster', stage: 1, name: 'Fingering and Touch', ids: ['kl1-finger-why', 'kl1-finger-play', 'kl1-finger-detached', 'kl1-finger-phrase'],
    intro: 'Why the finger numbers matter \u2014 and a first smooth, connected legato touch that makes a line sing.' },
  { course: 'keymaster', stage: 1, name: 'Intervals and Musical Distance', ids: ['kl1-intervals-intro', 'kl1-intervals-play', 'kl1-intervals-2nd', 'kl1-intervals-3rd', 'kl1-intervals-compare'],
    intro: 'The distance between notes, named by number: a 2nd is a step, a 3rd is a skip. Reading by distance is faster than naming every note.' },
  { course: 'keymaster', stage: 1, name: 'Five-Finger Patterns and First Scales', ids: ['kl1-fivefinger-why', 'kl1-fivefinger-play', 'kl1-fivefinger-even'],
    intro: 'The five-finger pattern \u2014 five notes, five fingers, the hand staying home. The shape that lives inside so much music.' },
  { course: 'keymaster', stage: 1, name: 'First Harmony', ids: ['kl1-harmony-tonic', 'kl1-harmony-triad', 'kl1-harmony-melody', 'kl1-harmony-broken2'],
    intro: 'The home note \u2014 the tonic \u2014 and the home chord built on it. Your first harmony, played as a broken chord so you hear every note.' },
  { course: 'keymaster', stage: 1, name: 'Listening and Echo', ids: ['kl1-echo-task', 'kl1-echo-two', 'kl1-echo-three', 'kl1-echo-shape'],
    intro: 'No notation \u2014 pure listening. Hear a short phrase and play it straight back by ear, the deepest musical skill of all.' },
  { course: 'keymaster', stage: 1, name: 'Sight-Reading Micro-Lessons', ids: ['kl1-sight-micro', 'kl1-sight-treble2', 'kl1-sight-bass'],
    intro: 'A phrase you have not heard, read cold and played on your own. Reading before playing \u2014 the habit that opens every piece.' },
  { course: 'keymaster', stage: 1, name: 'Key Level 1 Review', ids: ['kl1-review-rhythm', 'kl1-review-shape', 'kl1-review-lh', 'kl1-review-interval', 'kl1-review-echo', 'kl1-review-sight', 'kl1-review'],
    intro: 'A calm look back at how far you have come \u2014 and the road into Key Level 2, Real Repertoire.' },

  // ===== Key Level 2 — Real Repertoire (KL2A: Chapters 1\u20134) ==============
  { course: 'keymaster', stage: 2, name: 'The Road Ahead', ids: ['kl2-welcome', 'kl2-arc'],
    intro: 'Key Level 2 begins \u2014 Real Repertoire. A look at what is coming: three new pieces built from what you already know, and real historical music further down the road.' },
  { course: 'keymaster', stage: 2, name: 'The Waltz Pulse', ids: ['kl2-waltz-intro', 'kl2-waltz-count', 'kl2-dotted-minim', 'kl2-dotted-play', 'kl2-waltz-phrase'],
    intro: 'A new metre \u2014 three beats in a bar \u2014 and the dotted minim, a note that can fill a whole bar of three-time on its own.' },
  { course: 'keymaster', stage: 2, name: 'Slate & Homeward', ids: ['kl2-dynamics-name', 'kl2-slate-listen', 'kl2-slate-play', 'kl2-homeward-listen', 'kl2-homeward-play'],
    intro: 'Light and shade in the sound \u2014 p for quiet, f for strong. Two pieces, Slate and Homeward, each shaped by dynamics from quiet to strong and home again.' },
  { course: 'keymaster', stage: 2, name: 'Still Water', ids: ['kl2-still-listen', 'kl2-still-play-question', 'kl2-still-play-answer', 'kl2-still-perform'],
    intro: 'A calmer piece built from question and answer \u2014 the phrase-shape at the heart of almost all real music. The doorway into repertoire proper.' },
  { course: 'keymaster', stage: 2, name: 'The Quaver', ids: ['kl2-quaver-hear', 'kl2-quaver-see', 'kl2-quaver-count', 'kl2-quaver-descend'],
    intro: 'Notes faster than the beat \u2014 two to a beat, joined by a beam. Heard first, counted aloud, then played.' },
  { course: 'keymaster', stage: 2, name: 'First Light', ids: ['kl2-firstlight-listen', 'kl2-firstlight-a', 'kl2-firstlight-perform'],
    intro: 'The first piece that moves at two speeds \u2014 steady notes with quicker ones woven through, shaped by quiet and strong.' },
  { course: 'keymaster', stage: 2, name: 'Black Keys & F sharp', ids: ['kl2-blackkeys-see', 'kl2-fsharp-meet', 'kl2-fsharp-sign'],
    intro: 'The pattern of black keys, and the first one you will play from notation \u2014 F sharp, and the sign that raises it.' },
  { course: 'keymaster', stage: 2, name: 'G Major', ids: ['kl2-gmajor-home', 'kl2-gmajor-why', 'kl2-keysig-read', 'kl2-keysig-play'],
    intro: 'A new five-finger home on G \u2014 why the key needs its sharp, and how a key signature carries that instruction through a whole piece.' },
  { course: 'keymaster', stage: 2, name: 'Meadow Song', ids: ['kl2-meadow-listen', 'kl2-meadow-sharp', 'kl2-meadow-perform'],
    intro: 'G major, three-time, quavers and a black key \u2014 the first piece that asks for everything at once.' },
  { course: 'keymaster', stage: 2, name: 'By Ear', ids: ['kl2-by-ear'],
    intro: 'One phrase, played to you and not written down. The ear is a reading tool too.' },
  { course: 'keymaster', stage: 2, name: 'Key Level 2 Review', ids: ['kl2-review-read', 'kl2-review'],
    intro: 'A sight-reading check with no demonstration, and a look at how much reading ground this level has covered.' },
  // ===== Key Level 3 — Pattern Fluency ==================================
  { course: 'keymaster', stage: 3, name: 'Reading by Distance', ids: ['kl3-welcome', 'kl3-step-see', 'kl3-skip-see', 'kl3-mixed-play'],
    intro: 'Steps and skips recognised by their SHAPE on the page rather than counted \u2014 the first move from decoding to reading.' },
  { course: 'keymaster', stage: 3, name: 'Wider Steps', ids: ['kl3-wide-see', 'kl3-wide-play'],
    intro: 'Fourths and fifths, and the habit of naming a leap before the hand moves. The eye leads; the fingers follow.' },
  { course: 'keymaster', stage: 3, name: 'The Thumb Passes Under', ids: ['kl3-thumb-why', 'kl3-thumb-move', 'kl3-thumb-join'],
    intro: 'The single most important mechanism in piano technique \u2014 the movement that makes the keyboard wider than your hand.' },
  { course: 'keymaster', stage: 3, name: 'The C Major Scale', ids: ['kl3-scale-up', 'kl3-scale-down'],
    intro: 'A full octave in both directions, read and felt as one gesture rather than eight separate decisions.' },
  { course: 'keymaster', stage: 3, name: 'Patterns That Repeat', ids: ['kl3-sequence-see', 'kl3-sequence-play'],
    intro: 'The sequence \u2014 the same shape moved to a new pitch. Spot it, and you have half as much to read.' },
  { course: 'keymaster', stage: 3, name: 'Riverlight', ids: ['kl3-riverlight-listen', 'kl3-riverlight-a', 'kl3-riverlight-perform'],
    intro: 'The first piece written across two lines, as real sheet music is \u2014 and the reading skill of crossing the break without stopping.' },
  { course: 'keymaster', stage: 3, name: 'Reading Ahead', ids: ['kl3-scan-teach', 'kl3-scan-play'],
    intro: 'Ten seconds of scanning before a note is played \u2014 the habit that separates fluent readers from everyone else.' },
  { course: 'keymaster', stage: 3, name: 'By Ear', ids: ['kl3-by-ear'],
    intro: 'Steps and skips \u2014 heard this time, not seen. The same distances your eyes have been learning.' },
  { course: 'keymaster', stage: 3, name: 'Key Level 3 Review', ids: ['kl3-review-read', 'kl3-review'],
    intro: 'An undemonstrated sight-read across two systems in a sharp key, and a look at how much reading has changed.' },
  // ===== Key Level 4 — Musical Independence =============================
  { course: 'keymaster', stage: 4, name: 'Two Hands, One Music', ids: ['kl4-welcome', 'kl4-why-hard'],
    intro: 'The largest step in the course \u2014 and an honest explanation of why it feels hard, and what actually solves it.' },
  { course: 'keymaster', stage: 4, name: 'The Held Bass', ids: ['kl4-held-listen', 'kl4-held-play', 'kl4-held-change'],
    intro: 'Independence at its gentlest: one hand presses a note and simply holds it while the other moves above.' },
  { course: 'keymaster', stage: 4, name: 'Contrary Motion', ids: ['kl4-contrary-see', 'kl4-contrary-play'],
    intro: 'Hands moving in opposite directions \u2014 easier than it sounds, because mirrored movement is natural to the body.' },
  { course: 'keymaster', stage: 4, name: 'Different Rhythms', ids: ['kl4-rhythm-listen', 'kl4-rhythm-play'],
    intro: 'One hand twice as fast as the other, held together by a single pulse \u2014 and the trick of thinking in where they meet.' },
  { course: 'keymaster', stage: 4, name: 'By Ear', ids: ['kl4-by-ear'],
    intro: 'The Minuet\u2019s opening, met by ear before it is met on the page \u2014 recognition before execution, exactly.' },
  { course: 'keymaster', stage: 4, name: 'The Minuet \u2014 the melody', ids: ['kl4-minuet-story', 'kl4-minuet-rh-listen', 'kl4-minuet-rh-a', 'kl4-minuet-rh-b'],
    intro: 'Real repertoire: the Minuet in G by Christian Petzold \u2014 not Bach, and the story of how the world got that wrong.' },
  { course: 'keymaster', stage: 4, name: 'The Minuet \u2014 the left hand', ids: ['kl4-minuet-lh', 'kl4-minuet-lh-hard'],
    intro: 'A bass line that holds one note for five bars running \u2014 and the two bars that actually need practising.' },
  { course: 'keymaster', stage: 4, name: 'The Minuet \u2014 both hands', ids: ['kl4-minuet-both-see', 'kl4-minuet-both-a', 'kl4-minuet-perform'],
    intro: 'The whole thing on the grand staff, read for where the parts coincide, then performed.' },
  { course: 'keymaster', stage: 4, name: 'Mistake Recovery', ids: ['kl4-recovery-teach', 'kl4-recovery-play'],
    intro: 'Every pianist plays wrong notes. What separates a musician is keeping the pulse and rejoining \u2014 a skill worth rehearsing on purpose.' },
  { course: 'keymaster', stage: 4, name: 'Key Level 4 Review', ids: ['kl4-review-read', 'kl4-review'],
    intro: 'An undemonstrated two-hand sight-read, and a look at how much the hands have learned to do apart.' },
  // ===== Key Level 5 — Harmonic Fluency =================================
  { course: 'keymaster', stage: 5, name: 'Chords Are Built in Thirds', ids: ['kl5-welcome', 'kl5-triad-build', 'kl5-triad-play'],
    intro: 'What a triad actually is \u2014 a stack of thirds \u2014 and how to recognise that shape instantly on the page.' },
  { course: 'keymaster', stage: 5, name: 'Major and Minor', ids: ['kl5-minor-hear', 'kl5-minor-play', 'kl5-minor-real'],
    intro: 'One note, one semitone, and the entire emotional colour of the music changes \u2014 heard in Petzold\u2019s own minor minuet.' },
  { course: 'keymaster', stage: 5, name: 'The Three Chords', ids: ['kl5-three-see', 'kl5-three-play'],
    intro: 'I, IV and V \u2014 three chords that hold up a key, and the progression underneath an enormous amount of music.' },
  { course: 'keymaster', stage: 5, name: 'Cadences', ids: ['kl5-cadence-hear', 'kl5-cadence-play'],
    intro: 'How a phrase closes, or deliberately refuses to \u2014 the full stop and the comma of music.' },
  { course: 'keymaster', stage: 5, name: 'Inversions', ids: ['kl5-inversion-why', 'kl5-inversion-play'],
    intro: 'Why chords change shape: not theory for its own sake, but so that hands and voices can move smoothly.' },
  { course: 'keymaster', stage: 5, name: 'New Keys', ids: ['kl5-dmajor', 'kl5-fmajor'],
    intro: 'D major and F major \u2014 sharps one way, flats the other, and the chain of fifths that connects them all.' },
  { course: 'keymaster', stage: 5, name: 'Predicting Harmony', ids: ['kl5-predict-teach', 'kl5-predict-play'],
    intro: 'Hearing the next chord before you read it \u2014 the exercise this whole level was built to make possible.' },
  { course: 'keymaster', stage: 5, name: 'Harmony in Real Music', ids: ['kl5-real-analysis'],
    intro: 'A melody with its harmony written underneath and analysed \u2014 reading the structure before reading the tune.' },
  { course: 'keymaster', stage: 5, name: 'By Ear', ids: ['kl5-by-ear'],
    intro: 'A chord rather than a line. Three notes at once, heard and found.' },
  { course: 'keymaster', stage: 5, name: 'Key Level 5 Review', ids: ['kl5-review-play', 'kl5-review'],
    intro: 'Deduce a key from its signature and build its home chord unaided \u2014 then a look at how differently you now listen.' },
  // ===== Key Level 6 — Expressive Repertoire ============================
  { course: 'keymaster', stage: 6, name: 'Two Touches', ids: ['kl6-welcome', 'kl6-touch-hear', 'kl6-staccato-play'],
    intro: 'Legato and staccato \u2014 the two basic touches, heard before they are named, and the point where the question becomes HOW rather than which note.' },
  { course: 'keymaster', stage: 6, name: 'Slurs and Phrasing', ids: ['kl6-slur-see'],
    intro: 'The curved line that joins notes into a sentence, and shows where the music breathes.' },
  { course: 'keymaster', stage: 6, name: 'The Dynamic Range', ids: ['kl6-dynamics-range', 'kl6-dynamics-play'],
    intro: 'From pp to ff, and the more useful idea \u2014 growing and fading, with the sound following the shape of the line.' },
  { course: 'keymaster', stage: 6, name: 'Tempo and Rubato', ids: ['kl6-tempo-words', 'kl6-rit-play'],
    intro: 'The Italian words for speed and character, and how to broaden an ending so it arrives rather than merely stops.' },
  { course: 'keymaster', stage: 6, name: 'The Pedal', ids: ['kl6-pedal-teach', 'kl6-pedal-listen'],
    intro: 'What the sustaining pedal is actually for, the rule that prevents mud \u2014 and an honest admission that only your ears can judge it.' },
  { course: 'keymaster', stage: 6, name: 'Completing the Minuet', ids: ['kl6-minuet-repeat', 'kl6-minuet-new', 'kl6-minuet-lh-b', 'kl6-minuet-both-b'],
    intro: 'Petzold\u2019s second half \u2014 six bars of which you already know, and the two that finally close the piece.' },
  { course: 'keymaster', stage: 6, name: 'Interpretive Choice', ids: ['kl6-interpret-teach', 'kl6-interpret-play'],
    intro: 'One phrase, three defensible readings, and no right answer \u2014 the first time the decision is genuinely yours.' },
  { course: 'keymaster', stage: 6, name: 'By Ear', ids: ['kl6-by-ear'],
    intro: 'The bar where the Minuet stops repeating itself, found by ear.' },
  { course: 'keymaster', stage: 6, name: 'Key Level 6 Review', ids: ['kl6-review-read', 'kl6-review'],
    intro: 'An undemonstrated read carrying every expressive mark of the level, and a look at how much of the music is now your own.' },
  // ===== Key Level 7 — Advanced Musicianship ============================
  { course: 'keymaster', stage: 7, name: 'Reading for Structure', ids: ['kl7-welcome', 'kl7-form-binary'],
    intro: 'Reading form before notes \u2014 and the point at which the instruction deliberately thins out, because you no longer need leading.' },
  { course: 'keymaster', stage: 7, name: 'Compound Time', ids: ['kl7-compound-hear', 'kl7-compound-play'],
    intro: 'Six-eight \u2014 a beat that divides in three, and the rolling lilt that comes with it.' },
  { course: 'keymaster', stage: 7, name: 'Chromaticism', ids: ['kl7-chromatic-teach'],
    intro: 'Accidentals from outside the key, and the natural sign that cancels them \u2014 usually a signal that something is changing.' },
  { course: 'keymaster', stage: 7, name: 'Modulation', ids: ['kl7-modulation-teach', 'kl7-modulation-see', 'kl7-modulation-play'],
    intro: 'A piece changing key \u2014 seen on the page before it is heard, in Petzold\u2019s own second section.' },
  { course: 'keymaster', stage: 7, name: 'Ornaments', ids: ['kl7-ornament-teach', 'kl7-ornament-minuet'],
    intro: 'Trills, mordents and turns \u2014 and the Minuet\u2019s own ornaments finally restored, exactly as its composer wrote them.' },
  { course: 'keymaster', stage: 7, name: 'Reading Above Your Level', ids: ['kl7-score-reading'],
    intro: 'Following a score you cannot yet play \u2014 the habit that keeps understanding ahead of technique.' },
  { course: 'keymaster', stage: 7, name: 'Transposition', ids: ['kl7-transpose-teach', 'kl7-transpose-play'],
    intro: 'The same shape in a different key \u2014 the definitive test of whether a passage was understood or merely memorised.' },
  { course: 'keymaster', stage: 7, name: 'By Ear', ids: ['kl7-by-ear'],
    intro: 'The note that does not belong to the key \u2014 heard rather than read.' },
  { course: 'keymaster', stage: 7, name: 'Key Level 7 Review', ids: ['kl7-review-read', 'kl7-review'],
    intro: 'An unfamiliar passage in a new key and metre, with no demonstration, no fingering and no hints.' },
  // ===== Key Level 8 — Performance Mastery ==============================
  { course: 'keymaster', stage: 8, name: 'How to Practise', ids: ['kl8-welcome', 'kl8-diagnose', 'kl8-slow-practice'],
    intro: 'Diagnosing your own weak bar, and why slow practice is a different activity rather than a gentler one.' },
  { course: 'keymaster', stage: 8, name: 'Learning Unaided', ids: ['kl8-unaided', 'kl8-questions'],
    intro: 'A whole section shown once, with no breakdown, no fingering and no lit keys \u2014 and two questions left deliberately unanswered.' },
  { course: 'keymaster', stage: 8, name: 'Memorisation', ids: ['kl8-memory', 'kl8-memory-test'],
    intro: 'Structural memory rather than finger memory \u2014 knowledge that survives nerves and can find your place again.' },
  { course: 'keymaster', stage: 8, name: 'Performing', ids: ['kl8-performing', 'kl8-nerves'],
    intro: 'What listeners actually hear, and an honest account of nerves and what genuinely helps with them.' },
  { course: 'keymaster', stage: 8, name: 'Building a Programme', ids: ['kl8-programme'],
    intro: 'Choosing what to play and in what order \u2014 the last musicianly skill the course teaches.' },
  { course: 'keymaster', stage: 8, name: 'The Complete Minuet', ids: ['kl8-minuet-close', 'kl8-minuet-whole'],
    intro: 'The closing bars, and then all thirty-two \u2014 performed whole, unchecked and unmarked, for you to judge yourself.' },
  { course: 'keymaster', stage: 8, name: 'By Ear', ids: ['kl8-by-ear'],
    intro: 'The closing phrase, by ear, with no help of any kind.' },
  { course: 'keymaster', stage: 8, name: 'Where You Are Now', ids: ['kl8-next', 'kl8-review'],
    intro: 'What to learn after this, where to find it \u2014 and an honest account of what is now true that was not when you began.' },
];
