// courseChapters.js
// Course chapter map — groups the linear steps into named chapters for the Course Map. Presentation only.
// Extracted verbatim from foundations.js (the rc2-127 monolith) by the rc2-136
// thin-engine split. Identity-preserving: the SAME step objects, in the SAME
// order, with the SAME ids and fields — only their physical file location moved,
// so the Course renders identically. Original KeyMaster material; no third-party, method-book, or competitor content.

export const COURSE_CHAPTERS = [
  { stage: 1, name: 'Orientation', ids: ['welcome', 'meet-keyboard', 'low-high'] },
  { stage: 1, name: 'Your hands', ids: ['sit-approach', 'hand-shape', 'fingers-rh', 'fingers-lh', 'hands-mirror', 'thumb-play', 'finger3-play', 'press-control'],
    intro: 'Before patterns, set up the hands: posture, a relaxed curved shape, the finger numbers, and control.' },
  { stage: 1, name: 'Black keys', ids: ['black-keys-two', 'black-keys-three'],
    intro: 'The black keys come in groups of two and three \u2014 your signposts.' },
  { stage: 1, name: 'White keys', ids: ['find-c', 'find-d', 'find-e', 'find-f', 'find-g', 'find-a', 'middle-c', 'b-below'],
    intro: 'Now we name the white keys, using the black-key groups to find them.' },
  { stage: 1, name: 'Movement', ids: ['direction', 'step-skip'],
    intro: 'Music moves \u2014 up and down, by steps and by skips.' },
  { stage: 1, name: 'Tones & semitones', ids: ['semitone', 'tone'],
    intro: 'The two sizes of step \u2014 the semitone and the tone \u2014 that scales are built from.' },
  { stage: 1, name: 'Scales', ids: ['scale-why', 'first-scale', 'c-scale-five', 'c-scale-down'],
    intro: 'What a scale is and why it matters \u2014 ordered steps you can climb and descend.' },
  { stage: 1, name: 'B major', ids: ['first-b-scale', 'b-major-why', 'bridge-scales'],
    intro: 'A first taste of the B-major pathway, and why it fits the hand.' },
  { stage: 1, name: 'Harmony', ids: ['first-chord', 'chord-g', 'bridge-chords'],
    intro: 'Notes sounded together make chords \u2014 the colour of music.' },
  { stage: 1, name: 'Reading the staff', ids: ['staff-what', 'staff-spaces', 'treble-clef', 'bass-clef', 'grand-staff', 'grand-staff-map', 'ledger-line', 'staff-to-key'],
    intro: 'The staff is the map musicians read \u2014 lines, spaces, clefs, the grand staff, and how it connects to the keys.' },
  { stage: 1, name: 'Naming the notes', ids: ['note-alphabet', 'treble-g-landmark', 'treble-spaces-face', 'treble-lines-egbdf', 'treble-recall-spaces', 'treble-recall-lines'],
    intro: 'Every line and space has a letter name \u2014 the treble G, the spaces that spell FACE, and the lines E G B D F.' },
  { stage: 1, name: 'Reading', ids: ['read-play-e', 'read-play-g', 'first-reading', 'bridge-sightreading'],
    intro: 'Reading music means knowing a note, then playing it \u2014 now linked to the staff.' },
  { stage: 1, name: 'Reading by shape', ids: ['shape-reading-intro', 'shape-step', 'shape-skip', 'shape-repeat', 'first-shape-pattern'],
    intro: 'Fluent readers see how notes move \u2014 steps, skips, and repeats \u2014 and read small groups as shapes, not one note at a time.' },
  { stage: 1, name: 'Rhythm', ids: ['first-pulse', 'pulse-eight'],
    intro: 'Music sits on a steady pulse \u2014 an even beat underneath the notes.' },
  { stage: 1, name: 'Checkpoint', ids: ['review-c', 'review-scale', 'review-chord'],
    intro: 'A calm checkpoint \u2014 just the things you already know.' },
  { stage: 1, name: 'Stage 1 complete', ids: ['stage1-complete'] },
  { stage: 2, name: 'Making music', ids: ['stage2-welcome'],
    intro: 'Stage 2 \u2014 the foundations become music.' },
  { stage: 2, name: 'The B-major pathway', ids: ['bmaj-shape', 'bmaj-rh', 'bmaj-lh'],
    intro: 'The KeyMaster hand-shape pathway \u2014 fingering, hand by hand, on the keys that fit.' },
  { stage: 2, name: 'Phrases', ids: ['phrase-up', 'phrase-down', 'read-pattern'],
    intro: 'Short phrases you can play \u2014 up, down, and a pattern to name and play in order.' },
  { stage: 2, name: 'Rhythm in music', ids: ['play-on-pulse', 'pattern-pulse'],
    intro: 'Notes over a steady pulse \u2014 the feel of music in time.' },
  { stage: 2, name: 'Scale & pattern shapes', ids: ['scale-shape-up', 'pattern-fingered'],
    intro: 'A scale and a pattern as shapes \u2014 with a finger ready for each note.' },
  { stage: 2, name: 'Harmony in music', ids: ['arpeggio-c'],
    intro: 'A chord spread out in time becomes an arpeggio.' },
  { stage: 2, name: 'Patterns & phrases', ids: ['motif-echo', 'first-phrase'],
    intro: 'Recognise a small pattern, then play your first melody.' },
  { stage: 2, name: 'Making music \u2014 studies', ids: ['play-echo', 'study-steps', 'study-qa'],
    intro: 'Echo a short idea, then play two original studies \u2014 the first real feel of making music.' },
  { stage: 2, name: 'Making music \u2014 answers & a tune', ids: ['call-response', 'chord-warm', 'study-tune'],
    intro: 'Answer a musical call, play a warm chord, and shape a little tune of your own.' },
  { stage: 2, name: 'Becoming a musician', ids: ['practise-slow', 'listen-tone'],
    intro: 'The habits behind the notes \u2014 practising slowly, and listening.' },
  { stage: 2, name: 'Bring it back \u2014 a gentle review', ids: ['recall-register', 'recall-middlec', 'recall-echo'],
    intro: 'A calm recall \u2014 find low and high, find Middle C, and echo a short pattern, all from memory.' },
  { stage: 2, name: 'Stage 2 review', ids: ['review-phrase', 'stage2-onward'],
    intro: 'A calm review, and the road into Stage 3.' },

  { stage: 3, name: 'Reading & playing', ids: ['s3-welcome'],
    intro: 'Stage 3 \u2014 reading from the staff and playing as one motion.' },
  { stage: 3, name: 'Reading the staff', ids: ['s3-landmark-g', 's3-read-up', 's3-direction', 's3-read-fingered'],
    intro: 'Landmarks, note movement, and a finger ready for each note.' },
  { stage: 3, name: 'Right-hand patterns', ids: ['s3-rh-pattern', 's3-rh-down'],
    intro: 'Short five-finger lines, played from the staff, the hand staying home.' },
  { stage: 3, name: 'Reading with pulse', ids: ['s3-read-pulse'],
    intro: 'Reading and playing carried on a steady count.' },
  { stage: 3, name: 'B major, reading', ids: ['s3-bmaj-staff'],
    intro: 'The B-major hand shape, now read from the staff.' },
  { stage: 3, name: 'Phrase & review', ids: ['s3-phrase', 's3-review', 's3-onward'],
    intro: 'Shaping a line, a checkpoint, and the road into Stage 4.' },

  { stage: 4, name: 'Two hands', ids: ['s4-welcome'],
    intro: 'Stage 4 \u2014 the left hand and the bass clef join in.' },
  { stage: 4, name: 'The bass clef', ids: ['s4-bass-clef', 's4-lh-fingers', 's4-lh-note', 's4-lh-pattern'],
    intro: 'Lower notes, left-hand fingers, and reading the bass.' },
  { stage: 4, name: 'The grand staff', ids: ['s4-grand', 's4-anchor'],
    intro: 'Both clefs together \u2014 a left-hand anchor under a right-hand melody.' },
  { stage: 4, name: 'Harmony & scales', ids: ['s4-chord-arp', 's4-scale-rh', 's4-scale-lh'],
    intro: 'Chord and arpeggio, and the five-finger scale shape in both hands.' },
  { stage: 4, name: 'Practising well', ids: ['s4-practise'],
    intro: 'Hands separately first, then together \u2014 the heart of good practice.' },
  { stage: 4, name: 'A piece & review', ids: ['s4-piece', 's4-review', 's4-onward'],
    intro: 'A first short piece, a checkpoint, and where you are now.' },
];
