// coursePianoSampler.js
// =============================================================================
// KeyMaster PRO — Course-only PREMIUM piano (sampled). PROOF / INVESTIGATION.
//
// A tiny, dependency-free Web Audio sampler. It plays short piano samples and
// pitch-shifts between them to cover the Course range, giving a real-grand sound
// in place of the provisional synth tone. It is built to be a *drop-in* for the
// `courseVoice` hook foundations already references (noteOn / noteOff / cancelAll),
// matching the PianoSynth (pianoVoice) interface exactly.
//
// HARD SAFETY RULES honoured by this module:
//   • NO Tone.js, NO external library, NO remote/CDN fetch — samples are loaded
//     from the SAME ORIGIN (the repo), so there is no third-party runtime call.
//   • If samples are missing or any load fails, isReady() stays FALSE and every
//     noteOn() returns false — the caller then uses the existing, always-ready
//     pianoVoice. No silence, no delayed start, no hard dependency on samples.
//   • It NEVER touches synth.js, Scales audio, the masterclasses, or pianoVoice.js
//     (this is a separate module; pianoVoice remains the protected fallback).
//   • Course-only by intent: the integration layer only selects this voice when
//     data-view="learn"; this module itself plays nothing until asked to.
//
// Provenance/attribution lives in NOTICE and in assets/piano/salamander-lite/
// manifest.json, both generated by the build-salamander-lite GitHub Action. This
// module ships NO audio of its own; the Action writes the CC-BY Salamander
// samples (Yamaha C5, Alexander Holm) under assets/piano/salamander-lite/.
// =============================================================================

// Zone map for the first "lite" proof: Salamander notes (Yamaha C5 source,
// CC BY 3.0) every TRITONE across the Course range C3..C6. Minimal file count
// for a fast proof (max pitch-shift ±3 semitones). For higher fidelity, use the
// minor-third set (C, D#, F#, A per octave) — see SALAMANDER_MINOR_THIRD below;
// the sampler works with whatever zones actually decode.
export const SALAMANDER_LITE_ZONES = [
  { note: 'C3',  midi: 48, file: 'C3.mp3'  },
  { note: 'Fs3', midi: 54, file: 'Fs3.mp3' },
  { note: 'C4',  midi: 60, file: 'C4.mp3'  },
  { note: 'Fs4', midi: 66, file: 'Fs4.mp3' },
  { note: 'C5',  midi: 72, file: 'C5.mp3'  },
  { note: 'Fs5', midi: 78, file: 'Fs5.mp3' },
  { note: 'C6',  midi: 84, file: 'C6.mp3'  },
];

// Recommended quality set (matches Holm's native minor-third sampling → max
// shift ±1.5 semitones). 13 files; still well under ~0.5 MB as MP3.
export const SALAMANDER_MINOR_THIRD = [
  ['C3', 48], ['Ds3', 51], ['Fs3', 54], ['A3', 57],
  ['C4', 60], ['Ds4', 63], ['Fs4', 66], ['A4', 69],
  ['C5', 72], ['Ds5', 75], ['Fs5', 78], ['A5', 81],
  ['C6', 84],
].map(([note, midi]) => ({ note, midi, file: `${note}.mp3` }));

// CANONICAL lite pack — 18 notes, every minor third A1..C6. This is what the
// build-salamander-lite GitHub Action generates and what manifest.json lists;
// it is the in-code DEFAULT used when no manifest is present yet (so the sampler
// still works the moment the files exist, even before a manifest is fetched).
// Max pitch-shift ±1.5 semitones across the Course keybed.
export const SALAMANDER_LITE_18 = [
  ['A1', 33], ['C2', 36], ['Ds2', 39], ['Fs2', 42], ['A2', 45],
  ['C3', 48], ['Ds3', 51], ['Fs3', 54], ['A3', 57],
  ['C4', 60], ['Ds4', 63], ['Fs4', 66], ['A4', 69],
  ['C5', 72], ['Ds5', 75], ['Fs5', 78], ['A5', 81], ['C6', 84],
].map(([note, midi]) => ({ note, midi, file: `${note}.mp3` }));

export function createCoursePiano(opts = {}) {
  const basePath = (opts.basePath || 'assets/piano/salamander-lite').replace(/\/$/, '');
  // Explicit zones win; otherwise init() resolves them from manifest.json, then
  // falls back to the in-code 18-note default. (Manifest-driven, never fragile.)
  const explicitZones = Array.isArray(opts.zones) && opts.zones.length ? opts.zones : null;
  const masterVolume = opts.volume ?? 0.85;
  const attack = opts.attack ?? 0.006;   // s — soft attack ramp, never a click
  const release = opts.release ?? 0.7;   // s — longer, more natural ring-out (Pass 1: body & air)
  const maxPolyphony = opts.maxPolyphony ?? 24;

  let ctx = null;
  let master = null;
  let ready = false;
  let status = 'idle';         // idle | loading | ready | missing | error (drives the in-app status line)
  let manifestFound = false;   // did manifest.json load? (tells "no files" apart from "no manifest")
  const buffers = new Map();   // midi -> AudioBuffer (only zones that decoded)
  let sampledMidis = [];       // sorted midis we actually have
  const active = [];           // { midi, src, gain, releasing }

  function _nearest(midi) {
    if (!sampledMidis.length) return null;
    let best = sampledMidis[0], bestD = Math.abs(midi - best);
    for (const m of sampledMidis) {
      const d = Math.abs(midi - m);
      if (d < bestD) { bestD = d; best = m; }
    }
    return best;
  }
  // Equal temperament: each semitone is a frequency ratio of 2^(1/12).
  function _rate(targetMidi, sampleMidi) { return Math.pow(2, (targetMidi - sampleMidi) / 12); }

  // Pass 1 "body & air": a small synthesised room impulse so the reverb needs NO
  // extra audio files. Decaying, gently low-passed noise — darkened so it reads
  // as room body rather than hiss.
  function _makeRoomImpulse(audioCtx, seconds, decay) {
    const rate = (audioCtx && audioCtx.sampleRate) ? audioCtx.sampleRate : 44100;
    const len = Math.max(1, Math.floor(seconds * rate));
    const buf = audioCtx.createBuffer(2, len, rate);
    for (let ch = 0; ch < 2; ch++) {
      const d = buf.getChannelData(ch);
      let lp = 0;
      for (let i = 0; i < len; i++) {
        const white = Math.random() * 2 - 1;
        lp = 0.6 * lp + 0.4 * white;            // gentle low-pass → darker tail
        d[i] = lp * Math.pow(1 - i / len, decay);
      }
    }
    return buf;
  }

  // Load samples. Returns a promise resolving to whether the sampler is usable.
  // A missing/failed file simply drops that one zone; one good zone = usable.
  async function init(audioContext, initOpts = {}) {
    ctx = audioContext || null;
    if (!ctx) { ready = false; status = 'idle'; return false; }
    status = 'loading';
    master = ctx.createGain();
    master.gain.value = masterVolume;
    // Pass 1: gentle high-shelf warmth + a subtle generated room, on the Course
    // voice ONLY (the synth fallback and practice rooms are unaffected). Wrapped
    // so any node failure falls back to a direct dry connection — never silence.
    const _dest = initOpts.destination || ctx.destination;
    try {
      const warmth = ctx.createBiquadFilter();
      warmth.type = 'highshelf';
      warmth.frequency.value = (opts.warmthHz ?? 6000);
      warmth.gain.value = (opts.warmthDb ?? -2.5);     // soften MP3 / close-mic edge
      master.connect(warmth);
      warmth.connect(_dest);                            // dry path (warmed)
      try {
        const conv = ctx.createConvolver();
        conv.buffer = _makeRoomImpulse(ctx, (opts.reverbSeconds ?? 1.8), (opts.reverbDecay ?? 2.6));
        const wet = ctx.createGain();
        wet.gain.value = (opts.reverbWet ?? 0.15);      // subtle room, ~15% wet
        warmth.connect(conv);
        conv.connect(wet);
        wet.connect(_dest);                             // parallel wet (warmed + room)
      } catch (_) { /* reverb unavailable → dry (warmed) only */ }
    } catch (_) {
      try { master.connect(_dest); } catch (_2) { /* last resort: bare connect */ }
    }

    if (initOpts.buffers instanceof Map && initOpts.buffers.size) {
      // Test/embedding seam: decoded buffers supplied directly (no fetch).
      for (const [m, buf] of initOpts.buffers) buffers.set(m, buf);
    } else {
      // Resolve the zone list: explicit opts.zones → manifest.json → in-code
      // default. A missing/invalid manifest silently uses the default set, so
      // the sampler activates as soon as the audio files exist in the repo.
      let resolvedZones = explicitZones;
      let sampleVersion = '';   // cache-busting tag from manifest (rebuilt packs bypass stale caches)
      if (!resolvedZones) {
        try {
          const mres = await fetch(`${basePath}/manifest.json`);
          if (mres && mres.ok) {
            manifestFound = true;
            const mdata = await mres.json();
            if (mdata && mdata.version) sampleVersion = String(mdata.version);
            if (mdata && Array.isArray(mdata.zones) && mdata.zones.length) resolvedZones = mdata.zones;
          }
        } catch (_) { /* no manifest yet → use the in-code default below */ }
      }
      if (!resolvedZones) resolvedZones = SALAMANDER_LITE_18;
      await Promise.all(resolvedZones.map(async (z) => {
        try {
          const res = await fetch(`${basePath}/${z.file}${sampleVersion ? ('?v=' + encodeURIComponent(sampleVersion)) : ''}`);
          if (!res || !res.ok) return;
          const arr = await res.arrayBuffer();
          const buf = await new Promise((resolve, reject) => {
            // callback form is the widest-compatible; promise form also works
            const p = ctx.decodeAudioData(arr, resolve, reject);
            if (p && typeof p.then === 'function') p.then(resolve, reject);
          });
          if (buf) buffers.set(z.midi, buf);
        } catch (_) { /* drop this zone, keep the rest */ }
      }));
    }
    sampledMidis = [...buffers.keys()].sort((a, b) => a - b);
    ready = sampledMidis.length > 0;
    status = ready ? 'ready' : 'missing';
    return ready;
  }

  function isReady() { return ready; }

  function noteOn(midi, velocity = 100, when) {
    if (!ready || !ctx) return false;                 // -> caller uses pianoVoice
    const sampleMidi = _nearest(midi);
    const buf = sampleMidi == null ? null : buffers.get(sampleMidi);
    if (!buf) return false;
    const t = (typeof when === 'number') ? when : ctx.currentTime;
    while (active.length >= maxPolyphony) { const v = active.shift(); _hardStop(v, ctx.currentTime); }
    try {
      const src = ctx.createBufferSource();
      src.buffer = buf;
      src.playbackRate.value = _rate(midi, sampleMidi);
      const g = ctx.createGain();
      const vel = Math.max(1, Math.min(127, velocity)) / 127;
      const peak = Math.max(0.0008, vel * vel);       // square-ish velocity curve
      g.gain.setValueAtTime(0.0001, t);
      g.gain.linearRampToValueAtTime(peak, t + attack);
      src.connect(g); g.connect(master);
      const voice = { midi, src, gain: g, releasing: false };
      src.onended = () => { const i = active.indexOf(voice); if (i !== -1) active.splice(i, 1); };
      src.start(t);
      active.push(voice);
      return true;
    } catch (_) { return false; }
  }

  function _release(voice, when) {
    if (!voice || voice.releasing || !ctx) return;
    voice.releasing = true;
    const t = (typeof when === 'number') ? when : ctx.currentTime;
    try {
      const g = voice.gain.gain;
      g.cancelScheduledValues(t);
      g.setValueAtTime(Math.max(g.value, 0.0001), t);
      g.linearRampToValueAtTime(0.0001, t + release);  // ramp down — no tail click
      voice.src.stop(t + release + 0.02);
    } catch (_) { /* no-op */ }
  }
  function _hardStop(voice, when) {
    if (!voice || !ctx) return;
    const t = (typeof when === 'number') ? when : ctx.currentTime;
    try {
      const g = voice.gain.gain;
      g.cancelScheduledValues(t);
      g.setValueAtTime(Math.max(g.value, 0.0001), t);
      g.linearRampToValueAtTime(0.0001, t + 0.03);     // 30 ms fade — avoids a pop
      voice.src.stop(t + 0.05);
    } catch (_) { /* no-op */ }
    const i = active.indexOf(voice); if (i !== -1) active.splice(i, 1);
  }

  function noteOff(midi, when) {
    if (!ready) return;
    for (let i = active.length - 1; i >= 0; i--) {
      if (active[i].midi === midi && !active[i].releasing) { _release(active[i], when); return; }
    }
  }
  function cancelAll(when) {
    const t = (typeof when === 'number') ? when : (ctx ? ctx.currentTime : 0);
    for (const v of [...active]) _hardStop(v, t);
  }

  return {
    init,
    isReady,
    noteOn,
    noteOff,
    cancelAll,
    allNotesOff: cancelAll,   // PianoSynth parity
    panic: cancelAll,
    setVolume: (v) => { if (master && ctx) master.gain.setTargetAtTime(Math.max(0, Math.min(1, v)), ctx.currentTime, 0.02); },
    // In-app status for the side-menu indicator (so the voice state is visible,
    // not guessed by ear): code is idle|loading|ready|missing|error.
    getStatus: () => ({ code: status, loaded: sampledMidis.length, manifest: manifestFound }),
    // introspection for tests / the #voice-test diagnostic:
    _state: () => ({ ready, sampled: [...sampledMidis], active: active.length, basePath }),
    _nearest,
    _rate,
  };
}
