// courseFoundation.js
// Foundation Course steps (the keyboard-geography stage).
// Extracted verbatim from foundations.js (the rc2-127 monolith) by the rc2-136
// thin-engine split. Identity-preserving: the SAME step objects, in the SAME
// order, with the SAME ids and fields — only their physical file location moved,
// so the Course renders identically. Original KeyMaster material; no third-party, method-book, or competitor content.

import { B_FRAGMENT, B_FRAGMENT_NAMES } from './courseData.js';

export const FOUNDATION_STEPS = [
  {
    eyebrow: 'Welcome', title: 'Welcome to the Course', id: 'welcome',
    media: { kind: 'video', topic: 'posture', caption: 'Sitting well at the piano \u2014 guided demonstration' },
    say: [
      { text: 'Welcome to the KeyMaster PRO Course.', pauseAfter: 560, tone: 'warm' },
      { text: 'I\u2019m your tutor. We\u2019ll go step by step, and you\u2019ll always know what to do next.', pauseAfter: 620 },
      { text: 'Sit comfortably \u2014 both feet down, shoulders easy, hands relaxed over the keys. Natural, supported, never forced.', pauseAfter: 640, tone: 'warm' },
      { text: 'When you\u2019re ready, we\u2019ll begin by orienting the keyboard.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['Welcome to KeyMaster PRO. This Course teaches you more than which key to press \u2014 how the keyboard is laid out, how notes move, how rhythm is felt, how music is read, and how the hand finds its shape naturally.', 'We begin with the foundations: sitting well, finding the keyboard, hearing low and high, recognising the black-key patterns, naming notes, and feeling a steady pulse. Then we begin making music. There is no need to rush \u2014 I\u2019ll guide you one step at a time.'],
    mode: 'none',
  },
  {
    eyebrow: 'The keyboard', title: 'Meet the keyboard', id: 'meet-keyboard',
    cues: { labels: [{ midi: 48, text: 'low', place: 'below' }, { midi: 88, text: 'high', place: 'below' }] },
    say: [
      { text: 'Let\u2019s orient the keyboard first.', pauseAfter: 520, tone: 'warm' },
      { text: 'Lower notes live to your left, higher notes to your right.', pauseAfter: 560 },
      { text: 'Play any key, and listen to where its sound sits.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['Let\u2019s orient the keyboard first. Lower notes live to your left, higher notes to your right.', 'Play any key, and listen to where its sound sits.'],
    show: { kind: 'keys', midis: [48, 60, 72, 88], caption: 'One row \u2014 low on the left, high on the right.', label: 'Low \u2190                      \u2192 High' },
    demo: [48, 88], demoGap: 0.6,
    tryPrompt: 'Play any key, and listen to where its sound sits — low to the left, high to the right.', mode: 'any',
    okMsg: 'Good. That is your first landmark: sound moves across the keyboard, low to high.',
  },
  {
    eyebrow: 'Low and high', title: 'Low and high sounds', id: 'low-high',
    cues: { range: { from: 48, to: 88, lowLabel: 'low', highLabel: 'high' }, labels: [{ midi: 60, text: 'C', place: 'below', badge: true }] },
    say: [
      { text: 'The keyboard is laid out by pitch.', pauseAfter: 500, tone: 'warm' },
      { text: 'Keys to the left sound lower; keys to the right sound higher.', pauseAfter: 560 },
      { text: 'Play a low note on the left \u2014 then a high note on the right.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['The keyboard is laid out by pitch. To the left the sound is lower and deeper; to the right it grows higher and brighter.', 'Touch a low note on the left and hear how deep it sounds. Then find a higher note on the right, and notice how the sound brightens.'],
    show: { kind: 'keys', midis: [48, 88], caption: 'Left is low \u2014 right is high, across the whole keyboard.', label: 'low                          high' },
    demo: [48, 88], demoGap: 0.6,
    tryPrompt: 'Touch a low note on the left, then a higher note on the right \u2014 and listen to how the sound changes.', mode: 'lowhigh',
    okMsg: 'Good \u2014 low on the left, high on the right. You\u2019re hearing the shape of the keyboard.',
  },

  // ===========================================================================
  // YOUR HANDS \u2014 the physical foundation, taught before any patterns. Posture,
  // a relaxed curved hand, the finger numbers (1 = thumb \u2026 5 = little finger),
  // right vs left, and the thumb's role. Uses original hand diagrams (handViz).
  // ===========================================================================
  {
    eyebrow: 'Your hands', title: 'Sitting at the keyboard', id: 'sit-approach',
    say: [
      { text: 'Before we play patterns, let\u2019s set up your hands. Good habits now make everything later easier.', pauseAfter: 620, tone: 'warm' },
      { text: 'Sit tall, a little back from the keys, roughly centred. Let your arms hang easily, elbows about level with the keyboard, shoulders down and relaxed.', pauseAfter: 700 },
      { text: 'Bring a hand toward the keys with the weight carried by your arm, not gripped in the fingers. The wrist stays level \u2014 never locked, never dropped.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Sit tall, a little back and roughly centred, arms hanging easily \u2014 elbows about level with the keys, shoulders relaxed.', 'Bring the hand toward the keys with the arm carrying the weight, wrist level and loose. This relaxed, supported approach is the foundation of good tone.'],
    show: { kind: 'hand', hand: 'right', caption: 'Relaxed and supported \u2014 wrist level, arm carrying the weight.' },
    mode: 'none',
  },
  {
    eyebrow: 'Your hands', title: 'A natural hand shape', id: 'hand-shape',
    say: [
      { text: 'Now the shape of the hand itself. Let the fingers stay gently rounded, the knuckles slightly up \u2014 a soft dome, as if a small ball rested under your palm.', pauseAfter: 700, tone: 'warm' },
      { text: 'Notice the fingers are different lengths. The middle three \u2014 two, three and four \u2014 are longer, and reach a little further forward. That matters once we meet the black keys.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Keep the hand\u2019s natural curve \u2014 fingers gently rounded, knuckles slightly up, a soft dome under the palm. Never flat, never tense.', 'The longer fingers (2, 3, 4) reach a little further forward than the thumb and little finger \u2014 which is exactly why the B-major shape will feel natural later.'],
    show: { kind: 'hand', hand: 'right', sweep: [2, 3, 4], caption: 'Gently curved, knuckles up \u2014 the long fingers (2, 3, 4) reach furthest.' },
    mode: 'none',
  },
  {
    eyebrow: 'Your hands', title: 'The numbered fingers', id: 'fingers-rh',
    say: [
      { text: 'Each finger has a number, the same in every method: the thumb is one, then two, three, four, and the little finger is five.', pauseAfter: 700, tone: 'warm' },
      { text: 'Watch your right hand: one, two, three, four, five.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['Every finger has a number \u2014 the same the world over. Thumb is 1, then 2, 3, 4, and the little finger is 5.', 'These numbers tell you which finger to use. Watch them light in order on the right hand.'],
    show: { kind: 'hand', hand: 'right', sweep: [1, 2, 3, 4, 5], caption: 'Right hand: 1 (thumb) to 5 (little finger).' },
    mode: 'none',
  },
  {
    eyebrow: 'Your hands', title: 'The left hand mirrors', id: 'fingers-lh',
    say: [
      { text: 'The left hand uses the same numbers \u2014 mirrored. Its thumb is also one, sitting toward the middle of the keyboard.', pauseAfter: 680, tone: 'warm' },
      { text: 'Watch the left hand: one, two, three, four, five.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['The left hand is numbered the same way \u2014 thumb is 1 \u2014 but mirrored, so its thumb points toward the middle of the keyboard.', 'Right thumb and left thumb both sit near the centre; the little fingers reach outward.'],
    show: { kind: 'hand', hand: 'left', sweep: [1, 2, 3, 4, 5], caption: 'Left hand: 1 (thumb) to 5 (little finger), mirrored.' },
    mode: 'none',
  },
  {
    eyebrow: 'Your hands', title: 'Two hands, mirrored', id: 'hands-mirror',
    say: [
      { text: 'Here are both hands together. They use the same numbers, one to five \u2014 but they mirror each other.', pauseAfter: 660, tone: 'warm' },
      { text: 'Both thumbs are finger one, and both sit toward the middle of the keyboard. The little fingers, finger five, reach outward to the ends.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['The two hands mirror each other. Both thumbs are finger 1 and sit toward the centre; both little fingers are finger 5 and reach outward.', 'Left hand on the left, right hand on the right \u2014 each numbered outward from its thumb.'],
    show: { kind: 'hand', hand: 'both', sweep: [1], caption: 'Left and right \u2014 both thumbs (1) toward the centre.' },
    mode: 'none',
  },
  {
    eyebrow: 'Your hands', title: 'Play with your thumb', id: 'thumb-play',
    say: [
      { text: 'Let\u2019s use a finger on purpose. Your thumb is finger one \u2014 strong and close to the keys.', pauseAfter: 600, tone: 'warm' },
      { text: 'With your right thumb, play any white key near the middle. Let the arm support it \u2014 don\u2019t press hard.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['Your thumb is finger 1. It plays from the side, staying close to the keys.', 'With the right thumb, play any white key near the middle \u2014 a relaxed, supported sound. (We trust your hand here; play with intention.)'],
    show: { kind: 'keys', midis: [60], caption: 'Thumb \u2014 finger 1.', label: 'Finger 1' },
    handHint: { hand: 'right', highlight: [1] },
    tryPrompt: 'Play any white key near the middle with your right thumb (finger 1).', mode: 'any',
    okMsg: 'That\u2019s finger 1, your thumb \u2014 playing with intention. This is how every note begins: a chosen finger, a relaxed hand.',
    hint: 'Any white key near the centre is fine \u2014 the point is using the thumb, finger 1.',
  },
  {
    eyebrow: 'Your hands', title: 'Play with finger 3', id: 'finger3-play',
    say: [
      { text: 'Now your longest finger \u2014 the middle finger, number three.', pauseAfter: 560, tone: 'warm' },
      { text: 'With right finger three, play any white key near the middle. Keep the hand curved, the wrist level.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['Finger 3 is your longest \u2014 the middle finger. Long fingers reach in toward the black keys naturally.', 'With right finger 3, play any white key near the middle, hand curved and wrist level.'],
    show: { kind: 'keys', midis: [64], caption: 'Middle finger \u2014 finger 3.', label: 'Finger 3' },
    handHint: { hand: 'right', highlight: [3] },
    tryPrompt: 'Play any white key near the middle with right finger 3.', mode: 'any',
    okMsg: 'Good \u2014 finger 3, curved and supported. Knowing your finger numbers is what lets a teacher (or this Course) guide your hands precisely.',
    hint: 'Any white key is fine \u2014 the point is using finger 3, the long middle finger.',
  },
  {
    eyebrow: 'Your hands', title: 'Press with control', id: 'press-control',
    say: [
      { text: 'One last habit before we play patterns: control.', pauseAfter: 520, tone: 'warm' },
      { text: 'Watch the finger, then press a single key slowly and deliberately \u2014 let the arm guide it down, don\u2019t jab. Feel the key under your finger, and listen to the sound it makes.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Press a single key slowly and deliberately, the arm guiding the finger down \u2014 controlled, not jabbed.', 'This joins the three things piano asks of you at once: seeing the finger, feeling the key, and hearing the sound. Play any one white key, with control.'],
    show: { kind: 'keys', midis: [62], caption: 'See it, feel it, hear it.', label: 'Control' },
    handHint: { hand: 'right', highlight: [2] },
    demo: [62], demoGap: 0.5,
    tryPrompt: 'Press any single white key slowly, with control \u2014 and listen to it.', mode: 'any',
    okMsg: 'Good \u2014 a slow, supported press. Seeing, feeling and hearing together is how every note is played well. Now your hands are ready.',
    hint: 'Any single white key \u2014 the point is a slow, controlled, supported press, listening as you go.',
  },
  {
    eyebrow: 'Finding your way', title: 'Black-key groups of two', id: 'black-keys-two',
    cues: { brackets: [{ midis: [61, 63], label: 'group of two' }] },
    say: [
      { text: 'A keyboard has white keys and black keys.', pauseAfter: 520, tone: 'warm' },
      { text: 'The black keys sit in groups of two and three, and that pattern repeats \u2014 it helps you find your place.', pauseAfter: 580 },
      { text: 'Here is a group of two.', pauseAfter: 460, tone: 'instruct', emphasis: 'two' },
      { text: 'Now you try \u2014 tap either black key.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['A keyboard has white keys and black keys. The black keys sit in groups of two and three, and that pattern repeats across the keyboard \u2014 it helps you find your place.', 'Here is a group of two.'],
    show: { kind: 'keys', midis: [61, 63], caption: 'A group of two black keys.', label: 'group of two' },
    demo: [61, 63], demoGap: 0.4,
    tryPrompt: 'Tap one of the two black keys in the highlighted group.', targets: [61, 63], mode: 'oneof',
    okMsg: 'Good \u2014 that\u2019s one of the pair. The groups of two are your first anchor points.',
    hint: 'The group of two is highlighted \u2014 tap either black key.',
    reteach: 'Look again \u2014 the two black keys sit close together, with a wider gap before the next group. Tap either one.',
  },
  {
    eyebrow: 'Finding your way', title: 'Black-key groups of three', id: 'black-keys-three',
    cues: { brackets: [{ midis: [66, 68, 70], label: 'group of three' }] },
    say: [
      { text: 'Next to the twos are groups of three.', pauseAfter: 520, tone: 'warm' },
      { text: 'Here is a group of three.', pauseAfter: 520, tone: 'instruct', emphasis: 'three' },
      { text: 'We use these groups as landmarks.', pauseAfter: 520 },
      { text: 'Now you try \u2014 tap any of the three.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['Next to the twos are groups of three black keys.', 'Here is a group of three.'],
    show: { kind: 'keys', midis: [66, 68, 70], caption: 'A group of three black keys.', label: 'group of three' },
    demo: [66, 68, 70], demoGap: 0.34,
    tryPrompt: 'Tap one of the three black keys in the highlighted group.', targets: [66, 68, 70], mode: 'oneof',
    okMsg: 'Good \u2014 that\u2019s the group of three. The groups of two and three repeat across the keyboard, so you can always find your place.',
    hint: 'The group of three is highlighted \u2014 tap any of them.',
    reteach: 'Look again \u2014 the group of three is the wider cluster. Tap any one of the three.',
  },
  {
    eyebrow: 'The landmark C', title: 'Find C', id: 'find-c',
    cues: { arrow: { from: [61, 63], to: 60 }, labels: [{ midi: 60, text: 'C', place: 'below', badge: true }] },
    say: [
      { text: 'Find a group of two black keys.', pauseAfter: 520 },
      { text: 'The white key just to their left is C.', pauseAfter: 560, tone: 'warm', emphasis: 'C' },
      { text: 'Because the pattern repeats, C is everywhere.', pauseAfter: 480 },
      { text: 'Now you try \u2014 find a C.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['C is the white key just to the left of every group of two black keys.', 'Because the pattern repeats, you can find a C anywhere.'],
    show: { kind: 'keys', midis: [60], caption: 'C sits just left of the two black keys.', label: 'this is C' },
    demo: [60], demoGap: 0.45,
    tryPrompt: 'Find and press a C \u2014 just left of a group of two black keys.', targets: [60], mode: 'one',
    okMsg: 'Good \u2014 that\u2019s C, just to the left of the two black keys.',
    hint: 'C is the white key immediately left of a group of two black keys.',
    reteach: 'Let\u2019s look again \u2014 first find a group of two black keys, then the white key just to their left is C.',
  },
  {
    eyebrow: 'White-key names', title: 'Find D', id: 'find-d',
    cues: { arrow: { from: [61, 63], to: 62 }, labels: [{ midi: 62, text: 'D', place: 'below' }] },
    say: [
      { text: 'D sits right between the two black keys.', pauseAfter: 540, tone: 'warm', emphasis: 'D' },
      { text: 'Now you try \u2014 find a D.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['D sits in the middle of the group of two black keys \u2014 right between them.', 'Because the pattern repeats, there is a D in every group of two.'],
    show: { kind: 'keys', midis: [62], caption: 'D \u2014 between the two black keys.', label: 'this is D' },
    demo: [62], demoGap: 0.45,
    tryPrompt: 'Find and press a D \u2014 between the two black keys.', targets: [62], mode: 'one',
    okMsg: 'Yes \u2014 that\u2019s D, sitting between the two black keys.',
    hint: 'D is the white key between the group of two black keys.',
  },
  {
    eyebrow: 'White-key names', title: 'Find E', id: 'find-e',
    cues: { labels: [{ midi: 64, text: 'E', place: 'below' }] },
    say: [
      { text: 'E sits just to the right of the two black keys.', pauseAfter: 540, tone: 'warm', emphasis: 'E' },
      { text: 'Now you try \u2014 find an E.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['E is the white key just to the right of the two black keys.', 'C, D, E \u2014 the three white keys around the group of two.'],
    show: { kind: 'keys', midis: [64], caption: 'E \u2014 just right of the two black keys.', label: 'this is E' },
    demo: [64], demoGap: 0.45,
    tryPrompt: 'Find and press an E \u2014 just right of the two black keys.', targets: [64], mode: 'one',
    okMsg: 'That\u2019s E, just to the right of the two black keys.',
    hint: 'E is the white key immediately right of the group of two black keys.',
  },
  {
    eyebrow: 'White-key names', title: 'Find F', id: 'find-f',
    cues: { arrow: { from: [66, 68, 70], to: 65 }, labels: [{ midi: 65, text: 'F', place: 'below' }] },
    say: [
      { text: 'F sits just to the left of the three black keys.', pauseAfter: 540, tone: 'warm', emphasis: 'F' },
      { text: 'Now you try \u2014 find an F.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['F is the white key just to the left of the group of three black keys.', 'The three black keys are your signpost for F.'],
    show: { kind: 'keys', midis: [65], caption: 'F \u2014 just left of the three black keys.', label: 'this is F' },
    demo: [65], demoGap: 0.45,
    tryPrompt: 'Find and press an F \u2014 just left of the three black keys.', targets: [65], mode: 'one',
    okMsg: 'Good \u2014 that\u2019s F, just to the left of the three black keys.',
    hint: 'F is the white key immediately left of the group of three black keys.',
  },
  {
    eyebrow: 'White-key names', title: 'Find G', id: 'find-g',
    cues: { labels: [{ midi: 67, text: 'G', place: 'below' }] },
    say: [
      { text: 'After F comes G \u2014 the next white key up.', pauseAfter: 540, tone: 'warm', emphasis: 'G' },
      { text: 'Now you try \u2014 find a G.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['G is the next white key to the right of F.', 'It sits between the first two of the three black keys.'],
    show: { kind: 'keys', midis: [67], caption: 'G \u2014 just right of F.', label: 'this is G' },
    demo: [67], demoGap: 0.45,
    tryPrompt: 'Find and press a G \u2014 the white key just right of F.', targets: [67], mode: 'one',
    okMsg: 'Yes \u2014 that\u2019s G, the next white key along.',
    hint: 'G is the next white key to the right of F.',
  },
  {
    eyebrow: 'White-key names', title: 'Find A', id: 'find-a',
    cues: { labels: [{ midi: 69, text: 'A', place: 'below' }] },
    say: [
      { text: 'After G comes A.', pauseAfter: 540, tone: 'warm', emphasis: 'A' },
      { text: 'Now you try \u2014 find an A.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['A is the next white key to the right of G.', 'C, D, E, F, G, A \u2014 the white-key names climbing upward.'],
    show: { kind: 'keys', midis: [69], caption: 'A \u2014 just right of G.', label: 'this is A' },
    demo: [69], demoGap: 0.45,
    tryPrompt: 'Find and press an A \u2014 the white key just right of G.', targets: [69], mode: 'one',
    okMsg: 'That\u2019s A. You can now name all of the white keys.',
    hint: 'A is the next white key to the right of G.',
  },
  {
    eyebrow: 'Your home note', title: 'Find exact Middle C', id: 'middle-c',
    cues: { arrow: { from: [61, 63], to: 60 }, labels: [{ midi: 60, text: 'Middle C', place: 'below', badge: true }] },
    say: [
      { text: 'Look near the centre of the keyboard.', pauseAfter: 520 },
      { text: 'Find the two black keys there.', pauseAfter: 520 },
      { text: 'The white key to their left is Middle C.', pauseAfter: 560, tone: 'warm', emphasis: 'Middle C' },
      { text: 'Here it is.', pauseAfter: 460 },
      { text: 'Now you try.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['Middle C is one special C, near the centre of the piano.', 'It is a landmark for reading music.'],
    show: { kind: 'keys', midis: [60], caption: 'Middle C \u2014 near the centre.', label: 'Middle C' },
    demo: [60], demoGap: 0.45,
    tryPrompt: 'Press Middle C \u2014 the highlighted key near the centre.', targets: [60], exact: true, mode: 'one',
    okMsg: 'That\u2019s Middle C \u2014 the C nearest the centre of the keyboard.',
    hint: 'Middle C is the highlighted key, near the centre.',
    reteach: 'Let\u2019s look again \u2014 Middle C is near the centre, the white key just left of the two black keys there.',
  },
  {
    eyebrow: 'The note B', title: 'Find B below Middle C', id: 'b-below',
    cues: { arrow: { from: 60, to: 59 }, labels: [{ midi: 60, text: 'C', place: 'below', badge: true }, { midi: 59, text: 'B', place: 'below' }] },
    say: [
      { text: 'Start from Middle C.', pauseAfter: 500 },
      { text: 'Step one white key to the left.', pauseAfter: 540, tone: 'warm' },
      { text: 'That note is B \u2014 the B below Middle C.', pauseAfter: 560, emphasis: 'B' },
      { text: 'Later, this B becomes the starting note of the B major scale.', pauseAfter: 460, tone: 'warm' },
      { text: 'Now you try.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['Step one white key to the left of Middle C. That note is B \u2014 the B below Middle C.', 'Later, this B will be the starting note of our B major scale.'],
    show: { kind: 'keys', midis: [59, 60], caption: 'B sits immediately left of Middle C.', label: 'C \u2192 one step left \u2192 B' },
    demo: [60, 59], demoGap: 0.5,
    tryPrompt: 'Press the B just below Middle C \u2014 one white key to the left.', targets: [59], exact: true, mode: 'one',
    okMsg: 'Good \u2014 that\u2019s B, the white key just below Middle C.',
    hint: 'B is the white key immediately left of Middle C.',
    reteach: 'Let\u2019s look again \u2014 find Middle C first, then step one white key to the left for B.',
  },
  {
    eyebrow: 'Direction', title: 'First direction: up and down', id: 'direction',
    cues: { arrow: { from: 60, to: 62 } },
    say: [
      { text: 'Moving to the right raises the pitch.', pauseAfter: 500, tone: 'warm' },
      { text: 'Moving to the left lowers it.', pauseAfter: 480 },
      { text: 'Play two notes that rise \u2014 C, then D.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['Moving right raises the pitch; moving left lowers it.', 'Play two notes that rise \u2014 C, then the next white key up, D.'],
    show: { kind: 'keys', midis: [60, 62], caption: 'C up to D \u2014 going up.', label: 'up \u2192' },
    demo: [60, 62], demoGap: 0.4,
    tryPrompt: 'Play C, then D \u2014 two notes rising in pitch.', targets: [60, 62], mode: 'sequence',
    okMsg: 'Good \u2014 that\u2019s motion upward, C to D. Direction is how a melody moves.',
    hint: 'Start on C, then the next white key to the right, D.',
  },
  {
    eyebrow: 'Movement', title: 'Steps and skips', id: 'step-skip',
    cues: { labels: [{ midi: 60, text: 'C', place: 'below' }, { midi: 64, text: 'E', place: 'below' }] },
    say: [
      { text: 'Moving to the very next key is a step.', pauseAfter: 520 },
      { text: 'Jumping over a key is a skip.', pauseAfter: 540, tone: 'warm' },
      { text: 'Play C, then skip up to E.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['A step moves to the next note; a skip jumps over one.', 'Play C, then skip up to E \u2014 leaving D in between.'],
    show: { kind: 'keys', midis: [60, 64], caption: 'C up to E \u2014 a skip.', label: 'C \u2013 E (a skip)' },
    demo: [60, 64], demoGap: 0.5,
    tryPrompt: 'Play C, then skip up to E.', targets: [60, 64], mode: 'sequence',
    okMsg: 'Good \u2014 C to E is a skip. Steps and skips are how melodies move.',
    hint: 'Play C first, then skip over D to E.',
  },
  {
    eyebrow: 'Tones & semitones', title: 'The smallest step: a semitone', id: 'semitone',
    say: [
      { text: 'Two useful words now, ones we\u2019ll keep using as scales and keys grow: semitone and tone.', pauseAfter: 600, tone: 'warm' },
      { text: 'A semitone is the smallest step there is \u2014 from one key to the very next key, with nothing between, whether that next key is white or black.', pauseAfter: 600 },
      { text: 'E and F are neighbours with no key between them. Play E, then F \u2014 that move is one semitone.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['A semitone is the smallest step \u2014 from any key to the very next key, with nothing between, white or black.', 'E and F sit side by side with no key between. Play E, then F: that is one semitone.'],
    show: { kind: 'keys', midis: [64, 65], caption: 'E to F \u2014 one semitone (no key between).', label: 'E \u2013 F = a semitone' },
    demo: [64, 65], demoGap: 0.5,
    tryPrompt: 'Play E, then the very next key F \u2014 one semitone.', targets: [64, 65], mode: 'sequence', manualNext: true,
    okMsg: 'Good \u2014 that\u2019s a semitone: the smallest move on the keyboard. Stepping to a black key is a semitone too.',
    hint: 'E and F are the two white keys with no black key between them.',
  },
  {
    eyebrow: 'Tones & semitones', title: 'Two steps: a tone', id: 'tone',
    say: [
      { text: 'A tone is simply two semitones \u2014 two of those smallest steps joined together.', pauseAfter: 580, tone: 'warm' },
      { text: 'From C, step up past the black key to D. You\u2019ve moved two semitones \u2014 that is one tone.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['A tone is two semitones \u2014 two smallest steps at once.', 'C up to D skips the black key between them: two semitones, so C to D is one tone.'],
    show: { kind: 'keys', midis: [60, 62], caption: 'C to D \u2014 one tone (two semitones).', label: 'C \u2013 D = a tone' },
    demo: [60, 62], demoGap: 0.5,
    tryPrompt: 'Play C, then D \u2014 a tone (two semitones).', targets: [60, 62], mode: 'sequence', manualNext: true,
    okMsg: 'Good \u2014 a tone: two semitones. Scales are built from tones and semitones in a set order, as you\u2019ll see.',
    hint: 'C and D are white keys with one black key between them \u2014 that gap makes it a tone.',
  },
  {
    eyebrow: 'What a scale is', title: 'Why scales matter', id: 'scale-why',
    say: [
      { text: 'Before we climb one, a word on why scales matter.', pauseAfter: 540, tone: 'warm' },
      { text: 'A scale is an ordered set of steps \u2014 the basic vocabulary of a key. Melodies, chords and whole pieces are drawn from it, and practising one trains the hand to move evenly and find its shape.', pauseAfter: 680 },
      { text: 'We\u2019ll start in C because its steps are all white keys \u2014 easy to see and name. The hand-shape pathway then moves into B major, where the fingers fit the keys especially well.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A scale is an ordered set of steps \u2014 the vocabulary of a key. Melodies, chords and pieces are built from it, and practising one trains the hand to move evenly.', 'We start in C (all white keys, easy to see), then the hand-shape pathway moves into B major, where the fingers fit the keys especially well.'],
    show: { kind: 'keys', midis: [60, 62, 64, 65, 67], caption: 'A scale: steps in order, C upward.', label: 'a scale = steps in order' },
    tryPrompt: 'Play these five notes in order: C, D, E, F, then G.',
    targets: [60, 62, 64, 65, 67], mode: 'sequence',
    okMsg: 'That\u2019s it \u2014 five steps climbing. That is the shape of a scale.',
    hint: 'They\u2019re the white keys from C, in order: C, D, E, F, G.',
  },
  {
    eyebrow: 'Notes in order', title: 'First scale idea', id: 'first-scale',
    cues: { labels: [{ midi: 60, text: 'C', place: 'below' }, { midi: 62, text: 'D', place: 'below' }, { midi: 64, text: 'E', place: 'below' }] },
    say: [
      { text: 'A scale is steps in order \u2014 a ladder of pitch.', pauseAfter: 520, tone: 'warm' },
      { text: 'Climb the first three.', pauseAfter: 460, tone: 'instruct' },
      { text: 'C, then D, then E.', pauseAfter: 300 },
    ],
    explain: ['A scale is simply steps in order \u2014 a ladder of pitch.', 'Climb the first three: C, D, E.'],
    show: { kind: 'keys', midis: [60, 62, 64], caption: 'C, D, E \u2014 step by step.', label: 'C \u2013 D \u2013 E' },
    demo: [60, 62, 64], demoGap: 0.3,
    tryPrompt: 'Climb the first three steps in order: C, D, then E.', targets: [60, 62, 64], mode: 'sequence',
    okMsg: 'Good \u2014 C, D, E. That\u2019s the opening of a scale: three steps climbing.',
    hint: 'In order on the white keys: C, then D, then E.',
  },
  {
    eyebrow: 'The C scale', title: 'Five steps up', id: 'c-scale-five',
    say: [
      { text: 'Let\u2019s climb further \u2014 five steps of the C scale.', pauseAfter: 560, tone: 'warm' },
      { text: 'C, D, E, F, G \u2014 each the very next white key.', pauseAfter: 560 },
      { text: 'I\u2019ll play it, then you climb it.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['A scale climbs by steps. Here are five: C, D, E, F, G.', 'Each note is the next white key to the right.'],
    show: { kind: 'keys', midis: [60, 62, 64, 65, 67], caption: 'C, D, E, F, G \u2014 five steps up.', label: 'C D E F G' },
    demo: [60, 62, 64, 65, 67], demoGap: 0.42,
    tryPrompt: 'Climb the C scale: C, D, E, F, G.', targets: [60, 62, 64, 65, 67], mode: 'sequence',
    okMsg: 'Good \u2014 C, D, E, F, G. The first five notes of the C major scale.',
    hint: 'Start on C and play each next white key in turn: C, D, E, F, G.',
  },
  {
    eyebrow: 'The C scale', title: 'And back down', id: 'c-scale-down',
    say: [
      { text: 'A scale comes down as well as up.', pauseAfter: 540, tone: 'warm' },
      { text: 'From G, step down: G, F, E, D, C.', pauseAfter: 560 },
      { text: 'Now you bring it home.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['Now descend the same five notes: G, F, E, D, C.', 'Down is just up, in reverse.'],
    show: { kind: 'keys', midis: [67, 65, 64, 62, 60], caption: 'G, F, E, D, C \u2014 five steps down.', label: 'G F E D C' },
    demo: [67, 65, 64, 62, 60], demoGap: 0.42,
    tryPrompt: 'Come down the C scale: G, F, E, D, C.', targets: [67, 65, 64, 62, 60], mode: 'sequence',
    okMsg: 'Good \u2014 up and down. You\u2019ve played your first scale, both directions.',
    hint: 'Start on G and step down: G, F, E, D, C.',
  },
  {
    eyebrow: 'A new shape', title: 'A taste of B major', id: 'first-b-scale',
    progressKey: 'scale:b-major-fragment',
    media: { kind: 'video', topic: 'hand-shape', caption: 'The B major hand shape \u2014 guided demonstration' },
    cues: { labels: B_FRAGMENT.map((m, i) => ({ midi: m, text: B_FRAGMENT_NAMES[i], place: 'below' })) },
    explain: ['Those notes moved upward. Now hear a different shape \u2014 the opening of B major.', `Copy these three: ${B_FRAGMENT_NAMES.join(', then ')}.`],
    show: { kind: 'keys', midis: B_FRAGMENT, caption: `${B_FRAGMENT_NAMES.join(', ')} \u2014 the first steps of B major.`, label: B_FRAGMENT_NAMES.join(' \u2013 ') },
    demo: B_FRAGMENT, demoGap: 0.32,
    tryPrompt: `Copy the shape: ${B_FRAGMENT_NAMES.join(', then ')}.`, targets: B_FRAGMENT, mode: 'sequence',
    okMsg: `That\u2019s the opening of B major \u2014 ${B_FRAGMENT_NAMES.join(', ')}.`,
    hint: 'In order: B, then the black key C#, then the black key D#.',
    reteach: 'B is the white key just left of the two black keys. Climb: B, C#, D#.',
  },
  {
    eyebrow: 'Why B major', title: 'The B-major pathway', id: 'b-major-why',
    say: [
      { text: 'You just played the opening of B major.', pauseAfter: 540, tone: 'warm' },
      { text: 'B major fits the hand beautifully \u2014 the black keys give your longer fingers natural resting points.', pauseAfter: 640 },
      { text: 'That\u2019s why KeyMaster PRO grows your playing from a B-major home: it builds confident, ergonomic technique.', pauseAfter: 320 },
    ],
    explain: ['B major fits the hand well \u2014 the black keys give your longer fingers natural resting points, and the shorter fingers fall comfortably on the white keys.', 'That is why KeyMaster PRO uses a B-major pathway as a home for building technique. The Scales Masterclass takes this much further.'],
    mode: 'none',
  },
  {
    eyebrow: 'Looking ahead', title: 'Scales come next', id: 'bridge-scales',
    explain: ['You found C and climbed your first steps upward \u2014 the beginning of a scale.', 'Scales have their own stage further on in the Course. For deeper practice any time, the Scales Masterclass is always open.'],
    show: { kind: 'keys', midis: [59, 61, 63, 64, 66, 68, 70, 71], caption: 'B major sits naturally under the hand.' },
    demo: [59, 61, 63, 64, 66, 68, 70, 71], demoGap: 0.26, mode: 'none',
    bridge: { label: 'For deeper scale practice, open Scales Masterclass', hash: '#/scales' },
    autoNext: 4200,
  },
  {
    eyebrow: 'Notes together', title: 'First chord idea', id: 'first-chord',
    explain: ['A chord is several notes sounded together.', 'C, E and G together make a C major chord.'],
    show: { kind: 'keys', midis: [60, 64, 67], caption: 'C + E + G = C major.', label: 'C + E + G' },
    demo: [60, 64, 67], demoGap: 0.08,
    tryPrompt: 'Press C, E and G together.', targets: [60, 64, 67], mode: 'set',
    okMsg: 'That\u2019s a C major chord \u2014 C, E and G together.',
    hint: 'Press the three highlighted keys together: C, E and G.',
  },
  {
    eyebrow: 'A second chord', title: 'G major chord', id: 'chord-g',
    cues: { labels: [{ midi: 67, text: 'G', place: 'below' }, { midi: 71, text: 'B', place: 'below' }, { midi: 74, text: 'D', place: 'below' }] },
    say: [
      { text: 'You know one chord. Here is a second.', pauseAfter: 520, tone: 'warm' },
      { text: 'G, B and D, played together, make a G major chord.', pauseAfter: 560, emphasis: 'G' },
      { text: 'Press all three at once.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['Stack G, B and D and play them together \u2014 that is a G major chord.', 'Like C major, it is built from every-other white key.'],
    show: { kind: 'keys', midis: [67, 71, 74], caption: 'G, B, D \u2014 a G major chord.', label: 'G \u2013 B \u2013 D' },
    demo: [67, 71, 74], demoGap: 0.08,
    tryPrompt: 'Press G, B and D together.', targets: [67, 71, 74], mode: 'set',
    okMsg: 'That\u2019s a G major chord \u2014 G, B and D. You now have two chords.',
    hint: 'Press the three highlighted keys together: G, B and D.',
  },
  {
    eyebrow: 'Looking ahead', title: 'Chords come next', id: 'bridge-chords',
    explain: ['You sounded your first chord \u2014 three notes ringing together.', 'Chords have their own stage further on in the Course. For extra practice any time, the Chord Masterclass is always open.'],
    show: { kind: 'keys', midis: [60, 64, 67], caption: 'Chords are built from stacked notes.' },
    demo: [60, 64, 67], demoGap: 0.08, mode: 'none',
    bridge: { label: 'For extra chord practice, open Chord Masterclass', hash: '#/chords' },
    autoNext: 3200,
  },
  {
    eyebrow: 'Reading the staff', title: 'The staff: lines', id: 'staff-what',
    say: [
      { text: 'A quick foundation that unlocks written music: the staff.', pauseAfter: 540, tone: 'warm' },
      { text: 'The staff is the map musicians use to show pitch. Each staff has five lines. A note\u2019s height on the staff tells you how high or low it sounds.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['The staff is the map musicians use to show pitch \u2014 higher on the staff means higher in sound.', 'It has five lines. Here they are, highlighted.'],
    show: { kind: 'staff', clef: 'treble', highlight: 'lines', caption: 'Five lines.' },
    mode: 'none',
  },
  {
    eyebrow: 'Reading the staff', title: 'The staff: spaces', id: 'staff-spaces',
    say: [
      { text: 'Between the five lines are four spaces.', pauseAfter: 520, tone: 'warm' },
      { text: 'A note can sit on a line, or in a space. Lines and spaces together give every pitch a place.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Between the five lines are four spaces. A note can sit on a line, or in a space.', 'Here are the four spaces, highlighted.'],
    show: { kind: 'staff', clef: 'treble', highlight: 'spaces', caption: 'Four spaces.' },
    mode: 'none',
  },
  {
    eyebrow: 'Reading the staff', title: 'The treble clef', id: 'treble-clef',
    say: [
      { text: 'At the start of a staff sits a clef \u2014 it tells you which pitches the lines and spaces stand for.', pauseAfter: 600, tone: 'warm' },
      { text: 'The treble clef usually helps us read higher notes \u2014 often the right hand at the piano.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['A clef at the start of the staff tells you which pitches the lines and spaces mean.', 'The treble clef usually carries the higher notes \u2014 at the piano, often the right hand.'],
    show: { kind: 'staff', clef: 'treble', caption: 'The treble clef \u2014 higher notes.' },
    mode: 'none',
  },
  {
    eyebrow: 'Reading the staff', title: 'The bass clef', id: 'bass-clef',
    say: [
      { text: 'The bass clef usually helps us read lower notes \u2014 often the left hand at the piano.', pauseAfter: 600, tone: 'warm' },
      { text: 'Same five lines and four spaces, but standing for lower pitches.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['The bass clef usually carries the lower notes \u2014 at the piano, often the left hand.', 'Same five lines and four spaces, standing for lower pitches.'],
    show: { kind: 'staff', clef: 'bass', caption: 'The bass clef \u2014 lower notes.' },
    mode: 'none',
  },
  {
    eyebrow: 'Reading the staff', title: 'The grand staff', id: 'grand-staff',
    say: [
      { text: 'Piano music often uses both clefs together, joined into one system. That is called the grand staff.', pauseAfter: 640, tone: 'warm' },
      { text: 'Treble on top for the right hand, bass below for the left \u2014 to begin with. And right in the middle sits Middle C.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Piano music joins both clefs into the grand staff \u2014 treble above, bass below. To begin with: treble for the right hand, bass for the left.', 'Between the two staves sits Middle C \u2014 the landmark that links them.'],
    show: { kind: 'staff', clef: 'grand', middleC: true, caption: 'The grand staff \u2014 Middle C sits between.' },
    mode: 'none',
  },
  {
    eyebrow: 'Reading the staff', title: 'Ledger lines', id: 'ledger-line',
    say: [
      { text: 'When notes go above or below the five lines, we add small extra lines called ledger lines.', pauseAfter: 620, tone: 'warm' },
      { text: 'They simply extend the staff. Middle C, just below the treble staff, sits on its own short ledger line \u2014 you can see it here.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['When notes go above or below the five lines, small extra lines \u2014 ledger lines \u2014 extend the staff.', 'Middle C sits on a ledger line just below the treble staff. That is the note shown here.'],
    show: { kind: 'staff', clef: 'treble', notes: [60], caption: 'Middle C on a ledger line below the treble staff.' },
    mode: 'none',
  },
  {
    eyebrow: 'Reading the staff', title: 'From staff to key', id: 'staff-to-key',
    say: [
      { text: 'Now connect it. This note on the staff is Middle C \u2014 and Middle C is a key you already know.', pauseAfter: 620, tone: 'warm' },
      { text: 'Find it on the staff, then find it on the keyboard, and play it.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['The note on the staff is Middle C. The staff shows it; the keyboard is where you play it.', 'Find Middle C \u2014 just left of the two black keys, near the centre \u2014 and play it.'],
    show: { kind: 'keys', midis: [60], caption: 'This staff note is Middle C.', label: 'Middle C' },
    staffHint: { clef: 'grand', notes: [60], middleC: true },
    demo: [60], demoGap: 0.45,
    tryPrompt: 'Find Middle C on the staff, then play it on the keyboard.', targets: [60], exact: true, mode: 'one', manualNext: true,
    okMsg: 'Good \u2014 you connected the written note to the key. That link, staff to keyboard, is the whole of reading.',
    hint: 'Middle C is the white key just left of the two black keys, near the centre.',
  },
  {
    eyebrow: 'Reading', title: 'Name and play: E', id: 'read-play-e',
    say: [
      { text: 'Reading music means knowing a note, then playing it.', pauseAfter: 560, tone: 'warm' },
      { text: 'The note is E. Find it and play it.', pauseAfter: 300, tone: 'instruct', emphasis: 'E' },
    ],
    explain: ['Reading music means recognising a note, then finding it on the keyboard.', 'The note is E \u2014 just right of the two black keys. Play it.'],
    show: { kind: 'keys', midis: [64], caption: 'The note is E.', label: 'E' },
    staffHint: { clef: 'treble', notes: [64] },
    demo: [64], demoGap: 0.45,
    tryPrompt: 'The note is E \u2014 find it and play it.', targets: [64], mode: 'one',
    okMsg: 'Good \u2014 you knew E, and you played it. That is where reading music begins.',
    hint: 'E is just right of the two black keys.',
  },
  {
    eyebrow: 'Reading', title: 'Name and play: G', id: 'read-play-g',
    say: [
      { text: 'One more. The note is G.', pauseAfter: 520, tone: 'warm', emphasis: 'G' },
      { text: 'Find it and play it.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['Know the note, then play it.', 'The note is G \u2014 just right of F.'],
    show: { kind: 'keys', midis: [67], caption: 'The note is G.', label: 'G' },
    staffHint: { clef: 'treble', notes: [67] },
    demo: [67], demoGap: 0.45,
    tryPrompt: 'The note is G \u2014 find it and play it.', targets: [67], mode: 'one',
    okMsg: 'Good \u2014 know it, then play it. Cognitive Sight-Reading takes this much further.',
    hint: 'G is just right of F.',
  },
  {
    eyebrow: 'Reading', title: 'First reading idea', id: 'first-reading',
    say: [
      { text: 'Written music lives on lines and spaces \u2014 the staff.', pauseAfter: 560, tone: 'warm' },
      { text: 'Middle C is the shared landmark between your two hands, the note we count outward from.', pauseAfter: 620 },
      { text: 'You already know it on the keys. Play Middle C now, and hold it as your anchor.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['Written music lives on a staff \u2014 lines and spaces. Middle C is the shared landmark between the hands, the note we count outward from.', 'You already know it on the keys. Play Middle C \u2014 your reading anchor.'],
    show: { kind: 'keys', midis: [60], caption: 'Middle C \u2014 your anchor, on the keys and on the page.', label: 'Middle C' },
    media: { kind: 'image', topic: 'staff', caption: 'Middle C on the staff \u2014 notation view' },
    demo: [60], demoGap: 0.45,
    tryPrompt: 'Play Middle C \u2014 your reading anchor.', targets: [60], exact: true, mode: 'one',
    okMsg: 'Good \u2014 that\u2019s your anchor. In Sight-Reading, every note is read from here.',
    hint: 'Middle C is the white key just left of the two black keys, near the centre.',
    progressKey: 'reading:middle-c-anchor',
  },
  {
    eyebrow: 'Looking ahead', title: 'Reading comes next', id: 'bridge-sightreading',
    explain: ['Reading grows from recognising landmarks like Middle C, then the patterns around them.', 'Reading has its own stage further on in the Course. For more drills any time, Cognitive Sight-Reading is always open.'],
    show: { kind: 'keys', midis: [60], caption: 'Start reading from Middle C.' },
    demo: [60], demoGap: 0.45, mode: 'none',
    bridge: { label: 'For more reading drills, open Cognitive Sight-Reading', hash: '#/sightreading' },
    autoNext: 3200,
  },
  {
    eyebrow: 'Rhythm', title: 'Feel the pulse', id: 'first-pulse',
    media: { kind: 'video', topic: 'pulse', caption: 'Keeping a steady pulse \u2014 guided demonstration' },
    say: [
      { text: 'Music moves in time, over a steady pulse \u2014 a calm, even heartbeat under the notes.', pauseAfter: 560, tone: 'warm' },
      { text: 'Music groups beats in different ways. A very common pattern is four beats: one, two, three, four. We\u2019ll start there.', pauseAfter: 640 },
      { text: 'Listen to the count first, then play a note on each beat. Don\u2019t rush.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['Music moves over a steady pulse \u2014 an even heartbeat under the notes.', 'Beats group in different ways; a very common one is four: 1, 2, 3, 4. Listen to the count first, then play a note on each beat.'],
    show: { kind: 'pulse', caption: 'A steady count of four: 1 2 3 4.' },
    tryPrompt: 'After the count, play four notes \u2014 one on each beat.', mode: 'count', count: 4,
    okMsg: 'Good \u2014 that\u2019s pulse: an even beat you can rely on. Every piece you play sits on it.',
    hint: 'Wait for the count to finish, then play any four notes, evenly spaced \u2014 don\u2019t rush.',
    progressKey: 'rhythm:first-pulse',
  },
  {
    eyebrow: 'Rhythm', title: 'Eight steady beats', id: 'pulse-eight',
    say: [
      { text: 'Let\u2019s hold the pulse a little longer \u2014 two groups of four.', pauseAfter: 540, tone: 'warm' },
      { text: 'Listen to the count, then play eight even notes \u2014 one on each beat.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['Keep the pulse steady and even \u2014 not rushing, not dragging.', 'Eight beats, grouped as two fours: 1 2 3 4 \u00B7 1 2 3 4. Play a note on each.'],
    show: { kind: 'pulse', caption: 'Two groups of four: 1 2 3 4 \u00B7 1 2 3 4.' },
    tryPrompt: 'After the count, play eight notes \u2014 one on each beat.', mode: 'count', count: 8,
    okMsg: 'Good \u2014 a steady pulse you can rely on. Other music counts in twos, threes, sixes and more, but a steady four is a strong place to start.',
  },
  {
    eyebrow: 'Checkpoint', title: 'Checkpoint: Middle C', id: 'review-c',
    say: [
      { text: 'A quick checkpoint \u2014 a chance to use what you already know.', pauseAfter: 540, tone: 'warm' },
      { text: 'Play Middle C.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['Let\u2019s bring together what you\u2019ve learned so far.', 'Find and play Middle C, near the centre.'],
    show: { kind: 'keys', midis: [60], caption: 'Middle C.', label: 'Middle C' },
    demo: [60], demoGap: 0.45,
    tryPrompt: 'Play Middle C.', targets: [60], exact: true, mode: 'one',
    okMsg: 'That\u2019s Middle C, near the centre \u2014 well remembered.',
    hint: 'Middle C is the white key just left of the two black keys, near the centre.',
  },
  {
    eyebrow: 'Checkpoint', title: 'Checkpoint: three steps', id: 'review-scale',
    say: [
      { text: 'Now play the first three steps of the C scale.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['From memory \u2014 climb the first three steps of the C scale.', 'C, then D, then E.'],
    show: { kind: 'keys', midis: [60, 62, 64], caption: 'C, D, E.', label: 'C D E' },
    demo: [60, 62, 64], demoGap: 0.46,
    tryPrompt: 'Play C, D, E in order.', targets: [60, 62, 64], mode: 'sequence',
    okMsg: 'Good \u2014 C, D, E. The scale is in your hands now.',
    hint: 'Start on C, then the next white key, then the next: C, D, E.',
  },
  {
    eyebrow: 'Checkpoint', title: 'Checkpoint: C major chord', id: 'review-chord',
    say: [
      { text: 'Last checkpoint \u2014 a chord.', pauseAfter: 500, tone: 'warm' },
      { text: 'Play C, E and G together.', pauseAfter: 300, tone: 'instruct' },
    ],
    explain: ['One chord, from memory.', 'Press C, E and G together \u2014 a C major chord.'],
    show: { kind: 'keys', midis: [60, 64, 67], caption: 'C, E, G together.', label: 'C \u2013 E \u2013 G' },
    demo: [60, 64, 67], demoGap: 0.08,
    tryPrompt: 'Press C, E and G together.', targets: [60, 64, 67], mode: 'set',
    okMsg: 'That\u2019s a C major chord. Orientation, names, scales, reading, rhythm and harmony \u2014 you\u2019ve begun them all.',
    hint: 'Press the three highlighted keys together: C, E and G.',
  },
  {
    eyebrow: 'Stage 1 complete', title: 'Foundations complete', id: 'stage1-complete',
    say: [
      { text: 'That\u2019s Stage 1 complete \u2014 the foundations are yours.', pauseAfter: 600, tone: 'warm' },
      { text: 'You can name the white keys, climb a scale up and down, play two chords, name a note and play it, and hold a steady pulse.', pauseAfter: 700 },
      { text: 'The Course now continues into Stage 2, where we begin shaping these notes into music. The masterclasses are there too, any time, for deeper practice.', pauseAfter: 360, tone: 'warm' },
    ],
    explain: ['Stage 1 complete \u2014 you\u2019ve built the foundations: the keyboard, the white keys, movement, scales, B major, harmony, naming notes, and a steady pulse.', 'Next is Stage 2, where these foundations become music. Continue the Course below \u2014 the masterclasses stay available any time for deeper practice.'],
    bridge: { label: 'Optional \u2014 open a practice room for deeper practice', hash: '#/scales' },
    mode: 'none',
  },

];
