// courseKeyLevel1.js
// KeyMaster Course · Key Level 1 — First Musicianship.
//
// The first level of the proper KeyMaster Course, beginning AFTER the Foundation
// Course (Foundation Stages 1–4). Appended to LEARN_STEPS after STAGE3_TWOHANDS_STEPS,
// so no Foundation step, title, chapter index, or resume position shifts.
//
// This module ships the OPENING ON-RAMP only — the "Reading Shapes into Music"
// chapter — and uses the existing educational-diagram renderer (whole noteheads,
// no manuscript). Proper manuscript (barlines, measures, time signature, note
// values, rests) is a separate gated track delivered before the first true piece.
//
// Original KeyMaster material. The Grade 1 practical + theory level is an INTERNAL
// seriousness benchmark only — no exam-board wording, repertoire, descriptors, or
// published exercises are used or reproduced anywhere.
//
// Voice: each step carries NEW `say` lines (id.say), spoken by TTS until recorded —
// no existing/recorded Jack line is touched. Jack-Coach scaffold (hint → reteach →
// gentle support reveal) follows the same data shape proven in Foundation.

export const KEY_LEVEL1_STEPS = [
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The KeyMaster Course begins', id: 'kl1-welcome',
    say: [
      { text: 'You have completed the Foundation Course. The whole map is yours now \u2014 the keyboard, the staff, the note names, and a steady pulse.', pauseAfter: 640, tone: 'warm' },
      { text: 'From here, the KeyMaster Course begins. This is Key Level 1 \u2014 First Musicianship.', pauseAfter: 520, tone: 'instruct' },
      { text: 'Everything you have learned now starts to become music: reading, rhythm, your hands, harmony, and your first real pieces \u2014 with me beside you the whole way.', pauseAfter: 380, tone: 'warm' },
    ],
    explain: ['You have completed the Foundation Course. Now the KeyMaster Course begins \u2014 Key Level 1, First Musicianship.', 'From here, reading, rhythm, technique, harmony, and pieces grow together. This is where you begin to play and think as a musician.'],
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Shapes are the building blocks', id: 'kl1-shapes-recap',
    say: [
      { text: 'In the Foundation you learned how notes move \u2014 by step, by skip, or by repeat. Those small moves are the building blocks of every melody.', pauseAfter: 600, tone: 'warm' },
      { text: 'Now we use them to make music. Read the shape, hear it, and play it \u2014 a little more each time.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Notes move by step, by skip, or by repeat \u2014 the building blocks of melody you met in the Foundation.', 'In Key Level 1 we turn those shapes into phrases, then into pieces \u2014 read, heard, and played.'],
    show: { kind: 'staff', clef: 'treble', notes: [ { midi: 67, value: 'whole' }, { midi: 69, value: 'whole' }, { midi: 71, value: 'whole' } ], caption: 'Step, skip, repeat \u2014 the building blocks of melody.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Your first phrase', id: 'kl1-first-phrase',
    say: [
      { text: 'Here is a short phrase. Read it as one shape \u2014 it rises by step, then returns home.', pauseAfter: 600, tone: 'warm' },
      { text: 'Listen to it first, then play it back.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['A five-note phrase that rises by step and returns \u2014 read it as one shape, not five separate notes.', 'Hear it, then play it in order.'],
    show: { kind: 'staff', clef: 'treble', notes: [ { midi: 67, value: 'whole' }, { midi: 69, value: 'whole' }, { midi: 71, value: 'whole' }, { midi: 69, value: 'whole' }, { midi: 67, value: 'whole' } ], caption: 'A little phrase \u2014 it rises by step, then returns home.' },
    demo: [67, 69, 71, 69, 67], demoGap: 0.46,
    tryPrompt: 'Play the phrase you see \u2014 up by step, then back home.',
    targets: [67, 69, 71, 69, 67], mode: 'sequence',
    okMsg: 'That sounded like music \u2014 a phrase with a shape, rising and returning. Beautifully read.',
    hint: 'Read it as a shape: step up, step up, then step back down the same way.',
    reteach: 'Take it gently \u2014 the phrase climbs three notes by step, then comes back down to where it started.',
    support: { highlight: [67, 69, 71], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Echo the phrase', id: 'kl1-phrase-echo',
    say: [
      { text: 'Now an echo. I will play a short phrase \u2014 listen to its shape, then play it back to me.', pauseAfter: 600, tone: 'warm' },
      { text: 'This one steps gently down, coming home.', pauseAfter: 320, tone: 'instruct' },
    ],
    explain: ['Listen to the phrase, then echo it back \u2014 the same shape, in your own time.', 'It steps downward and settles, like a line coming home.'],
    show: { kind: 'staff', clef: 'treble', notes: [ { midi: 72, value: 'whole' }, { midi: 71, value: 'whole' }, { midi: 69, value: 'whole' }, { midi: 67, value: 'whole' } ], caption: 'Listen, then echo \u2014 it steps down, coming home.' },
    demo: [72, 71, 69, 67], demoGap: 0.46,
    tryPrompt: 'Echo the phrase \u2014 stepping down, coming home.',
    targets: [72, 71, 69, 67], mode: 'sequence',
    okMsg: 'Yes \u2014 you heard the shape and echoed it. That is real musical listening.',
    hint: 'Listen again to the shape \u2014 it steps down, one note at a time, and settles at the bottom.',
    reteach: 'Hear it as a falling line: each note is one step lower than the last, until it comes to rest.',
    support: { highlight: [72, 71, 69, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The pulse beneath the music', id: 'kl1-pulse-feel',
    say: [
      { text: 'Every piece of music has a pulse \u2014 a steady beat underneath, like a calm, unhurried heartbeat. You can feel it before you play a single note.', pauseAfter: 640, tone: 'warm' },
      { text: 'A musician feels that pulse first, then places the notes onto it. We will not rush \u2014 we feel the beat, and let the music rest on top of it.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['Music sits on a steady pulse \u2014 an even beat underneath, like a calm, unhurried heartbeat.', 'Feel the pulse first; the notes rest on top of it. This is the difference between playing in time and merely playing the right notes.'],
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Play on the beat', id: 'kl1-pulse-play',
    say: [
      { text: 'Let us feel four steady beats together. Count with me \u2014 one, two, three, four \u2014 evenly, never hurried.', pauseAfter: 620, tone: 'warm' },
      { text: 'Then play any note once on each beat, landing exactly with the pulse. Listen first, then join in.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['Count four even beats \u2014 one, two, three, four \u2014 and play a note exactly on each one.', 'Listen to the pulse first, then place each note onto a beat. Steady matters far more than fast.'],
    show: { kind: 'pulse' },
    tryPrompt: 'Play a note on each beat \u2014 one, two, three, four \u2014 landing with the pulse.',
    mode: 'count', count: 4,
    okMsg: 'Beautifully steady \u2014 you placed each note onto the pulse. That is what playing in time feels like.',
    hint: 'Let the count lead you \u2014 wait for each beat, then play exactly on it, not before.',
    reteach: 'Listen to the steady beat once more, then play one note on each pulse \u2014 even, unhurried, one to a beat.',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'How long each note lasts', id: 'kl1-notes-values',
    say: [
      { text: 'Notes do not only tell you which key to play \u2014 they tell you how long to hold it. The shape of the note is its length.', pauseAfter: 640, tone: 'warm' },
      { text: 'A semibreve, the whole note, is held for four beats. A minim, the half note, lasts two. A crotchet, the quarter note, is one beat. The longer notes are hollow; the crotchet is filled in.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['A note\u2019s shape tells you its length. A semibreve (whole note) is held for four beats; a minim (half note) for two; a crotchet (quarter note) for one.', 'The longer notes are hollow; the crotchet is filled in, with a stem. Same pitch, different lengths \u2014 this is rhythm beginning.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 67, value: 'whole' }, { midi: 67, value: 'half' }, { midi: 67, value: 'quarter' } ], caption: 'Semibreve (4 beats) \u00B7 minim (2 beats) \u00B7 crotchet (1 beat) \u2014 same note, different lengths.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Read the lengths and play', id: 'kl1-notes-read',
    say: [
      { text: 'Here is a short line in four-four time \u2014 four beats in the bar. Read the lengths as you play: two crotchets, then a minim held across two beats.', pauseAfter: 640, tone: 'warm' },
      { text: 'Listen to it first, then play the same notes, giving the long note its full length.', pauseAfter: 340, tone: 'instruct' },
    ],
    explain: ['A short line in four-four time. Read each note\u2019s length: two crotchets, one beat each, then a minim held for two \u2014 four beats in the bar.', 'Hear it, then play it, letting the minim breathe for its full two beats.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'half', finger: 3 } ], bars: [3], caption: 'Four-four time \u2014 crotchet, crotchet, minim. Four beats in the bar.' },
    demo: [60, 62, 64], demoGap: 0.5,
    tryPrompt: 'Play the line \u2014 two short notes, then the longer note held for two beats.',
    targets: [60, 62, 64], mode: 'sequence',
    okMsg: 'Yes \u2014 and you let the minim breathe for its full length. That is reading rhythm, not only notes.',
    hint: 'Read the lengths left to right: two short notes, then a longer one held twice as long.',
    reteach: 'Slowly now \u2014 play the two short notes, one beat each, then hold the last note for two full beats. The lit keys will guide your hand.',
    support: { highlight: [60, 62, 64], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Morning Steps \u2014 listen first', id: 'kl1-piece-listen',
    say: [
      { text: 'Now your first real piece from manuscript \u2014 a little tune called Morning Steps. Look at it as a whole before you play.', pauseAfter: 640, tone: 'warm' },
      { text: 'The right hand rests over five notes, the thumb on C. It steps gently upward, then returns home and settles. Listen to how it sounds.', pauseAfter: 400, tone: 'instruct' },
    ],
    explain: ['Your first piece from manuscript: Morning Steps. The right hand sits over five notes \u2014 thumb on C \u2014 stepping gently upward, then home.', 'Read it as music: a rising line that turns and settles. Listen first, and let the shape sink in before you play.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'half', finger: 3 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Morning Steps \u2014 four-four time. It steps up, then returns home.' },
    demo: [60, 62, 64, 65, 64, 60], demoGap: 0.48,
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Morning Steps \u2014 now you play', id: 'kl1-piece-play',
    say: [
      { text: 'Now you play Morning Steps. Read the shape \u2014 four steps up, then home. Take your time; the notes matter more than the speed.', pauseAfter: 640, tone: 'warm' },
      { text: 'If you wander, I will help you find your way \u2014 a small hint first, and a closer look only if you need it.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Play Morning Steps from the manuscript. Read the rising shape \u2014 four steps up, then a turn and home \u2014 and let your fingers follow it.', 'Unhurried and even. Reading the shape well comes before playing fast.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'half', finger: 3 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Morning Steps \u2014 read the shape, and play it through.' },
    demo: [60, 62, 64, 65, 64, 60], demoGap: 0.48,
    tryPrompt: 'Play Morning Steps \u2014 up by step to the top, then turn and come home.',
    targets: [60, 62, 64, 65, 64, 60], mode: 'sequence',
    okMsg: 'That was real music \u2014 your first piece, read from the page and played with shape. Beautifully done.',
    hint: 'Follow the shape: it climbs four notes by step, then turns and comes home. Check where your hand sits against the next note.',
    reteach: 'Gently \u2014 the line rises one step at a time to the top, then steps down and rests on the note it began with. The lit keys will guide your hand.',
    support: { highlight: [60, 62, 64, 65, 64, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Rests \u2014 the silence in music', id: 'kl1-rests-intro',
    say: [
      { text: 'Music is not only sound. The silences matter just as much \u2014 and they are written down too. A written silence is called a rest.', pauseAfter: 640, tone: 'warm' },
      { text: 'Each note length has a matching rest. A crotchet rest is one beat of silence; a minim rest, two. You count a rest exactly as carefully as a note \u2014 the beat keeps going underneath.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['A rest is a written silence. Every note length has a matching rest \u2014 a crotchet rest is one beat of silence, a minim rest two beats.', 'The pulse never stops during a rest. You keep counting; you simply do not play. Silence is part of the music, not a gap in it.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 67, value: 'quarter' }, { rest: 'quarter' }, { midi: 67, value: 'quarter' }, { rest: 'quarter' } ], bars: [4], caption: 'Crotchet, crotchet rest, crotchet, crotchet rest \u2014 sound, silence, sound, silence.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Play through a rest', id: 'kl1-rests-play',
    say: [
      { text: 'Now read a short bar with a rest in it. Play the first note, then keep the second beat silent \u2014 that is the rest \u2014 then play the last two.', pauseAfter: 640, tone: 'warm' },
      { text: 'Count steadily through the silence: one, two, three, four. Do not let the rest hurry you on.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Read the bar: play on beat one, stay silent on beat two (the rest), then play on beats three and four.', 'Count right through the rest \u2014 one, two, three, four \u2014 so the silence keeps its full length.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 64, value: 'quarter', finger: 3 }, { rest: 'quarter' }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'quarter', finger: 1 } ], bars: [4], caption: 'Play \u00B7 rest \u00B7 play \u00B7 play \u2014 keep counting through the silence.' },
    tryPrompt: 'Play the bar \u2014 first note, a silent beat, then the last two notes.',
    targets: [64, 62, 60], mode: 'sequence',
    okMsg: 'Good \u2014 you let the rest breathe and kept your count. Silence handled like a musician.',
    hint: 'Three notes are played, with a silent beat after the first. Read the shape \u2014 it steps gently down to home.',
    reteach: 'Slowly \u2014 play the first note, count the silent beat, then step down two notes to the bottom. The lit keys will guide you.',
    support: { highlight: [64, 62, 60], replay: false },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Blue Window \u2014 listen first', id: 'kl1-blue-listen',
    say: [
      { text: 'Here is a second piece \u2014 Blue Window. This one falls gently, like a line drawn downward, then turns and comes home.', pauseAfter: 640, tone: 'warm' },
      { text: 'The right hand stays in its five-note home, thumb on C. Look at the shape, then listen to how it sounds.', pauseAfter: 400, tone: 'instruct' },
    ],
    explain: ['Your second piece: Blue Window. A gentle falling line \u2014 it steps downward from G, then turns and settles home on C.', 'Read the shape as a whole \u2014 a calm descent and a return. Listen first, and let it settle before you play.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 67, value: 'quarter', finger: 5 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'half', finger: 3 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Blue Window \u2014 four-four time. It falls by step, then turns home.' },
    demo: [67, 65, 64, 62, 64, 60], demoGap: 0.48,
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Blue Window \u2014 now you play', id: 'kl1-blue-play',
    say: [
      { text: 'Now you play Blue Window. Read the falling shape \u2014 G stepping down, then a turn and home to C. Unhurried.', pauseAfter: 640, tone: 'warm' },
      { text: 'Let the long notes at the end breathe. If you lose your way, I will guide you gently.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Play Blue Window from the manuscript. Read the falling shape \u2014 a gentle step-wise descent from G, then a turn and home to C.', 'Give the two minims at the end their full length. Read the shape; let the fingers follow.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 67, value: 'quarter', finger: 5 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'half', finger: 3 }, { midi: 60, value: 'half', finger: 1 } ], bars: [4], caption: 'Blue Window \u2014 read the falling shape, and play it through.' },
    demo: [67, 65, 64, 62, 64, 60], demoGap: 0.48,
    tryPrompt: 'Play Blue Window \u2014 falling by step from G, then a turn and home to C.',
    targets: [67, 65, 64, 62, 64, 60], mode: 'sequence',
    okMsg: 'Lovely \u2014 a calm, shaped line, read from the page and brought home. Two pieces now in your hands.',
    hint: 'Follow the shape downward \u2014 each note one step lower \u2014 then it lifts back up and settles home. Check the next note against where your hand is.',
    reteach: 'Gently \u2014 the line steps down four notes from the top, then rises one step and rests on home. The lit keys will guide your hand.',
    support: { highlight: [67, 65, 64, 62, 64, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The left hand and the bass clef', id: 'kl1-lh-intro',
    say: [
      { text: 'So far your right hand has done the playing. Now the left hand joins, and it usually reads from the bass clef \u2014 the lower of the two clefs.', pauseAfter: 640, tone: 'warm' },
      { text: 'The bass clef carries the deeper notes, below Middle C. Here is a short left-hand line \u2014 notice the fingering counts the other way: the thumb is finger one, on the higher note.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['The left hand usually reads the bass clef \u2014 the lower clef, carrying the deeper notes below Middle C.', 'Left-hand fingering mirrors the right: the thumb is still finger one, but it now sits on the higher note, so the little finger takes the lowest note.'],
    show: { kind: 'staff', clef: 'bass', notes: [ { midi: 48, value: 'whole', finger: 5 } ], caption: 'The bass clef \u2014 the left hand\u2019s home. This low C is played by the little finger.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A first left-hand line', id: 'kl1-lh-play',
    say: [
      { text: 'Let your left hand rest over five notes, the little finger on the low C. Now play a gentle line \u2014 up by step, then back home.', pauseAfter: 640, tone: 'warm' },
      { text: 'Read it from the bass clef, and keep the hand calm. Listen first, then play.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Rest the left hand over five notes \u2014 little finger on low C. Play up by step to F, then turn and come home.', 'Read from the bass clef. Keep the hand still and let the fingers do the moving.'],
    show: { kind: 'staff', clef: 'bass', timeSig: [4, 4], notes: [ { midi: 48, value: 'quarter', finger: 5 }, { midi: 50, value: 'quarter', finger: 4 }, { midi: 52, value: 'quarter', finger: 3 }, { midi: 53, value: 'quarter', finger: 2 }, { midi: 52, value: 'half', finger: 3 }, { midi: 48, value: 'half', finger: 5 } ], bars: [4], caption: 'A left-hand line in the bass clef \u2014 up by step, then home.' },
    demo: [48, 50, 52, 53, 52, 48], demoGap: 0.5,
    tryPrompt: 'Play the left-hand line \u2014 up by step from low C, then turn and home.',
    targets: [48, 50, 52, 53, 52, 48], mode: 'sequence',
    okMsg: 'Well done \u2014 your left hand reading and playing from the bass clef. Both hands can read music now.',
    hint: 'Read the bass clef shape \u2014 it climbs by step, then turns and steps back down to where it began.',
    reteach: 'Slowly \u2014 little finger starts on low C, climb four notes by step, then come back down to home. The lit keys will guide your hand.',
    support: { highlight: [48, 50, 52, 53, 52, 48], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Both hands on the grand staff', id: 'kl1-hands-intro',
    say: [
      { text: 'Piano music joins the two clefs into one system \u2014 the grand staff. The treble clef on top for the right hand, the bass clef below for the left.', pauseAfter: 640, tone: 'warm' },
      { text: 'Reading both at once takes care, so we begin very gently: the left hand will hold one steady note while the right hand plays above it.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['The grand staff joins both clefs into one system \u2014 treble on top for the right hand, bass below for the left.', 'Two hands at once is the heart of piano playing. We begin gently: one held note in the left hand, a small melody in the right.'],
    show: { kind: 'staff', clef: 'grand', middleC: true, caption: 'The grand staff \u2014 right hand above, left hand below, joined by a brace.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A first move with both hands', id: 'kl1-hands-play',
    say: [
      { text: 'Here is your first move with both hands. Play the low C with your left hand and keep it gently held down.', pauseAfter: 620, tone: 'warm' },
      { text: 'Then, above it, play three notes with your right hand \u2014 C, E, G \u2014 the home chord, one note after another. Left first, then right.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['Your first two-hand move: the left hand plays and holds a low C, an anchor underneath.', 'Then the right hand plays C, E, G above it \u2014 one after another. The hands take turns: left settles first, then the right hand plays over the top.'],
    show: { kind: 'staff', clef: 'grand', timeSig: false, notes: [ { midi: 48, value: 'whole', finger: 5 }, { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 } ], caption: 'Left hand holds low C; right hand plays C, E, G above.' },
    demo: [48, 60, 64, 67], demoGap: 0.55,
    tryPrompt: 'Left hand plays and holds low C; then the right hand plays C, E, G above it.',
    targets: [48, 60, 64, 67], mode: 'sequence',
    okMsg: 'That is your first sound from two hands together \u2014 a held bass note and a melody above. A real pianist\u2019s texture.',
    hint: 'Start with the left hand on the low note, then move to the right hand and rise through the three notes above.',
    reteach: 'Gently \u2014 the low note first with the left hand, held; then the right hand climbs C, E, G. The lit keys show the path.',
    support: { highlight: [48, 60, 64, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Why fingering matters', id: 'kl1-finger-why',
    say: [
      { text: 'You may have noticed small numbers beside the notes. Those are fingering \u2014 they tell you which finger to use, and they are chosen with care.', pauseAfter: 640, tone: 'warm' },
      { text: 'Good fingering lets your hand stay calm and reach every note without jumping about. The right finger in the right place is what makes playing feel easy.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['The small numbers beside notes are fingering: one is the thumb, up to five at the little finger. They are not random \u2014 they are chosen so the hand can move smoothly.', 'Good fingering keeps the hand settled and lets it reach every note without leaping. Trust the numbers, and playing becomes far easier.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 67, value: 'quarter', finger: 5 } ], caption: 'One finger to each note \u2014 thumb on C, up to the little finger on G.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'A smooth, connected touch', id: 'kl1-finger-play',
    say: [
      { text: 'Now play with a smooth, connected touch \u2014 we call it legato. Each note joins to the next with no gap, as if drawing one unbroken line.', pauseAfter: 640, tone: 'warm' },
      { text: 'Hold each key just until the next one sounds, then release. The fingering keeps your hand steady so the line can stay smooth.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Legato means smooth and connected \u2014 each note joined to the next with no gap between them.', 'Hold each key until the next sounds, then let go. With the hand settled on its fingering, the line flows as one.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 60, value: 'quarter', finger: 1 } ], bars: [4], caption: 'A smooth line \u2014 connect each note to the next, no gaps.' },
    demo: [60, 62, 64, 60], demoGap: 0.5,
    tryPrompt: 'Play the four notes smoothly \u2014 each joined to the next, no gaps.',
    targets: [60, 62, 64, 60], mode: 'sequence',
    okMsg: 'That had a smooth, singing line \u2014 connected and calm. That is legato touch.',
    hint: 'Read the small shape \u2014 it steps up, then returns to where it started. Aim to join each note to the next.',
    reteach: 'Gently \u2014 thumb on C, step up to E, then back to the thumb. Connect the sound, no gaps. The lit keys will guide you.',
    support: { highlight: [60, 62, 64, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Steps and skips \u2014 2nds and 3rds', id: 'kl1-intervals-intro',
    say: [
      { text: 'The distance between two notes is called an interval, and we name intervals by number. Two notes next-door to each other make a 2nd \u2014 that is a step.', pauseAfter: 640, tone: 'warm' },
      { text: 'Skip a note, and the distance grows to a 3rd \u2014 that is a skip. From C, the next-door D is a 2nd; jump over D to E, and that is a 3rd.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['An interval is the distance between two notes, named by number. Notes next to each other are a 2nd \u2014 a step.', 'Skip one note and you reach a 3rd \u2014 a skip. C up to D is a 2nd; C up to E, skipping D, is a 3rd. Reading these distances is faster than naming every note.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 } ], caption: 'C to D is a 2nd (a step) \u00B7 C to E, skipping D, is a 3rd (a skip).' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Hear a step, hear a skip', id: 'kl1-intervals-play',
    say: [
      { text: 'Now play a line that uses both. First three steps \u2014 C, D, E, each a 2nd \u2014 then a skip up to G, a 3rd.', pauseAfter: 640, tone: 'warm' },
      { text: 'Listen to how the skip opens up wider than the steps. Hear it first, then play it.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Play C, D, E \u2014 three notes a step apart, each a 2nd \u2014 then skip up to G, a 3rd.', 'Notice the skip sounds wider than the steps. Reading by distance \u2014 step or skip \u2014 is how fluent readers move.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 } ], bars: [4], caption: 'Steps up by 2nds \u2014 C, D, E \u2014 then a skip of a 3rd to G.' },
    demo: [60, 62, 64, 67], demoGap: 0.5,
    tryPrompt: 'Play three steps up \u2014 C, D, E \u2014 then skip a 3rd to G.',
    targets: [60, 62, 64, 67], mode: 'sequence',
    okMsg: 'Yes \u2014 you felt the difference: three steps, then a wider skip. That is reading by interval.',
    hint: 'Three notes move by step, close together; then the last one leaps wider. Read the distances, not the names.',
    reteach: 'Slowly \u2014 step up C, D, E one at a time, then skip past F to land on G. The lit keys will guide your hand.',
    support: { highlight: [60, 62, 64, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The five-finger pattern', id: 'kl1-fivefinger-play',
    say: [
      { text: 'Here is a pattern every pianist learns \u2014 the five-finger pattern. Your hand stays perfectly still, one finger to each note, up to the top and back.', pauseAfter: 640, tone: 'warm' },
      { text: 'From C, climb by step to G \u2014 thumb to little finger \u2014 then come back down. No jumping; the hand stays home. Listen, then play.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['The five-finger pattern: five notes, five fingers, the hand completely still. From C, step up to G \u2014 thumb, two, three, four, five \u2014 then step back down to C.', 'It trains evenness and a calm hand. Many pieces live inside this shape, so it is worth playing until it feels effortless.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 67, value: 'quarter', finger: 5 }, { midi: 65, value: 'quarter', finger: 4 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'quarter', finger: 1 } ], caption: 'Up to G and back \u2014 one finger to each note, the hand staying home.' },
    demo: [60, 62, 64, 65, 67, 65, 64, 62, 60], demoGap: 0.42,
    tryPrompt: 'Play the five-finger pattern \u2014 up by step from C to G, then back down to C.',
    targets: [60, 62, 64, 65, 67, 65, 64, 62, 60], mode: 'sequence',
    okMsg: 'Beautifully even, and your hand stayed home the whole way. That pattern is the foundation of so much playing.',
    hint: 'Climb by step to the top, then reverse exactly \u2014 the way down mirrors the way up. Keep the hand still.',
    reteach: 'Gently and evenly \u2014 thumb on C, step up one finger at a time to the little finger on G, then step back down the same path. The lit keys will guide you.',
    support: { highlight: [60, 62, 64, 65, 67], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Home note \u2014 the tonic', id: 'kl1-harmony-tonic',
    say: [
      { text: 'Every key has a home note \u2014 the note the music rests on, where a tune feels finished. Musicians call it the tonic.', pauseAfter: 640, tone: 'warm' },
      { text: 'In the key of C major, the home note is C. You have felt it already \u2014 both your pieces came to rest on C. That feeling of arriving home is the tonic.', pauseAfter: 420, tone: 'instruct' },
    ],
    explain: ['Every key has a home note \u2014 the tonic \u2014 where music feels settled and complete. In C major, that home note is C.', 'You have heard it without naming it: Morning Steps and Blue Window both came to rest on C. That sense of arriving home is the pull of the tonic.'],
    show: { kind: 'staff', clef: 'treble', notes: [ { midi: 60, value: 'whole', finger: 1, letter: 'C' } ], middleC: false, caption: 'C \u2014 the home note, the tonic of C major. Where the music comes to rest.' },
    mode: 'none',
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'The home chord, one note at a time', id: 'kl1-harmony-triad',
    say: [
      { text: 'Three notes belong specially to the home note: C, E and G. Together they make the home chord \u2014 the tonic triad. Built from C, skipping to E, skipping again to G.', pauseAfter: 640, tone: 'warm' },
      { text: 'Played all at once they make a chord; played one after another they make a broken chord. Let us play it broken \u2014 C, E, G, and back. Listen, then play.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['The home chord \u2014 the tonic triad \u2014 is built on C: C, then a skip to E, then a skip to G. Three notes that belong together.', 'Sounded together they are a chord; sounded one at a time they are a broken chord. Playing it broken \u2014 C, E, G and back \u2014 lets you hear each note of the harmony.'],
    show: { kind: 'staff', clef: 'treble', timeSig: false, notes: [ { midi: 60, value: 'quarter', finger: 1 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 67, value: 'quarter', finger: 5 }, { midi: 64, value: 'quarter', finger: 3 }, { midi: 60, value: 'quarter', finger: 1 } ], caption: 'The tonic triad as a broken chord \u2014 C, E, G, then back home.' },
    demo: [60, 64, 67, 64, 60], demoGap: 0.46,
    tryPrompt: 'Play the home chord broken \u2014 C, E, G, then back down to C.',
    targets: [60, 64, 67, 64, 60], mode: 'sequence',
    okMsg: 'That is the sound of home harmony \u2014 the tonic triad, the chord at the heart of the key. Your first harmony.',
    hint: 'Skip upward through the chord \u2014 each note a 3rd above the last \u2014 then come back down the same way.',
    reteach: 'Gently \u2014 thumb on C, skip to E with finger three, skip to G with finger five, then back down. The lit keys will guide your hand.',
    support: { highlight: [60, 64, 67, 64, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Listen, then echo \u2014 by ear', id: 'kl1-echo-task',
    say: [
      { text: 'This time there is no music to read. I will play a short phrase, and you play it straight back to me \u2014 by ear alone.', pauseAfter: 640, tone: 'warm' },
      { text: 'Listen to the shape: where it rises, where it falls. Hold it in your ear, then find it on the keys. Listen carefully now.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['No notation this time \u2014 pure listening. I play a short phrase; you echo it straight back from memory.', 'Hold the shape in your ear \u2014 its rise and fall \u2014 then find it on the keys. Playing by ear is a musician\u2019s deepest skill.'],
    demo: [62, 64, 65, 64], demoGap: 0.46,
    tryPrompt: 'Play back the phrase you just heard \u2014 by ear.',
    targets: [62, 64, 65, 64], mode: 'sequence',
    okMsg: 'You held the shape in your ear and found it on the keys \u2014 with no notation at all. That is real musicianship.',
    hint: 'Sing the shape back in your head first \u2014 it rises a little, lifts once more, then settles back. Then find those notes.',
    reteach: 'Listen again to the shape: it steps up, lifts to the highest note, then comes back. The lit keys will show you where it lives.',
    support: { highlight: [62, 64, 65, 64], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Sight-reading \u2014 read it cold', id: 'kl1-sight-micro',
    say: [
      { text: 'Now a sight-reading moment. This is a phrase you have not heard \u2014 and I will not play it for you. Reading something new, on your own, is sight-reading.', pauseAfter: 660, tone: 'warm' },
      { text: 'Look before you play. Find the shape \u2014 does it step up or down? Then play it, calmly, in your own time.', pauseAfter: 380, tone: 'instruct' },
    ],
    explain: ['Sight-reading means reading and playing something new without hearing it first. No demonstration this time \u2014 the reading is yours.', 'Look first: find the starting note and the shape of the line. Then play it slowly and steadily. Reading before playing is the whole habit.'],
    show: { kind: 'staff', clef: 'treble', timeSig: [4, 4], notes: [ { midi: 64, value: 'quarter', finger: 3 }, { midi: 62, value: 'quarter', finger: 2 }, { midi: 60, value: 'half', finger: 1 } ], bars: [3], caption: 'Read it yourself \u2014 find the shape, then play. No listening first.' },
    tryPrompt: 'Read the line and play it \u2014 on your own, without hearing it first.',
    targets: [64, 62, 60], mode: 'sequence',
    okMsg: 'You read that one cold and played it true \u2014 sight-reading, the skill that opens every piece of music to you.',
    hint: 'Find the first note, then follow the shape \u2014 it steps downward, one note at a time, to a held note at the bottom.',
    reteach: 'Take it slowly \u2014 the line begins up high and steps down to a long note at home. Now the keys are lit to show you; read the shape with them.',
    support: { highlight: [64, 62, 60], replay: true },
  },
  {
    eyebrow: 'KeyMaster Course \u00B7 Key Level 1', title: 'Key Level 1 \u2014 how far you have come', id: 'kl1-review',
    say: [
      { text: 'Take a moment. Look at how much you can do now. You read shapes instead of spelling out every note. You feel a pulse and count through rests.', pauseAfter: 640, tone: 'warm' },
      { text: 'You read both clefs, play with each hand, and have begun bringing them together. You know steps and skips, the home note, and the home chord \u2014 and you have two real pieces in your hands.', pauseAfter: 480, tone: 'warm' },
      { text: 'This is genuine musicianship beginning. When you are ready, Key Level 2 \u2014 Confident Reading \u2014 will take it further. Beautifully done.', pauseAfter: 360, tone: 'instruct' },
    ],
    explain: ['Look back at Key Level 1. You read music by shape, feel a steady pulse, count note values and rests, and read both treble and bass clefs.', 'You play with each hand and have begun two-hand coordination; you understand steps, skips, the tonic, and the tonic triad; and you have played real pieces \u2014 Morning Steps and Blue Window \u2014 from manuscript.', 'These are the true first foundations of musicianship. Key Level 2 \u2014 Confident Reading \u2014 builds directly on them when you are ready. This is a real beginning, beautifully made.'],
    show: { kind: 'staff', clef: 'grand', middleC: true, caption: 'Both clefs, both hands, the home note at the centre \u2014 the ground you now stand on.' },
    mode: 'none',
  },
];
