/* sw.js — KeyMaster PRO service worker.
   =============================================================================
   Purpose: make KeyMaster PRO an installable PWA so it can open in
   standalone / full-screen (no browser chrome), and work offline. An app is
   only installable if it has a registered service worker with a fetch handler
   plus a valid manifest over HTTPS — which is exactly what GitHub Pages serves.

   Strategy (deliberately conservative, so a new build never gets "stuck"):
     • HTML / navigations  → network-first, fall back to cache (offline).
       New builds always load when online; the shell is never pinned stale.
     • Same-origin GET assets → cache-first. The app's JS/CSS carry ?v= cache
       tokens, so a new build is a new URL = guaranteed fresh fetch; old entries
       are orphaned and cleared on activate.
     • Cross-origin (e.g. Google Fonts) → not intercepted; passes through.
   Bump CACHE on each release so activate clears the previous cache.
   ============================================================================= */

const CACHE = 'keymaster-rc2-172';
const CORE = ['./', './index.html', './manifest.json', './icon-192.png', './icon-512.png', './icon-maskable-192.png', './icon-maskable-512.png', './icon-180.png'];
// Course sampled-piano files (assets/piano/salamander-lite/*.mp3 + manifest.json,
// generated by the build-salamander-lite Action) and tutor voice MP3s
// (voice/en-GB/*.mp3) are NOT precached at install. They are small and lazy —
// the sampler loads them only after the first audio-unlock gesture — and the
// runtime cache-first handler below caches each on first fetch, so they work
// offline after the first Course session WITHOUT a heavy mandatory first load.

self.addEventListener('install', (event) => {
  // Take over ASAP. A previous worker without this line could otherwise keep
  // serving old JS forever (the update banner that releases it lives in code the
  // old worker won't load — a catch-22). skipWaiting + network-first HTML +
  // controllerchange-reload makes a deploy land automatically on next open.
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(CORE).catch(() => {}))
      .catch(() => {}),
    // NOTE: no skipWaiting() here — a new build WAITS until the user taps
    // "Update now" (pwaUpdate.js posts SKIP_WAITING), so updates are visible
    // and the app never silently swaps assets mid-session.
  );
});

// Take over immediately once the user has opted in to the update.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  let url;
  try { url = new URL(req.url); } catch { return; }
  if (url.origin !== self.location.origin) return;          // leave cross-origin alone

  const isHTML = req.mode === 'navigate'
    || url.pathname.endsWith('/')
    || url.pathname.endsWith('index.html');

  if (isHTML) {
    // Network-first: always try the live shell, fall back to cache offline.
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || caches.match('./index.html'))),
    );
    return;
  }

  // Cache-first for versioned static assets (safe: new versions are new URLs).
  event.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res && res.status === 200 && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
      }
      return res;
    }).catch(() => hit)),
  );
});
